<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cross-Cutting Issues</name>
   <tag></tag>
   <elementGuidId>486d34aa-c606-462c-b7c3-2e63ed83989c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='cd-primary-nav-secondary-desktop']/li/ul/li/ul/li/div/ul/li[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8c2d65b-3f59-4e0e-b98c-c08a91f2ba30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-border-wrapper</value>
      <webElementGuid>fd762890-ee65-415f-b976-cc9d1b29c9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cross-Cutting Issues</value>
      <webElementGuid>3995efbb-30f1-423d-8ad1-3981ac2efa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cd-primary-nav-secondary-desktop&quot;)/li[@class=&quot;has-children menu-is-active menu-is-open&quot;]/ul[@class=&quot;cd-secondary-nav&quot;]/li[@class=&quot;has-children&quot;]/ul[@class=&quot;main-primary-menu inner-agency-ul&quot;]/li[@class=&quot;has-children&quot;]/div[@class=&quot;unorder-flex&quot;]/ul[@class=&quot;batch-wrapper&quot;]/li[@class=&quot;batch-column-1&quot;]/a[1]/span[@class=&quot;menu-border-wrapper&quot;]</value>
      <webElementGuid>81b1069c-64c9-4e00-aa39-e8af2eaf2f31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cd-primary-nav-secondary-desktop']/li/ul/li/ul/li/div/ul/li[4]/a/span</value>
      <webElementGuid>b5f9fd7f-023c-4732-b765-812d9ec4193e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combating Child Labor, Forced Labor, and Human Trafficking'])[1]/following::span[1]</value>
      <webElementGuid>97dd9f3c-83e4-4d0b-98d1-eb32d170a86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strengthening Labor Standards'])[1]/following::span[2]</value>
      <webElementGuid>5c7c6219-7d77-47f6-89b3-a5071140e3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Assistance'])[1]/preceding::span[1]</value>
      <webElementGuid>d303d852-144d-44c9-a269-5d725c4be427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring, Evaluation, Research and Learning'])[1]/preceding::span[2]</value>
      <webElementGuid>125f04f6-9e8d-4d8f-b6f9-8d355c26b7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cross-Cutting Issues']/parent::*</value>
      <webElementGuid>02e3018a-44b9-40ed-91d4-2d4e0bec2b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li[4]/a/span</value>
      <webElementGuid>a7abccde-2b45-4b2b-843f-461607380d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cross-Cutting Issues' or . = 'Cross-Cutting Issues')]</value>
      <webElementGuid>c15cb8d5-054e-46da-9dd9-5014290f1bbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
