<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_OUR WORK_svg-inline--fa fa-chevron-down_93c0d7</name>
   <tag></tag>
   <elementGuidId>d85889ad-b81d-4a14-b28b-1d87c040b75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.svg-inline--fa.fa-chevron-down.fa-w-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='OUR WORK'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>57d300a4-8e7a-410e-a456-265e5221b95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-chevron-down fa-w-14</value>
      <webElementGuid>57a45126-e4fd-4b5f-a8d3-89fbe6bdd40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2dab7b3c-5aca-432d-9cd9-aab7acdd4f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1f53c81-605b-499c-baaa-add6da53a8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>120e890a-0d0b-4dd8-97c4-001d5910ae2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>chevron-down</value>
      <webElementGuid>5e737bc0-ab1b-46fa-98c0-d3262fdec80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a5c5556-cdac-4e38-9795-c83031ea206e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>49eb48c4-cbbc-4020-b071-b8750e92e2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 448 512</value>
      <webElementGuid>5c4535a3-9b9c-4573-8304-68427356a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cd-primary-nav-secondary-desktop&quot;)/li[@class=&quot;has-children&quot;]/a[1]/span[@class=&quot;menu-border-wrapper&quot;]/span[@class=&quot;menuarrow&quot;]/svg[@class=&quot;svg-inline--fa fa-chevron-down fa-w-14&quot;]</value>
      <webElementGuid>69a0a1ab-3550-4189-bb33-3e355172c106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OUR WORK'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>2d9747fa-16c8-4182-b458-21f064c0ee36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submenu'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>e383e04e-405b-4220-9092-841ac70363b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What We Do'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>f4542045-637e-4bab-b7ff-c9a93ab0d599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enforcing Trade Commitments'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>5d279e72-fd7c-438f-a752-c275e6ddb1b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
