<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit Person</name>
   <tag></tag>
   <elementGuidId>8e1eee9d-2ad2-43af-a0e2-c56c742d4974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='clientsListGrid']/tbody/tr/td[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb412e5c-9717-40e1-bc4c-c5352e43caff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>c1b67499-9094-477f-b1b2-04c7c41fe592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SDICMS_TEST/Intake/Edit/543160</value>
      <webElementGuid>0e3dda4c-8b74-4871-8260-6b68029f7069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Person</value>
      <webElementGuid>ef7c2dfc-5d28-4138-9a5c-2ee8f96f4672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientsListGrid&quot;)/tbody[1]/tr[@class=&quot;webgrid-row-style&quot;]/td[@class=&quot;EditPersonWidth&quot;]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>6ace3b0f-f5db-46c0-ae1a-ccf2febca5c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='clientsListGrid']/tbody/tr/td[6]/a</value>
      <webElementGuid>c95ce54e-ffad-4ce1-8171-c5e35dffb342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit Person')]</value>
      <webElementGuid>275e18c2-b61d-4ef2-aa51-6dc8f12ab0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulo'])[1]/following::a[1]</value>
      <webElementGuid>170c9748-3d44-4cae-aeb1-4212fd6ef76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulu'])[1]/following::a[1]</value>
      <webElementGuid>9274caba-62c0-4afd-8978-92e180f41930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Assessment'])[1]/preceding::a[1]</value>
      <webElementGuid>d46e5cd0-338a-4405-aaa2-2e214252d896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessment Date'])[1]/preceding::a[2]</value>
      <webElementGuid>b35e4d31-dacf-427e-a3e9-8dbd6bf12afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit Person']/parent::*</value>
      <webElementGuid>dd872bf2-74bd-411c-8f64-3105911301ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SDICMS_TEST/Intake/Edit/543160')]</value>
      <webElementGuid>f2fd9799-703a-4991-a473-f9774acf458f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>f655cbd5-d50f-4ced-943e-476161affa25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SDICMS_TEST/Intake/Edit/543160' and (text() = 'Edit Person' or . = 'Edit Person')]</value>
      <webElementGuid>37b43c74-25f3-4a9c-ba6a-1cf0c0df871d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
