<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create</name>
   <tag></tag>
   <elementGuidId>04c9c863-695c-4397-941c-6dbe48c03e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='intakePanel']/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e2d3ee2-58cc-4be6-8b80-2c01aa90e61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info pull-right</value>
      <webElementGuid>c43906a3-b669-4e42-8d1d-27481a78f09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SDICMS_TEST/Intake/Create</value>
      <webElementGuid>656871ed-167f-4810-869b-2e99f13bd63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>6c178221-6d51-47e4-bd0a-f189a371f791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;intakePanel&quot;)/div[@class=&quot;panel-heading&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-1&quot;]/a[@class=&quot;btn btn-info pull-right&quot;]</value>
      <webElementGuid>672f0e6f-2003-4fce-8f15-2922dbced0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div/div/div[2]/a</value>
      <webElementGuid>c979b59c-7795-4b54-bfb6-2a13cfb88cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create')]</value>
      <webElementGuid>49b29778-244c-40de-9be3-0bb494f02572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intake'])[2]/following::a[1]</value>
      <webElementGuid>6ee65e9e-4c3a-497c-b22d-b3fda63e8f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log off'])[1]/following::a[1]</value>
      <webElementGuid>f4a11b9d-cf44-4258-b824-0aae61e74085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Ref No'])[1]/preceding::a[1]</value>
      <webElementGuid>77f11d09-a1e2-4b65-a6a5-91f358303b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification Number'])[1]/preceding::a[1]</value>
      <webElementGuid>25d4f492-aac8-4859-bca9-d483296cc524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>b6843c43-9321-4cd3-b09c-668dde086e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SDICMS_TEST/Intake/Create')]</value>
      <webElementGuid>3e7325c4-9b38-4ca0-a867-f9269a71ab4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>a9758750-8d77-41c5-ab54-5c8db8747c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SDICMS_TEST/Intake/Create' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>8972937a-91eb-4708-91a6-a42dcdef5285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
