<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Change Password_ButtonSave</name>
   <tag></tag>
   <elementGuidId>89578f63-35e9-4346-82a8-b11be931ec1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ButtonSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ButtonSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48f942b6-10d4-41a7-8d21-b3bd50d6924e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>04ade09c-1217-4e18-a019-1f8e81e5feb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ButtonSave</value>
      <webElementGuid>1119ffe4-c542-4669-9830-ba9e83cb3806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>03edf6d4-7133-432f-933d-b6c8e8a6d507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>8689a8bd-fa15-4bf7-b554-41679a8731ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ButtonSave&quot;)</value>
      <webElementGuid>dc15ee0e-6257-4e1c-8801-743af1075771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ButtonSave']</value>
      <webElementGuid>844966ed-09a7-4d07-a7ce-a11802dbcd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>99b5dfb2-b6a2-4d80-8840-2d5de5fac116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'ButtonSave']</value>
      <webElementGuid>7982ac3d-8bd8-4798-bf7c-c737cebaef70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
