<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create</name>
   <tag></tag>
   <elementGuidId>e18c8d19-ebbc-4b53-86cf-40bb95dd2940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='intakePanel']/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5436b82b-b958-4549-bac5-02b2f5af7539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info pull-right</value>
      <webElementGuid>5e872ca7-5685-4b66-947d-e23382a5db9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SDICMS_TEST/Intake/Create</value>
      <webElementGuid>8ee8bd07-2bda-466c-822d-f42d347ad3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>0263abb0-5936-4b01-8fa1-45ff3113ab29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;intakePanel&quot;)/div[@class=&quot;panel-heading&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-1&quot;]/a[@class=&quot;btn btn-info pull-right&quot;]</value>
      <webElementGuid>c7e79aa5-ffcb-4978-a0e9-134107882cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div/div/div[2]/a</value>
      <webElementGuid>ececb0a8-d8a7-4608-8814-08c886d723e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create')]</value>
      <webElementGuid>7ed6aab6-7e9d-40d3-b4a7-18623c469dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intake'])[2]/following::a[1]</value>
      <webElementGuid>b9947870-5a7d-4f6d-9b85-d34a7f88d0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log off'])[1]/following::a[1]</value>
      <webElementGuid>5a5a65c2-e343-4093-88a6-732cf7374280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Ref No'])[1]/preceding::a[1]</value>
      <webElementGuid>52d79d52-dbec-4b3f-8423-be576d3dadd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification Number'])[1]/preceding::a[1]</value>
      <webElementGuid>5798e2c2-7472-47fa-bff5-c6c7fa20dc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>4e659db6-1850-4322-b003-6aecb69dd2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SDICMS_TEST/Intake/Create')]</value>
      <webElementGuid>809a20e3-029a-4be4-b1d7-ccb452e5ccff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>57d8f8a6-dcd7-49b1-a3a1-2787a035c0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SDICMS_TEST/Intake/Create' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>e927de56-7140-47e6-8cca-8fbe45f6bfbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
