<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Economy</name>
   <tag></tag>
   <elementGuidId>e53631c9-5fb7-4297-948f-5fd12e5f2e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/header/nav/ul/li[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72022a12-1010-48ff-aeed-22b6bc93822c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>fin24/economy</value>
      <webElementGuid>d5d69e6f-aa15-4d1f-af7d-96675d587604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Economy</value>
      <webElementGuid>91ce4cdb-e2f8-41c4-adf5-c5816ab11779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-container</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>97fe6b42-18a6-4d5f-8bbb-0ece7c22f852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-name</name>
      <type>Main</type>
      <value>category_link</value>
      <webElementGuid>12734da9-ced8-4166-8935-f0edd16d4e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-breadcrumb</name>
      <type>Main</type>
      <value>fin24/economy</value>
      <webElementGuid>124fda1a-9606-4494-a018-fd65882d80f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>2e9629fb-8973-4549-84c7-e319b1c4dd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Economy</value>
      <webElementGuid>f1db24c6-a738-450e-8225-686c6d646d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/header[@class=&quot;header&quot;]/nav[@class=&quot;header__nav&quot;]/ul[1]/li[@class=&quot;has-children&quot;]/ul[@class=&quot;sub-nav&quot;]/li[2]/a[1]</value>
      <webElementGuid>ca7868a2-a671-41f5-9318-1812dddb9536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/header/nav/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>1d36a545-c3c4-43ea-b07c-b42af239c5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Economy')]</value>
      <webElementGuid>de09364b-c9d2-4904-bf2d-bb7cc8b5d128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::a[1]</value>
      <webElementGuid>64d409ec-a0c0-4a6e-835e-4ce155344ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/following::a[2]</value>
      <webElementGuid>90c1b3d4-de8f-4314-a3c3-2ad21bf0bb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opinion'])[1]/preceding::a[1]</value>
      <webElementGuid>c70c526c-8b89-4bb4-bff0-c5fd67ae65e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Markets'])[1]/preceding::a[2]</value>
      <webElementGuid>0a6b501f-5a59-466f-b7b4-b9123402a54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Economy']/parent::*</value>
      <webElementGuid>45536b27-5250-4cc4-9190-068037c11016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'fin24/economy')]</value>
      <webElementGuid>7512cca5-4fdb-4a65-9cda-c2360a606fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>d6da58b1-83f4-4cfb-ad40-e1508686ab21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'fin24/economy' and (text() = 'Economy' or . = 'Economy')]</value>
      <webElementGuid>7c98ec24-50f4-4780-99ea-8beb53121492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
