<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Passport DocumentRSA ID Document</name>
   <tag></tag>
   <elementGuidId>4b5b5baa-2696-43ff-921a-684c197581a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownIdentificationType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownIdentificationType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bbee278e-17e6-47fe-9751-d98a52caf2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7cf58e6a-4847-4cb8-b8d6-09b5af5740ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fad7f88-4b5d-40e1-997a-7aa552843c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Identification_Type_Id must be a number.</value>
      <webElementGuid>b0c53ce0-6b3d-4af5-acc0-f12db1ade930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownIdentificationType</value>
      <webElementGuid>721bcbe5-f365-4cb6-85e5-bd7eabce5260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Identification_Type_Id</value>
      <webElementGuid>2ea11c67-2dea-4443-b386-29d47f57e5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passport Document
RSA ID Document
</value>
      <webElementGuid>5ad6181d-ec96-45aa-a122-abab0a6f8568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownIdentificationType&quot;)</value>
      <webElementGuid>17f9e0ca-789a-48dd-bd49-764ac89da394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownIdentificationType']</value>
      <webElementGuid>5373d9c7-e83b-4b66-94b2-f1e640221ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[4]/div[2]/select</value>
      <webElementGuid>720f5131-cd86-4648-a757-a97c2b179b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification Type'])[1]/following::select[1]</value>
      <webElementGuid>374de0bf-37a4-4a9f-b262-e5debf17441c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Citizenship'])[1]/following::select[2]</value>
      <webElementGuid>12c87ea5-2c9b-4254-b538-95736fee36db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Number'])[1]/preceding::select[1]</value>
      <webElementGuid>d03f87d2-0394-4d77-b6c7-93cf0c5d9377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/preceding::select[1]</value>
      <webElementGuid>1f0b0c1c-2211-4a36-bea5-fc783ad5f97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>b0443e1f-beb8-4881-a133-2b8e1dbb2b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownIdentificationType' and @name = 'Person.Identification_Type_Id' and (text() = 'Passport Document
RSA ID Document
' or . = 'Passport Document
RSA ID Document
')]</value>
      <webElementGuid>1536d75e-80c6-40e8-aeb8-441cb64ff191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
