<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>34694913-7784-4a9b-9eba-9a22485d35c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resultLoading > div > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultLoading']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2aebf0a0-021d-4cfa-8413-57d6e26ca32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif</value>
      <webElementGuid>b59396bd-38e6-44c2-b27c-1341ea5232c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultLoading&quot;)/div[1]/img[1]</value>
      <webElementGuid>ef30c3e0-c65a-497e-bc43-af52a8b34ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultLoading']/div/img</value>
      <webElementGuid>7dbfe950-1047-4e1b-89a3-a4f6af8eaace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif')]</value>
      <webElementGuid>dbd51809-abe7-4eab-b448-ee1281429629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>3c5fb6fa-4518-4af1-bfe8-37ce3aeb640c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif']</value>
      <webElementGuid>c8176782-67ff-4b1b-8ce6-dce5883585d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
