<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReceptionRegister.Visit_Date</name>
   <tag></tag>
   <elementGuidId>1f7cd5bb-4f66-497c-aba1-04899972a1c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Visit_Date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Visit_Date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d401ef15-dd5e-42e2-9a82-45e742198862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>0bad2505-2f78-480e-bb3e-bbbb5f70de3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d2241a9-a9bb-4462-a11f-42292158b5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Visit Date must be a date.</value>
      <webElementGuid>3766725b-8b65-4409-8733-166e57ad4e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Visit_Date</value>
      <webElementGuid>0c0b442e-2de4-4347-b5a9-60bd57d18f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Visit_Date</value>
      <webElementGuid>91a01e50-bdb0-417e-92ad-a3788a2451d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>69e11115-0176-47e7-b684-9b0c6e53ff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05737e7d-393e-47ea-9442-badb0e82be66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3c1360e5-4d29-4794-b78c-74f7fc2ac860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Visit_Date&quot;)</value>
      <webElementGuid>00700d8c-3c88-46ad-aa6f-25813a47ca25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Visit_Date']</value>
      <webElementGuid>f51b335d-91a5-4201-9565-d191b37bbed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>d3176848-833b-4e5c-a1e0-80e4ebf83358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>59950001-75c8-49d9-ab87-34700b0900c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Visit_Date' and @name = 'ReceptionRegister.Visit_Date' and @type = 'text']</value>
      <webElementGuid>5c75b504-9075-483f-9ecd-3976b48dee22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
