<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_Person.Phone_Number</name>
   <tag></tag>
   <elementGuidId>af84caa4-e1ad-4f96-a289-128d89d18be3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Person_Phone_Number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Person_Phone_Number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bf58395-3f22-4d80-a62e-41ce563eabef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5d67f0a4-6288-41bb-88b5-501891f73c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Person_Phone_Number</value>
      <webElementGuid>88a355e7-fdf1-4ab3-8962-407a9444ceff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Phone_Number</value>
      <webElementGuid>cdc3732b-5064-46de-a4dc-b9559c1d503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97f3d61e-9125-4341-aafc-22eabcef91ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Person_Phone_Number&quot;)</value>
      <webElementGuid>ebd1dc9a-07d2-41bc-8fda-a775ec0a814d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Person_Phone_Number']</value>
      <webElementGuid>16e54e8b-68a6-48db-a328-79606fc453b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div/div[2]/input</value>
      <webElementGuid>a40e8927-44e1-44ae-a6b5-e16aa9fd263d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>5252042f-a0f4-4b5e-8b7d-a7075a0da5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Person_Phone_Number' and @name = 'Person.Phone_Number' and @type = 'text']</value>
      <webElementGuid>c4e0e263-b3a7-46c1-b201-be524ca9dd41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
