<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.First_Name</name>
   <tag></tag>
   <elementGuidId>d64fe02c-a945-4a5f-8e2d-01e8044f39a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FirstNameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FirstNameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80cfed36-43eb-4fa1-847d-79c3305bafcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1f5953b-ac14-4863-bced-fbb882179ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FirstNameText</value>
      <webElementGuid>2e4c6329-d0dd-4e0b-b985-3390a634b557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.First_Name</value>
      <webElementGuid>9bca472b-5a95-48f9-b055-171f22950b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ec55d008-6eb3-4b9d-a75b-56383acb0da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cdb461d-05b6-423b-a545-45f751ea14a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fd76a35-c783-4ca4-9406-40ff0b218a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FirstNameText&quot;)</value>
      <webElementGuid>c517d73b-38fa-4d51-8626-e0f9fb9009a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FirstNameText']</value>
      <webElementGuid>9d8cad97-eeb1-430d-b3f1-2f082b267eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>7a3553c7-5a1a-40cb-aa91-5b81eab9d165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>03664af5-f458-47ce-bcb4-1c3b4e0e4d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FirstNameText' and @name = 'Person.First_Name' and @type = 'text']</value>
      <webElementGuid>4e4c4223-d568-41b9-a2cb-3e41399b8d28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
