<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Date_Of_Birth</name>
   <tag></tag>
   <elementGuidId>e15ca534-049b-4b73-b86f-1c79f36977ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Date_of_Birth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Date_of_Birth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f80dd75b-e452-4414-889a-a97b3e97e814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>eeb40b88-67b2-4280-91f1-2666f5b0291d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7d2f41b-35f4-441c-b47f-3e262b28d72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date of Birth must be a date.</value>
      <webElementGuid>66417cff-5bfb-4e57-b1f1-724145d32189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_of_Birth</value>
      <webElementGuid>7e9dc7cc-80c7-4616-9665-ec23af916c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Date_Of_Birth</value>
      <webElementGuid>f11869b6-6521-489f-b2b8-d56953aff006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Click here to select Birth Date!</value>
      <webElementGuid>314f4ece-c0d4-4ae7-a40e-a0cc3eac3cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>8de94e50-285f-41ca-82f3-7650dcab4853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97beb344-ab96-4679-a0d4-594a7337addc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72fb1bd8-2c12-4feb-a1fe-884b910eed20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_of_Birth&quot;)</value>
      <webElementGuid>0aa8bd7d-9e4e-4524-bcb6-db9e591ce54a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Date_of_Birth']</value>
      <webElementGuid>45c553d7-df4f-4497-b701-3b2841e2c824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>58acf28b-05d9-44c9-bc43-9be9aea10e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>33b89bfc-52ca-43f8-a843-1d55aa335f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Date_of_Birth' and @name = 'Person.Date_Of_Birth' and @placeholder = 'Click here to select Birth Date!' and @type = 'text']</value>
      <webElementGuid>e64e9a53-553d-454d-9ff2-522da0f4f2ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
