<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReceptionRegister.Reason_For_Visit</name>
   <tag></tag>
   <elementGuidId>a930eac7-c224-484e-acb6-f5c98a1f1ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReceptionRegister_Reason_For_Visit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e91a6da-b308-4648-992c-742b9a690530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b71ff2e-4212-4505-b1fa-b8ae151e56eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReceptionRegister_Reason_For_Visit</value>
      <webElementGuid>3afb59f5-63cf-4e5b-86ca-6cfe5f65d99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reason_For_Visit</value>
      <webElementGuid>8f8521f4-180c-4895-aa0f-0a803c20e906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>de237f6b-0248-45ef-bdd6-3252e32ba54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2df8a92c-5df7-4969-b0c5-28773e63f1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b9697ee-590e-4974-a254-aa1b6a597dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReceptionRegister_Reason_For_Visit&quot;)</value>
      <webElementGuid>b4c08bb2-0143-4ac3-a7b7-c8a842751b29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      <webElementGuid>40897d6f-5002-407a-8595-a777ab217e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[2]/input</value>
      <webElementGuid>acb7ecc9-295d-4929-90be-b85e9fa95555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cc585b35-c88f-4c65-985f-9d8931f8bf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReceptionRegister_Reason_For_Visit' and @name = 'ReceptionRegister.Reason_For_Visit' and @type = 'text']</value>
      <webElementGuid>66ca0fe7-38a6-46e6-884b-1f681352c3f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
