<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -AfarAfrikaansAkanAm_65536a</name>
   <tag></tag>
   <elementGuidId>031842cd-a8aa-4d9b-88e5-c1d36cb3ea0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownLanguage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownLanguage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ac204446-e9d3-4335-a7d0-1d4859193895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>241c3f31-8378-4222-958e-dc09e9cd5f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4bb2aff7-32d7-4931-a92c-18067558b5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Language_Id must be a number.</value>
      <webElementGuid>8d143336-9ae5-4be7-9c7f-20b0c1bb69af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownLanguage</value>
      <webElementGuid>4b7783a9-7d6d-4558-9698-6c683073d331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Language_Id</value>
      <webElementGuid>2a725528-5429-4c71-b8f1-4cd8bfe9bc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Afar
Afrikaans
Akan
Amharic
Arabic
Berber
Bhojpuri
Cape Verdean Creole
Chewa
Comorian
Dangme
English
Fon
French
Fulani
Ga
German
Gikuyu
Hausa
Hindi
Igbo
Italian
Khoekhoe
Kimbundu
Kinyarwanda
Kirundi
Kituba
Kongo
Lingala
Luganda
Luo
Malagasy
Mauritian Creole
Mossi
Nambya
Ndau
Ndebele
Niger-Congo
Noon
Northern Ndebele
Northern Sotho
Norwegian
Oromo
Portuguese
Sena
Seychellois Creole
Shona
Somali
Southern Ndebele
Southern Sotho
Spanish
Swahili
Swazi
Tamil
Tigrinya
Tonga
Tshiluba
Tshivenda
Tsoa
Tsonga
Tswana
Twi
Umbundu
Venda
Wolof
Xhosa
Yoruba
Zulu
</value>
      <webElementGuid>73c21f45-edc6-4c4f-be05-0e6fae21dfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownLanguage&quot;)</value>
      <webElementGuid>39fd75b7-6722-459b-af5f-f4921a397809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownLanguage']</value>
      <webElementGuid>3c218f70-5e43-4561-9751-b51c9d924958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[7]/div[2]/select</value>
      <webElementGuid>be329197-6bf4-4d03-b36d-9bfa3c3f5a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Type'])[1]/following::select[1]</value>
      <webElementGuid>2c302b4b-f9b2-46cb-872d-3ae1cd97315a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::select[2]</value>
      <webElementGuid>3d79c380-7347-4ce7-a7bb-e8d7843e8e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sexual Orientation'])[1]/preceding::select[1]</value>
      <webElementGuid>a75e985e-a592-462d-989d-f18823a251c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Population Group'])[1]/preceding::select[2]</value>
      <webElementGuid>1bb730c4-6eb2-4358-a2ae-1bf7cc6f7d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/select</value>
      <webElementGuid>70005d62-bee8-4724-9094-9f8f06f78872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownLanguage' and @name = 'Person.Language_Id' and (text() = '- Please select -
Afar
Afrikaans
Akan
Amharic
Arabic
Berber
Bhojpuri
Cape Verdean Creole
Chewa
Comorian
Dangme
English
Fon
French
Fulani
Ga
German
Gikuyu
Hausa
Hindi
Igbo
Italian
Khoekhoe
Kimbundu
Kinyarwanda
Kirundi
Kituba
Kongo
Lingala
Luganda
Luo
Malagasy
Mauritian Creole
Mossi
Nambya
Ndau
Ndebele
Niger-Congo
Noon
Northern Ndebele
Northern Sotho
Norwegian
Oromo
Portuguese
Sena
Seychellois Creole
Shona
Somali
Southern Ndebele
Southern Sotho
Spanish
Swahili
Swazi
Tamil
Tigrinya
Tonga
Tshiluba
Tshivenda
Tsoa
Tsonga
Tswana
Twi
Umbundu
Venda
Wolof
Xhosa
Yoruba
Zulu
' or . = '- Please select -
Afar
Afrikaans
Akan
Amharic
Arabic
Berber
Bhojpuri
Cape Verdean Creole
Chewa
Comorian
Dangme
English
Fon
French
Fulani
Ga
German
Gikuyu
Hausa
Hindi
Igbo
Italian
Khoekhoe
Kimbundu
Kinyarwanda
Kirundi
Kituba
Kongo
Lingala
Luganda
Luo
Malagasy
Mauritian Creole
Mossi
Nambya
Ndau
Ndebele
Niger-Congo
Noon
Northern Ndebele
Northern Sotho
Norwegian
Oromo
Portuguese
Sena
Seychellois Creole
Shona
Somali
Southern Ndebele
Southern Sotho
Spanish
Swahili
Swazi
Tamil
Tigrinya
Tonga
Tshiluba
Tshivenda
Tsoa
Tsonga
Tswana
Twi
Umbundu
Venda
Wolof
Xhosa
Yoruba
Zulu
')]</value>
      <webElementGuid>8d3437ff-ef65-4c5d-a75d-18070ed384e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
