<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search Discovery_header_logo_icon</name>
   <tag></tag>
   <elementGuidId>0b80530b-1ab8-4c41-9e40-47fa3112f831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header_logo_icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header_logo_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8dad20d5-9667-427b-8c3c-f9953d1d4c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_logo_icon</value>
      <webElementGuid>129ec70b-92d9-408c-9102-e0d85b7b5216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://za.shein.com</value>
      <webElementGuid>a63a5df9-15ee-4e34-9baf-1963b39172f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconfont-critical icon-sheinlogo</value>
      <webElementGuid>bb20e0c5-d813-4a5a-9018-14e781404a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_logo_icon&quot;)</value>
      <webElementGuid>b945f798-466e-402d-96ee-69fbd31a102d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header_logo_icon']</value>
      <webElementGuid>c9649d11-0452-4378-b5e4-acb9abe65f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://za.shein.com')]</value>
      <webElementGuid>69340c74-7603-4d05-9db7-2bae75d1181a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>304c06dc-a7f4-46c1-8050-b45699bf38e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'header_logo_icon' and @href = 'https://za.shein.com']</value>
      <webElementGuid>ec7ac371-06fc-4efa-91a0-6d2949c5e562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
