<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Virgin Islands (U.S.)  1340_sui-input_33056b</name>
   <tag></tag>
   <elementGuidId>26ed37e7-4fd7-4ac9-b7af-6a19fb367bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sui-input__inner.sui-input__inner-suffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dc727d0-eb95-4a01-b5ae-568824150669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modelmodifiers</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f8b8ca3a-8484-4549-910f-5a95e2f7f0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sui-input__inner sui-input__inner-suffix</value>
      <webElementGuid>c250978b-4838-4b6a-b8ca-1be67963d89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56886a78-25e7-456f-bb34-e8669c0d61c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02c75372-6234-449a-bfd2-f8d824a7309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email Address:</value>
      <webElementGuid>8f844246-e707-4dce-89b3-d90d5afe16e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce87ceb2-bde4-4e67-97c9-b7182eb4a4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sui-popup-parent__hidden&quot;]/div[@class=&quot;j-login-page-0&quot;]/div[1]/div[@class=&quot;sui-dialog c-login new-login-dialog page__login-newDiaglog-container page__login_newUI-Popcontainer&quot;]/div[@class=&quot;sui-dialog__ctn sui-animation__dialog_W480&quot;]/div[@class=&quot;sui-dialog__wrapper sui-dialog__W480&quot;]/div[@class=&quot;sui-dialog__body&quot;]/div[1]/div[@class=&quot;page__login_newUI&quot;]/div[@class=&quot;page__login-newUI-continue&quot;]/div[@class=&quot;page__login_input-filed page__login-newUI-input&quot;]/div[@class=&quot;input_filed-text input_filedFocus&quot;]/div[@class=&quot;input_filed-wrapper&quot;]/div[@class=&quot;email-recommend-input&quot;]/div[@class=&quot;sui-input&quot;]/input[@class=&quot;sui-input__inner sui-input__inner-suffix&quot;]</value>
      <webElementGuid>1e504eba-aec4-4e0f-bfda-6f609cf7c764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='input']</value>
      <webElementGuid>8662257c-e0f2-4322-91f5-a4e4cbbbb635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>7ff4a893-b0b6-4152-8ebe-e247b461631e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input']</value>
      <webElementGuid>4730260c-7347-451d-8ab3-20cfda9681a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
