<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_sui-input__inner sui-input___b5b877</name>
   <tag></tag>
   <elementGuidId>faaf350c-40f8-43d4-881c-be344e73eecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='password'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aef62534-eaab-43a3-8f0b-ca59f81398ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sui-input__inner sui-input__inner-suffix</value>
      <webElementGuid>f06ef754-bba6-4508-9be3-1452b398f2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3a399ce7-4f1e-4794-b64d-00311a077c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>86f254ac-6b2f-4956-993e-a264a676cf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password:</value>
      <webElementGuid>55b1cd73-6c1a-42c8-9b5e-1cd6dc97002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>483c2737-6ecb-4629-8874-1b371f9011d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sui-popup-parent__hidden&quot;]/div[@class=&quot;j-login-page-0&quot;]/div[1]/div[@class=&quot;sui-dialog c-login new-login-dialog page__login-newDiaglog-container page__login_newUI-Popcontainer&quot;]/div[@class=&quot;sui-dialog__ctn sui-animation__dialog_W480&quot;]/div[@class=&quot;sui-dialog__wrapper sui-dialog__W480&quot;]/div[@class=&quot;sui-dialog__body&quot;]/div[1]/div[@class=&quot;page__login_newUI&quot;]/div[@class=&quot;page__login-newUI-emailPannel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;page__login_input-filed page__login-newUI-input&quot;]/div[@class=&quot;input_filed-text&quot;]/div[@class=&quot;sui-input&quot;]/input[@class=&quot;sui-input__inner sui-input__inner-suffix&quot;]</value>
      <webElementGuid>51e6f7de-7f34-46da-bb87-11e8ad6303ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='password'])[3]</value>
      <webElementGuid>34fd556b-4e33-4ad6-840c-5006063f52e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>1ec3d114-4ab7-4230-bced-c88e6a937ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>8591dc68-699e-43ff-bad6-b500bfce0231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
