<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -Walk-inIJS-HubTelep_93781e</name>
   <tag></tag>
   <elementGuidId>1dd8be20-68c7-450b-a59a-3d259ca9b7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reception_Visit_Type_Id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Reception_Visit_Type_Id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f70651a-9d5a-442f-b5db-a11c01598695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6441023-b5e0-46b1-b1d6-1ded9fe90dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b3668ce-1363-46d2-b4e4-22bb9b5b6778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Reception_Visit_Type_Id must be a number.</value>
      <webElementGuid>ba23fda5-be44-4580-a1a4-1e38ff589212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reception_Visit_Type_Id</value>
      <webElementGuid>7e00b924-516a-45f7-aacc-c482a55dd80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reception_Visit_Type_Id</value>
      <webElementGuid>012ee927-4e7e-4ab3-851a-f54d97ee9fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>34dd36d2-ab91-4e6c-8251-27c4b47e0119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>487e4420-8160-4784-8da2-5e8d721dbc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
</value>
      <webElementGuid>dd17cf1d-c04f-4230-a31f-123654bad7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reception_Visit_Type_Id&quot;)</value>
      <webElementGuid>f61a4f4e-0bc9-45b7-99c5-b337925b6681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Reception_Visit_Type_Id']</value>
      <webElementGuid>6ff3255a-ecb7-4ceb-b74c-7e4320f7bf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[4]/select</value>
      <webElementGuid>f231543b-7128-45fe-b76c-0663f7265e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>f2e0a6b3-06c6-4a62-a517-865c9ab3fbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type'])[1]/following::select[1]</value>
      <webElementGuid>7877f5cb-a1dd-4e8e-acfd-9bb93d1f92e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Date'])[1]/preceding::select[1]</value>
      <webElementGuid>29841bce-8a3e-446c-9644-0c04ff0daa80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>9b59c019-0454-4b4a-969e-198b7d4b9f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>41c8fba9-9cd0-4dcf-b95a-687306dc48c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Reception_Visit_Type_Id' and @name = 'ReceptionRegister.Reception_Visit_Type_Id' and (text() = '- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
' or . = '- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
')]</value>
      <webElementGuid>a6190f67-7bca-4bb5-a943-f7d8abbb8710</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
