<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.First_Name</name>
   <tag></tag>
   <elementGuidId>6e7d389a-3945-4cfa-b5cc-7b0aed378dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FirstNameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FirstNameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>669ccee4-7863-40d6-9677-edf9d59f47b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>184ceef6-6213-43bc-904e-81f08084d1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FirstNameText</value>
      <webElementGuid>9e9e8a55-c777-4903-9fc6-68414d7f7640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.First_Name</value>
      <webElementGuid>937e0c6e-dae3-43d4-ac86-3415c0fe634d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b0c9f64c-434b-4348-90f6-4bd48d09c7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2aec1d3d-bf7d-4ee1-a8c1-89542d8120fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>edbc92d7-fc5e-405b-8fbc-df3060ee4d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FirstNameText&quot;)</value>
      <webElementGuid>1067b7c2-1c60-48ef-b868-e5b5915d2337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FirstNameText']</value>
      <webElementGuid>59f2670c-652e-47ad-8828-415242bf2b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>063f471d-07c7-4dc8-8b58-0ccbc1d1f928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>36570d37-9116-402c-b285-27e32d27bd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FirstNameText' and @name = 'Person.First_Name' and @type = 'text']</value>
      <webElementGuid>6e75d666-a59c-4ee7-a325-e67e903e7bde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
