<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Line 1_PhysicalAddress.Address_Line_1</name>
   <tag></tag>
   <elementGuidId>cec45bc0-b766-47d5-8166-61c232481b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PhysicalAddress_Address_Line_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PhysicalAddress_Address_Line_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c832df4d-2956-4a2f-97aa-15dbcd367753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e89102f9-5b7e-49f7-8034-6760ac394e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhysicalAddress_Address_Line_1</value>
      <webElementGuid>307d5d45-7273-4fac-b435-1caaecfbab3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhysicalAddress.Address_Line_1</value>
      <webElementGuid>ef87add7-fb89-4ed9-824a-73c81262edd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc82db74-1fd0-498a-b624-7b0286aaa23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhysicalAddress_Address_Line_1&quot;)</value>
      <webElementGuid>5097f1c8-9136-4740-86e3-6e382054ef88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PhysicalAddress_Address_Line_1']</value>
      <webElementGuid>65437f05-c981-4c90-985f-e81b3290f20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[4]/div/div[2]/input</value>
      <webElementGuid>59973365-f862-4e99-adae-d3c2f14ebc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>bd313a2a-9924-4598-ae7f-e062c3015ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhysicalAddress_Address_Line_1' and @name = 'PhysicalAddress.Address_Line_1' and @type = 'text']</value>
      <webElementGuid>cd76a818-df62-4fee-ae17-6921bdaa6209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
