<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_Person.Phone_Number</name>
   <tag></tag>
   <elementGuidId>ddbf8c35-9a32-4b19-8f38-fe156d317454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Person_Phone_Number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Person_Phone_Number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>378bce06-8b82-4f09-ad0c-47a9fad4fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4cfacb7-8c94-4743-bc97-4a98f5d4ffaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Person_Phone_Number</value>
      <webElementGuid>8d6b540f-5628-46ec-93e0-23e1db4a349e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Phone_Number</value>
      <webElementGuid>fec2e830-8b74-4e06-8983-d26f74e5c6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2d6a61d-3b7e-4d7c-9bb4-76e6d3cec5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Person_Phone_Number&quot;)</value>
      <webElementGuid>1d11fe1b-a15e-4603-be74-3d5b9d0de2c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Person_Phone_Number']</value>
      <webElementGuid>2d4e226f-6864-4ff7-a8a7-462833415646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div/div[2]/input</value>
      <webElementGuid>5a04fb8a-280f-400b-9b85-631d59ee9602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>0eedca78-14a9-4343-a26d-df272144751a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Person_Phone_Number' and @name = 'Person.Phone_Number' and @type = 'text']</value>
      <webElementGuid>2db3cef5-dbb8-4813-9e57-0884a381fef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
