<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone Number_Person.Mobile_Pho_afea20</name>
   <tag></tag>
   <elementGuidId>ded200d8-60d0-41d5-b8a6-34af2a85d109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Person_Mobile_Phone_Number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Person_Mobile_Phone_Number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6295314-3ece-48cd-bd70-9aabaad3c269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>185e6733-7fe7-4ac5-870b-363b79ef4757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Person_Mobile_Phone_Number</value>
      <webElementGuid>6c32f100-6be1-408d-87c5-f3983a7e07a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Mobile_Phone_Number</value>
      <webElementGuid>60d9569d-6856-48c7-9602-bd4691e70bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82a9fc02-1230-447b-a001-bfc5e577aefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Person_Mobile_Phone_Number&quot;)</value>
      <webElementGuid>d0e61451-d5ba-4a84-a111-4d589fc60194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Person_Mobile_Phone_Number']</value>
      <webElementGuid>ec20b1c6-c206-4433-90cb-80d0c0729368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div/div[4]/input</value>
      <webElementGuid>5d93d291-aaa7-4993-a486-879d5a08d9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/input</value>
      <webElementGuid>30847c3d-2f21-4ad2-a7ef-53127154526e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Person_Mobile_Phone_Number' and @name = 'Person.Mobile_Phone_Number' and @type = 'text']</value>
      <webElementGuid>2c6d2290-19bb-4d66-a9f0-f20c7f979cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
