<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Attention Deficit Hyperactivity  Disorde</name>
   <tag></tag>
   <elementGuidId>fdc11a40-e7d1-4587-86dc-2bbfddb9be7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DropdownDisabilityTypes_chosen']/div/ul/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DropdownDisabilityTypes_chosen > div.chosen-drop > ul.chosen-results > li.result-selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1daf1756-5703-47fa-a41d-413624f57c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-selected</value>
      <webElementGuid>82aa1064-ae10-4660-9c18-af965bfcf304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d13320a4-006d-46f2-b4be-801baf855e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attention Deficit Hyperactivity  Disorde</value>
      <webElementGuid>086f7c7f-24ff-4fe2-a59e-8e7f9a36efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownDisabilityTypes_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;result-selected&quot;]</value>
      <webElementGuid>112b1946-9791-4fa3-a095-9b3c81a1adf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownDisabilityTypes_chosen']/div/ul/li[4]</value>
      <webElementGuid>96247f71-f490-4328-8886-956097772508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attention Deficit Disorder'])[2]/following::li[1]</value>
      <webElementGuid>a2c73cea-433c-4a2f-ad7b-c4556b36aae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asperger Syndrome'])[2]/following::li[2]</value>
      <webElementGuid>151edef7-c8c6-4522-b683-f4d9e181f884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autism'])[2]/preceding::li[1]</value>
      <webElementGuid>43eb96e3-16db-4cc0-8b3b-d48c8787944e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Person', &quot;'&quot;, 's Photo')])[1]/preceding::li[2]</value>
      <webElementGuid>0f2e9ade-5fac-4b7a-a1a6-d00647dc4c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[4]/div/div/ul/li[4]</value>
      <webElementGuid>b0667565-8724-4df2-bbd6-0d81810b8dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Attention Deficit Hyperactivity  Disorde' or . = 'Attention Deficit Hyperactivity  Disorde')]</value>
      <webElementGuid>03a5742e-74b0-4bdd-bcc7-115278915f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
