<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__IntakeAssessment.Case_Allocation__20112d</name>
   <tag></tag>
   <elementGuidId>ce636c70-c3ce-4c2e-9a09-b6d35aff05c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CaseAllocationCommentText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='CaseAllocationCommentText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>907b8ad7-85b4-4e3a-a45e-ce2b1d844135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f2f08d44-48ee-41ae-93ac-129f9fd80a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4788e184-043e-4674-a7bd-3083bbaa3cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CaseAllocationCommentText</value>
      <webElementGuid>94db7be9-f51d-4d68-8cdc-1657cac131a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IntakeAssessment.Case_Allocation_Comments</value>
      <webElementGuid>5ca4b0d7-8b2c-4dc7-8a23-e2d44f086cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7369d368-cde5-4ddf-b655-0b7ad9e3c665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>09f15b16-0c99-488e-8b08-bc93bf98d7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18d91fb0-6021-4a8c-acbf-3dadc09432f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CaseAllocationCommentText&quot;)</value>
      <webElementGuid>1eda3979-6b5b-4d55-910f-bcb4fc0680fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='CaseAllocationCommentText']</value>
      <webElementGuid>19b0baf4-9424-43de-bdd5-6d061404a816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CaseReferralSuper']/div[2]/div[2]/textarea</value>
      <webElementGuid>61507002-5db4-4fea-93bc-c714c6ceff51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>619d93a9-5e60-4883-b878-2ff5d326f3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'CaseAllocationCommentText' and @name = 'IntakeAssessment.Case_Allocation_Comments']</value>
      <webElementGuid>bc5e2380-9367-4fac-8e02-d460f7fce9b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
