<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_Search_Last_Name</name>
   <tag></tag>
   <elementGuidId>374913bc-90fc-43f6-8c12-267c21843cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Search_Last_Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Last_Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd12d69f-2a24-45fe-9877-b22f398df81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc1ee7e1-398f-4a4f-abad-952870337939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Last_Name</value>
      <webElementGuid>11210a8c-1295-45d7-a14e-2ec669528f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Last_Name</value>
      <webElementGuid>d0319369-e2a9-4d9d-8548-ef1dec7a930a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65608359-da7d-4abc-82e9-9b7387fc9ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Last_Name&quot;)</value>
      <webElementGuid>7fdd33e8-6772-46b6-b8b9-7bca64716c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Last_Name']</value>
      <webElementGuid>1ab2fb7c-7de3-44e1-a4ad-3f4715966324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[8]/input</value>
      <webElementGuid>5c4c907a-90ad-4bdf-b7b6-667514041396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>cc67f017-f33d-459d-a3c2-9dde63515b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Last_Name' and @name = 'Search_Last_Name' and @type = 'text']</value>
      <webElementGuid>a89aac2d-7fc5-4863-9e7b-00e53af82a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
