<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Second Fingerprint_ButtonSave</name>
   <tag></tag>
   <elementGuidId>d28e9893-4c37-4c69-a7c5-2825d69731ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ButtonSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ButtonSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29a29503-6f25-4a06-8a3e-a86c94761a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ec1dc6ac-79e2-47c5-8af7-5108c77e891c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ButtonSave</value>
      <webElementGuid>c1318e5e-a747-43a8-b0b0-864e304c92a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>bc5ea24a-8bcc-4622-baaa-293cb03b0cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>7c2dc237-0960-4fd8-8db3-13a0542e51c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ButtonSave&quot;)</value>
      <webElementGuid>28e4052a-78c9-4cd5-9347-4c27a6321359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ButtonSave']</value>
      <webElementGuid>5b4e634f-0041-42f8-8889-6c2157472cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='personDetailsForm']/div[2]/div[4]/input</value>
      <webElementGuid>97322133-2e2a-4e87-a27a-9e98a9c7a445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>45cf3390-19c3-4a62-be00-44edad9af87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'ButtonSave']</value>
      <webElementGuid>143e3cb8-fa60-458c-81da-5d302ffb4ca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
