<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -FemaleMale</name>
   <tag></tag>
   <elementGuidId>50bd5858-4b86-4856-88d2-61e6240315d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownGender</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownGender']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c59490f-4084-43ab-a17d-e4ac4cf9af06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d14fceb7-dbff-4dd4-aef7-accf645ab300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26b7c388-ef66-449e-81fc-0f9fdb7dfce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Gender_Id must be a number.</value>
      <webElementGuid>9e4c8579-c600-4e70-9f14-14243cc41e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownGender</value>
      <webElementGuid>f90e3414-1098-494b-93ab-31611d1400e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Gender_Id</value>
      <webElementGuid>76877dd3-ac2c-4ed4-8994-714108d89dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Female
Male
</value>
      <webElementGuid>3a1fe02b-3921-4317-8ef4-6f5a613523af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownGender&quot;)</value>
      <webElementGuid>981a442b-34a1-429f-8d3f-0e82765415cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownGender']</value>
      <webElementGuid>e9a0050e-9776-4adc-8a6d-4b03aca02348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[6]/div[2]/select</value>
      <webElementGuid>483ce91a-2ed3-4060-bb9d-adb9aed0100a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::select[1]</value>
      <webElementGuid>fd26492f-699e-4444-bf6b-61dc72b4d3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated'])[1]/following::select[1]</value>
      <webElementGuid>2b89ebde-950c-4cc3-a98a-855a87e37030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/preceding::select[1]</value>
      <webElementGuid>405bf4e7-2aa5-4598-88f6-7e7616248c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Type'])[1]/preceding::select[2]</value>
      <webElementGuid>801d0b54-cee8-47b4-a372-c5ad4db0cb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/select</value>
      <webElementGuid>73c89e31-3f2d-4a1b-96b7-509d3a703077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownGender' and @name = 'Person.Gender_Id' and (text() = '- Please select -
Female
Male
' or . = '- Please select -
Female
Male
')]</value>
      <webElementGuid>e6128240-b501-4381-9dc6-c998f58d9135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
