<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReceptionRegister.Reason_For_Visit</name>
   <tag></tag>
   <elementGuidId>d92b2c0f-2ee5-468b-8751-bf71c63d9219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReceptionRegister_Reason_For_Visit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5890aafa-b41e-4e79-81f2-b9dd254cf62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4055acd6-7b2a-4ea1-b186-c544d30b833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReceptionRegister_Reason_For_Visit</value>
      <webElementGuid>d4b8acf4-e2cf-445c-9f9c-2fc9cd18419a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reason_For_Visit</value>
      <webElementGuid>a07617fd-fa3b-4e63-96cc-04770594680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>71d60096-c0e7-4f15-8c6a-3dbdbd235600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d5d9e0f-af47-45f0-a007-07dbcc2130c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddeb5fc7-3ea8-4767-8606-8267852438ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReceptionRegister_Reason_For_Visit&quot;)</value>
      <webElementGuid>7874e9b2-ffdc-4bb9-b2cd-0e1c67905056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      <webElementGuid>8b417cee-daf9-4ceb-8e2b-ca3eb7e6eb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[2]/input</value>
      <webElementGuid>11474de1-967e-4f04-9b2d-48c30659eb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>08de569e-85a8-44e1-a436-f393b5b0204c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReceptionRegister_Reason_For_Visit' and @name = 'ReceptionRegister.Reason_For_Visit' and @type = 'text']</value>
      <webElementGuid>714eb173-6fd1-4cfc-8c77-6195ca573d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
