<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Known As_Person.Known_As</name>
   <tag></tag>
   <elementGuidId>2c7f9623-e54d-4022-ab6a-7b2be1b22089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Person_Known_As</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Person_Known_As']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc342e9a-4d7d-4dc7-9f01-0e4d6ee91c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>00721cb9-6693-4cd0-a641-de37f2d42e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Person_Known_As</value>
      <webElementGuid>6a4106b3-f5b7-4f4b-8d26-a8fb5d282e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Known_As</value>
      <webElementGuid>9f75c90a-a9c7-429a-9858-6a373314f21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa2a1ca1-0a11-4e65-bc9b-4cba09e70b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Person_Known_As&quot;)</value>
      <webElementGuid>ce40fa32-07a4-4e1d-8644-961e916570ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Person_Known_As']</value>
      <webElementGuid>15eb2275-e18c-4088-b9e5-99ed350b4347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>f2969dfc-24eb-4d82-9764-fb8faa62590d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>24caca19-0a01-4375-b819-df19d2df4621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Person_Known_As' and @name = 'Person.Known_As' and @type = 'text']</value>
      <webElementGuid>ffdc3ef9-91ff-498c-9e5a-8f45a54b107a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
