<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.First_Name</name>
   <tag></tag>
   <elementGuidId>4ee8f2a7-f21a-4010-a06b-032f4b8538c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FirstNameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FirstNameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4fe8d2f-07b1-4841-ad47-1c24d931fa8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd0e3b07-3aae-43cc-b3a0-69f0aabb9bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FirstNameText</value>
      <webElementGuid>9f0ca328-f3bd-457e-bdb5-42b84ac69602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.First_Name</value>
      <webElementGuid>a47b128b-cb2e-4fd1-98bc-1fd5ff0c2829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>994486c4-d21e-4804-b7e0-5388208b1bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53005858-1e8d-499a-9cc1-d97546f23e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>063143a8-feb8-4f06-ad47-a44dea61e303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FirstNameText&quot;)</value>
      <webElementGuid>2ce5c7e2-1f3f-4c7e-91c7-569cd6c0875d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FirstNameText']</value>
      <webElementGuid>faabc513-e189-4b17-b945-056bbc4bffa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>f6964405-ac71-4975-8944-8803db7a396d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>c841a946-b98a-4965-b321-0e67e92c12a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FirstNameText' and @name = 'Person.First_Name' and @type = 'text']</value>
      <webElementGuid>7099ebcb-27be-43f2-8a24-579b35520bbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
