<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_Person.Identification_Number</name>
   <tag></tag>
   <elementGuidId>53915c37-ddc7-43ac-ae7b-880cc67e219a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Identification_Number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identification_Number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d131a10-fafc-4628-89ad-11ea7b2afa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a05e1b75-7cb6-4ffc-8cc2-2534f118e674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identification_Number</value>
      <webElementGuid>7961d77b-08da-4224-be30-e3258e15a646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Identification_Number</value>
      <webElementGuid>210088aa-fca0-43a6-94c8-344016723c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>299c49f9-bde2-43cf-ac36-a1c7713e0e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identification_Number&quot;)</value>
      <webElementGuid>43724dcf-f3d5-428b-aec4-b3c74f69daa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identification_Number']</value>
      <webElementGuid>98bb3358-a76d-4df9-ab71-1b3a918598f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[4]/div[4]/input</value>
      <webElementGuid>6ad81bbc-b520-42dc-b3e5-112edc9e826a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>e9df750e-59be-402d-9177-6e91d2cc96dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identification_Number' and @name = 'Person.Identification_Number' and @type = 'text']</value>
      <webElementGuid>b097663e-0a98-4fa7-9280-548846378eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
