<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label__input-group-addon btn</name>
   <tag></tag>
   <elementGuidId>f6ad5796-20c7-492d-ac3c-581d47a8e0ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.LeftSide > div.row > div.col-md-3.form-group > div.input-group > label.input-group-addon.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1']/div/div/div/div[5]/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f55d21ab-1cde-4b76-b1ec-6eea795e2083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Date_of_Birth</value>
      <webElementGuid>10ed5ec5-5f49-4541-bc61-2912b9b0e189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-addon btn</value>
      <webElementGuid>7cac6a5f-287e-42e7-b716-1d06b3d55ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;column_1&quot;]/div[@class=&quot;LeftSide&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 form-group&quot;]/div[@class=&quot;input-group&quot;]/label[@class=&quot;input-group-addon btn&quot;]</value>
      <webElementGuid>d651f032-5d49-4d5e-81ae-80c4a58c69f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[5]/div[2]/div/label</value>
      <webElementGuid>4b9a4b25-fea4-46cb-b5ad-fca1542797c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::label[1]</value>
      <webElementGuid>01f69601-63a9-48ba-bf27-e66f454973c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::label[1]</value>
      <webElementGuid>c0faed60-648e-49de-8c40-652f852cf65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::label[1]</value>
      <webElementGuid>dd56ddb6-ab14-4703-a185-0afe364466aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::label[2]</value>
      <webElementGuid>e226f3b0-c554-4ba6-ad6c-0546f37187e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/label</value>
      <webElementGuid>8a917eb0-5b7c-47c1-b396-9b9f92c438c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
