<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Chronic Illness</name>
   <tag></tag>
   <elementGuidId>b0d7fc8d-bfe2-4dd2-9f22-7232aab8977d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.result-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DropdownDisabilityCategory_chosen']/div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ebb0af8d-a4ab-49d8-8153-d19b05668986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-selected</value>
      <webElementGuid>0dedfc97-65f3-4bdc-8d22-199696c52abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>eb8005ad-9e3d-4141-b0db-c11daa4f43d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chronic Illness</value>
      <webElementGuid>275b866b-0a20-420d-83b8-6a1136ac3d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownDisabilityCategory_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;result-selected&quot;]</value>
      <webElementGuid>d89b5272-14a8-42af-a181-3ee95e8aa00d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownDisabilityCategory_chosen']/div/ul/li[3]</value>
      <webElementGuid>6da0a676-649f-47f5-9e4e-01c830046f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blind/Visual Impairment'])[2]/following::li[1]</value>
      <webElementGuid>a0e48426-df91-43b3-8886-620a40aead97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Please select -'])[12]/following::li[2]</value>
      <webElementGuid>9429d3ca-0023-404b-875b-b71ec282eabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Developmental Disability'])[2]/preceding::li[1]</value>
      <webElementGuid>b8488ed3-b52e-40dd-8515-bd6324f9f655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hearing Impairment'])[2]/preceding::li[2]</value>
      <webElementGuid>616f14aa-8793-472a-87a5-7f09e7038907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[3]</value>
      <webElementGuid>04748881-0d77-4e14-968b-c7bb30065ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Chronic Illness' or . = 'Chronic Illness')]</value>
      <webElementGuid>e1fb2c05-4400-4608-9bc9-8e5100cbb385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
