<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -AetheistAfrican rel_031447</name>
   <tag></tag>
   <elementGuidId>55bd1853-ed8b-42f6-ace4-2e2f4ec06347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownReligion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownReligion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5cff0887-65fc-4f5a-bdd2-0bb0efcdd301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5e2c1d73-e944-4b44-9b2b-2328364b028a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02d5a49d-83fe-4388-aaa9-3074d4f06e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Religion_Id must be a number.</value>
      <webElementGuid>88b91d2c-8c95-4e43-8a05-a62a095ed0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownReligion</value>
      <webElementGuid>6678c999-5dca-4417-b224-4277072f4a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Religion_Id</value>
      <webElementGuid>4f01773b-0e53-4485-82ce-82f3170edc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Aetheist
African religion
Agnostic
Buddhism

Christian
Hindu
Islam
Jewish
Postol
Rastafarian
Traditional
</value>
      <webElementGuid>9deb0264-304d-482b-9bdd-967bbc18a30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownReligion&quot;)</value>
      <webElementGuid>92075e18-db7c-497e-86c1-6227e544a5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownReligion']</value>
      <webElementGuid>20985c0a-eb4d-495f-9d12-da219af5c027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[9]/div[2]/select</value>
      <webElementGuid>181aca66-4fcf-4e51-a94e-d45635db17c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Religion'])[1]/following::select[1]</value>
      <webElementGuid>4c95741b-f4ec-4255-9628-d20492f414d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/following::select[2]</value>
      <webElementGuid>c47a18b6-cf18-4997-a3c1-c904284f9531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>24c031e8-0fab-464f-af9c-d243a4cbbfcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/select</value>
      <webElementGuid>7d2263a7-dd29-495b-bd5f-fee41f7a644c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownReligion' and @name = 'Person.Religion_Id' and (text() = '- Please select -
Aetheist
African religion
Agnostic
Buddhism

Christian
Hindu
Islam
Jewish
Postol
Rastafarian
Traditional
' or . = '- Please select -
Aetheist
African religion
Agnostic
Buddhism

Christian
Hindu
Islam
Jewish
Postol
Rastafarian
Traditional
')]</value>
      <webElementGuid>411f5052-6393-44fb-b453-a1ed2a7348c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
