<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname___field_908</name>
   <tag></tag>
   <elementGuidId>06b805ae-c212-436e-bf1e-b25107e53381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7782e61b-aaa0-4e44-892f-f7357c755696</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='7782e61b-aaa0-4e44-892f-f7357c755696']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf1dca15-38b0-436b-a400-a057ac90ecb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_908</value>
      <webElementGuid>a80a513e-850d-4657-913a-a7dcaf9bc5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7782e61b-aaa0-4e44-892f-f7357c755696</value>
      <webElementGuid>490adb0f-7217-444f-87e7-abf6682ec61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d658847-534d-4ac8-8ee9-35c1445adcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8fdf7df4-9301-4dac-9eb4-20592dd86579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7782e61b-aaa0-4e44-892f-f7357c755696&quot;)</value>
      <webElementGuid>9d67e57f-8312-4bba-a433-78496703c7be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7782e61b-aaa0-4e44-892f-f7357c755696']</value>
      <webElementGuid>d71d4ec1-2e36-4538-b0f5-199319f72de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__field_']/div[3]/div/input</value>
      <webElementGuid>49609c9f-5661-494e-958c-db81dbf51eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3a76797f-9154-417e-889b-fc71977b992a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_908' and @id = '7782e61b-aaa0-4e44-892f-f7357c755696' and @type = 'text']</value>
      <webElementGuid>0fabd7db-d0d0-4f2a-9b4d-766db84a9efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
