<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID  Passport number___field_912</name>
   <tag></tag>
   <elementGuidId>cd576202-6d66-444f-91cb-299b7c5c1b44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5d0bce3e-0759-4768-8e0a-5e45bdf6a4ce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='5d0bce3e-0759-4768-8e0a-5e45bdf6a4ce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d91096e8-ba7a-4449-82cb-2d1b1f5902c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_912</value>
      <webElementGuid>ca4d4713-18b1-4e5c-abc0-40a330440b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5d0bce3e-0759-4768-8e0a-5e45bdf6a4ce</value>
      <webElementGuid>0c9275ee-fe82-44f1-870d-dec9fa85c328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06ca0f4f-49ce-447e-9c19-4911a6eeed9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56fcd8d3-4a7e-4dfa-b22d-5623c227782b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5d0bce3e-0759-4768-8e0a-5e45bdf6a4ce&quot;)</value>
      <webElementGuid>ced17171-44af-48b0-8610-adf1247c00d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='5d0bce3e-0759-4768-8e0a-5e45bdf6a4ce']</value>
      <webElementGuid>d8ce93a2-d049-4ba5-ac6a-63e388d8db61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__field_']/div[4]/div/input</value>
      <webElementGuid>44292ec5-6539-423c-85f9-83b9f1d83eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>339f3c75-25bd-427f-ba9e-00085f851afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_912' and @id = '5d0bce3e-0759-4768-8e0a-5e45bdf6a4ce' and @type = 'text']</value>
      <webElementGuid>fbdd6960-20b5-4c35-9b8d-e17dd75fe479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
