<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please upload your bank state.ment</name>
   <tag></tag>
   <elementGuidId>380f289c-5498-427c-bd2e-f8be37d01bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__field_959_desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__field_959_desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ce673a3-286d-48be-bcec-db62cad50f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Form__Element__ValidationError</value>
      <webElementGuid>5af8cdd6-9a02-47f9-a8dc-83d1a69f80eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-f-linked-name</name>
      <type>Main</type>
      <value>__field_959</value>
      <webElementGuid>8bb7e352-6961-4d2a-becb-4b2873b441be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__field_959_desc</value>
      <webElementGuid>10b40581-9ed2-45b5-8bfc-0de1355d0fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please upload your bank state.ment.</value>
      <webElementGuid>bcafc917-8023-40ce-b4bb-316c3635b038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__field_959_desc&quot;)</value>
      <webElementGuid>dba79ff7-ed20-4d43-8cfe-63967fc37910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__field_959_desc']</value>
      <webElementGuid>106ec071-ec35-4db0-98a9-d15080597f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__field_']/div[7]/div/div/span[3]</value>
      <webElementGuid>771bc6c8-c491-488f-bddf-35dcd91c4dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload your bank statement'])[2]/following::span[2]</value>
      <webElementGuid>85eef91d-81b5-4624-9d70-af6f466b6bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What time should we call you?'])[1]/preceding::span[1]</value>
      <webElementGuid>72deadc2-a1cc-4b9d-b31a-b1b296afeb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferred time (Weekdays only)'])[1]/preceding::span[1]</value>
      <webElementGuid>36186dd7-f293-4243-8916-374206134f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please upload your bank state.ment.']/parent::*</value>
      <webElementGuid>7960ca2c-8454-4fa9-b961-a8e1cb25b919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/span[3]</value>
      <webElementGuid>34d3a5e4-fb0e-4ca0-b235-4db69b25759c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__field_959_desc' and (text() = 'Please upload your bank state.ment.' or . = 'Please upload your bank state.ment.')]</value>
      <webElementGuid>9ca5941a-3d3e-4672-8f52-2b4d4f3e1d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
