<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>f8d43ecf-12ab-484d-b711-fb8125532cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='personDetailsForm']/div[2]/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1cdcbb6-dbc8-4997-b50f-72d70597b9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>83399e85-0537-4312-8618-52a244fee8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SDICMS_TEST/Intake</value>
      <webElementGuid>a1dc8369-9d45-47e2-a633-10ce6b6587c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>14c59768-b195-422b-9e73-da92e9f8f7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personDetailsForm&quot;)/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-footer&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>f3477ee3-d41d-4d55-820a-f6c008beb88f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='personDetailsForm']/div[2]/div[4]/a</value>
      <webElementGuid>ab5086f7-69e1-4dc5-a888-21b6de4e6003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>2fe5dc8e-f72d-4f90-b64c-1f6f43e6bdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second Fingerprint'])[1]/following::a[5]</value>
      <webElementGuid>6c72e60b-bf2c-4d7e-82db-208ea904aae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Fingerprint'])[1]/following::a[5]</value>
      <webElementGuid>f2fe28a1-669c-4c07-b7f6-5090849d451d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/preceding::a[1]</value>
      <webElementGuid>ad7062e8-2c26-4015-90c7-ecb3138d298b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/preceding::a[2]</value>
      <webElementGuid>ba045778-ce24-485d-a04d-16e134089ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>6b388d44-9c9f-47fa-b884-2371b65bbe6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SDICMS_TEST/Intake')]</value>
      <webElementGuid>04422100-439f-46a0-a018-411a52eb8565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>1ea43024-45dd-4e4a-954b-ca7558e91b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SDICMS_TEST/Intake' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>6cfb7371-0b81-41cd-b710-e863a72d8642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
