<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loading data. please wait_bg</name>
   <tag></tag>
   <elementGuidId>4a26e172-5241-4a62-8c2f-5639a6e2f632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultLoading']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e332f53c-1f7a-4f3b-92e7-d67307900498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg</value>
      <webElementGuid>6fe7ad35-a0ea-4396-9a8a-4116aecc8a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultLoading&quot;)/div[@class=&quot;bg&quot;]</value>
      <webElementGuid>58a1b1ad-d4f9-44a8-a637-f0c347ab719c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultLoading']/div[2]</value>
      <webElementGuid>02385ad9-e318-4cd9-b53f-3aa5486f09e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]</value>
      <webElementGuid>b3e7e6ae-8ff1-4164-97be-8a2e26edd881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
