<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -BisexualGayHetero S_d0c270</name>
   <tag></tag>
   <elementGuidId>5d4db02e-6e42-42c3-96dd-85bc3361e8b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownSexualOrientation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownSexualOrientation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5b52a5a5-a993-4eb7-99b3-c971053f87eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8733ca25-756e-4baf-acdc-61178e143a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eec4faa7-1cdb-46e9-b275-ff84040c5f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Sexual_Orientation_Id must be a number.</value>
      <webElementGuid>c8a83573-e4b1-4cd5-bb9f-7da67986bbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownSexualOrientation</value>
      <webElementGuid>26e7be4b-a773-4c3e-9588-f7aa44a6842f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Sexual_Orientation_Id</value>
      <webElementGuid>32f70833-bb23-4446-927d-e7c6bd1f6edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Bisexual
Gay
Hetero Sexual
Intersex
LBGTIQA+
Lesbian
Queer
Transgender
</value>
      <webElementGuid>fb44a40d-3400-47a8-a3e5-12c6a8575e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownSexualOrientation&quot;)</value>
      <webElementGuid>f496954e-3d87-4043-8a66-589cec974faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownSexualOrientation']</value>
      <webElementGuid>0fb84568-d830-4e51-8dca-c039e627f3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[7]/div[4]/select</value>
      <webElementGuid>637e634d-9cba-40fe-9eb7-8a7b85294b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sexual Orientation'])[1]/following::select[1]</value>
      <webElementGuid>249a1180-09ff-4a89-836f-6807b5e58863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Type'])[1]/following::select[2]</value>
      <webElementGuid>3c0a1252-743a-4fd3-ac4d-7e9d1cf67dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Population Group'])[1]/preceding::select[1]</value>
      <webElementGuid>58fa9719-9579-4c53-9505-ea93c3c05d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/preceding::select[2]</value>
      <webElementGuid>f4c9ac70-62ad-4e9c-8e45-f23677e87012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[4]/select</value>
      <webElementGuid>3669950c-64a4-474f-b4b5-6137a3550126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownSexualOrientation' and @name = 'Person.Sexual_Orientation_Id' and (text() = '- Please select -
Bisexual
Gay
Hetero Sexual
Intersex
LBGTIQA+
Lesbian
Queer
Transgender
' or . = '- Please select -
Bisexual
Gay
Hetero Sexual
Intersex
LBGTIQA+
Lesbian
Queer
Transgender
')]</value>
      <webElementGuid>bcae6498-b71d-4aaf-8b2a-4a36c5664c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
