<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -Walk-inIJS-HubTelep_93781e</name>
   <tag></tag>
   <elementGuidId>91f13964-450a-4811-947b-fbae38b5a964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reception_Visit_Type_Id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Reception_Visit_Type_Id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>03a686cc-59e9-418a-83ef-1e8759735585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c43926ea-b8e3-4e9b-9d41-31fdfd89b813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3f3020d-7ac8-425e-b2b4-d7606c680987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Reception_Visit_Type_Id must be a number.</value>
      <webElementGuid>78754f95-8931-4c74-a0ae-f25706981def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reception_Visit_Type_Id</value>
      <webElementGuid>f46e7305-9efd-4001-88d0-8d927e20d947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reception_Visit_Type_Id</value>
      <webElementGuid>7a87356b-eb12-4a60-bf30-d984b87dda3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ee6b7bc2-c890-442e-b95a-404086877170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e7383392-85f4-4d82-b00a-3aefe45d62bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
</value>
      <webElementGuid>79bc8086-d7c8-464a-aa2f-a37150f530b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reception_Visit_Type_Id&quot;)</value>
      <webElementGuid>a5a2b97c-7333-4311-a7e5-a2e3b62473ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Reception_Visit_Type_Id']</value>
      <webElementGuid>d4be7ab1-2080-4d9c-97cd-95a99edae4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[4]/select</value>
      <webElementGuid>da624e8d-6fd8-4a2c-a917-9149489311fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>e047c823-5f65-488a-a8ac-2c47bd947fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type'])[1]/following::select[1]</value>
      <webElementGuid>e9296cd6-cc06-4421-adcc-b42e80215411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Date'])[1]/preceding::select[1]</value>
      <webElementGuid>dc7a8542-3e0d-4325-bd71-bfec0046ce06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>d16b552b-7717-4d31-9934-b473ab0cc4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>30206ada-35c1-433e-8931-afaeae47dd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Reception_Visit_Type_Id' and @name = 'ReceptionRegister.Reception_Visit_Type_Id' and (text() = '- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
' or . = '- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
')]</value>
      <webElementGuid>eeb11e1d-bcbc-4240-a2f8-1cc49b2f0ec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
