<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_Person.Identification_Number</name>
   <tag></tag>
   <elementGuidId>3980b6a2-a417-4c64-81c6-01c28b20fe34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Identification_Number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identification_Number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2282eca-f049-47f3-b00a-265cb42a5205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bb46e605-5896-45ae-a49d-0e0f4512b439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identification_Number</value>
      <webElementGuid>992f71d1-7f8b-4268-810b-c71e3e7cb0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Identification_Number</value>
      <webElementGuid>44708d40-3d43-41cc-9d77-86a23db30d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c21e8d7-8939-47be-9adb-c2b8c795eae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identification_Number&quot;)</value>
      <webElementGuid>c4ec170a-bd9a-4ef2-a5cf-a9809f6025c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identification_Number']</value>
      <webElementGuid>32b9b010-c248-4ab7-b900-bcf514765df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[4]/div[4]/input</value>
      <webElementGuid>6f867d85-dbc2-429c-b71e-eee948e8fdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>3e13c673-9c28-4d66-9ac7-ccd42598fabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identification_Number' and @name = 'Person.Identification_Number' and @type = 'text']</value>
      <webElementGuid>ef6fa9c2-7648-4e2d-b8a7-07a5c7b72989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
