<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign in</name>
   <tag></tag>
   <elementGuidId>8530bd88-bf8d-4364-8e01-a3ffa3ea2fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-container']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._yb_13wu2._yb_11eva.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2302b7dc-096d-46cb-9fc1-d4076dca2c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_yb_13wu2  _yb_11eva undefined</value>
      <webElementGuid>0bedccbc-8af1-41e4-a799-6536d23c3fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>sec:ybar;slk:sign-in;elm:signin;subsec:settings;itc:0;tar:login.yahoo.com</value>
      <webElementGuid>785a0a6f-e3a7-475b-a69e-690ead1c2562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-redirect-params</name>
      <type>Main</type>
      <value>pspid=[[pspid]]&amp;activity=ybar-signin</value>
      <webElementGuid>e65e2d76-1bf0-4c17-a018-ab4cdfe2839b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://login.yahoo.com/?.lang=en-US&amp;src=homepage&amp;.done=https%3A%2F%2Fwww.yahoo.com%2F&amp;pspid=2023538075&amp;activity=ybar-signin</value>
      <webElementGuid>4eb19cdc-96f9-48aa-ab63-b8013ba6caeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>166</value>
      <webElementGuid>6f7d1213-6c23-4627-a318-d1a8a3754517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v9y</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>61505951-6ff9-411d-83a1-7f341976a53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>4e602c14-d91d-4f22-a7ae-c8d884427b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-container&quot;)/a[@class=&quot;_yb_13wu2  _yb_11eva undefined&quot;]</value>
      <webElementGuid>fe24c56b-f970-4e88-9f7f-019f5a97b7f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-container']/a</value>
      <webElementGuid>b73e9c7b-2085-404a-86be-3c19516ed17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign in')]</value>
      <webElementGuid>d7a8b409-c819-445a-a8c4-f85492d7b40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mail'])[1]/following::a[1]</value>
      <webElementGuid>b1813d44-d26d-4924-9a85-08bde61942e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[12]/following::a[2]</value>
      <webElementGuid>9f6ed96a-1880-4887-80be-15bc557bae35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mail'])[2]/preceding::a[1]</value>
      <webElementGuid>75ebbca8-2fed-4187-bede-334088ea1bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[6]/preceding::a[2]</value>
      <webElementGuid>4fd4e4c6-289b-4465-8725-8d434a9355b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in']/parent::*</value>
      <webElementGuid>a47628df-acb4-45a6-ae31-c2e8a477f409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://login.yahoo.com/?.lang=en-US&amp;src=homepage&amp;.done=https%3A%2F%2Fwww.yahoo.com%2F&amp;pspid=2023538075&amp;activity=ybar-signin')]</value>
      <webElementGuid>54cd6cf6-d4ea-4ff7-ba89-cdd4ff7cf110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>dff19733-ec9f-4b96-bbe2-22d672fb12c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://login.yahoo.com/?.lang=en-US&amp;src=homepage&amp;.done=https%3A%2F%2Fwww.yahoo.com%2F&amp;pspid=2023538075&amp;activity=ybar-signin' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>0b20354b-aa7e-4217-a8b7-87fc9e1e08fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
