<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6341ef53-4484-4dbd-86c8-b5350152b1f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultLoading']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#resultLoading > div > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ee14291d-c1ca-405a-8b87-ebd618bb855a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif</value>
      <webElementGuid>4a10d547-0f36-4b8d-a1ba-d5238e29afd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultLoading&quot;)/div[1]/img[1]</value>
      <webElementGuid>d3fd3346-d8bc-4f2d-b85c-8c3803af1745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultLoading']/div/img</value>
      <webElementGuid>199fc2a4-b58e-44bf-b7e6-8e5d2aa152e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif')]</value>
      <webElementGuid>b338a3a1-3961-4d71-8b18-b58d60aae713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>5e25fa59-db92-4b52-99bf-20995b9c2c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif']</value>
      <webElementGuid>944490de-15b3-49e1-bc65-fc8118b752ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
