<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReceptionRegister.Reason_For_Visit</name>
   <tag></tag>
   <elementGuidId>2106799b-407c-4a09-965e-4d4cd4752a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReceptionRegister_Reason_For_Visit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27ee4252-893d-4b6f-bf5d-12e6a6584549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>138855be-e2ec-478b-89c5-c372d2e6fc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReceptionRegister_Reason_For_Visit</value>
      <webElementGuid>357c0910-e49e-43b5-a133-73486cc33b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reason_For_Visit</value>
      <webElementGuid>d7d784b3-e80c-43a7-83f8-8ac962455ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c69e87e6-0f31-4bd0-b75f-4617d49d8253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e617e9f0-73f2-4d2b-ac37-f8a2c46ca643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c6859f7d-a9a7-41c8-bb02-d5d2b86d8c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReceptionRegister_Reason_For_Visit&quot;)</value>
      <webElementGuid>90f05d4b-2633-4667-bf78-31e83d24a525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      <webElementGuid>d31a7fca-3d07-474d-9047-48a9cec23e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[2]/input</value>
      <webElementGuid>c50fe051-7f41-48f5-a0f3-e4d791ff342f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b4e759b8-832b-4a7e-a0fc-820c1dcd96fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReceptionRegister_Reason_For_Visit' and @name = 'ReceptionRegister.Reason_For_Visit' and @type = 'text']</value>
      <webElementGuid>61d23b52-0baa-4319-9194-456ce63eeae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
