<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_Person.Identification_Number</name>
   <tag></tag>
   <elementGuidId>aec1ff09-5495-4b13-946d-cd49b6626033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identification_Number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Identification_Number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a20b038b-8aac-4259-a5ef-4bccdb7614a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>56de5baf-478d-4b32-a18b-e5067a7e111b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identification_Number</value>
      <webElementGuid>e1a86b42-53da-4b00-9250-e22c9f00a3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Identification_Number</value>
      <webElementGuid>5649be93-65b6-430f-83ef-09dbf705355e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32f966f3-5826-4187-9386-50cc14936c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identification_Number&quot;)</value>
      <webElementGuid>b1a5cc38-74ff-4c70-9801-e4a5a67aa38c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identification_Number']</value>
      <webElementGuid>c1bbb69e-d6b1-4a16-ba8a-74671f3170ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[4]/div[4]/input</value>
      <webElementGuid>fc8d2352-27c8-4295-ac4f-c94e173f5c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>0a4dac25-a42b-4ec8-b87c-00617ccb0636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identification_Number' and @name = 'Person.Identification_Number' and @type = 'text']</value>
      <webElementGuid>cb21c40e-ec71-4f3a-90ce-297f9ffd87e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
