<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -Walk-inIJS-HubTelep_93781e</name>
   <tag></tag>
   <elementGuidId>39a99aeb-a56c-4b9c-9bd9-23e5bc18c6c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Reception_Visit_Type_Id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Reception_Visit_Type_Id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b668adae-2758-43bd-95ec-77f2d64d6b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>80f87518-1ba1-4252-be10-b55cce2619df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48cdce1d-fdd1-455f-b7ad-91db4c922bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Reception_Visit_Type_Id must be a number.</value>
      <webElementGuid>b6d74574-e740-4a52-8f2a-b63c14e32c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reception_Visit_Type_Id</value>
      <webElementGuid>54522460-1227-4d3b-871c-4f73b52cc78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reception_Visit_Type_Id</value>
      <webElementGuid>aed5ba38-9964-471a-a7a4-3da0314b9cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>18202201-bd11-4c6e-a498-eb1ae0ff148b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1724d685-7354-4b4b-a73b-1f272c01f26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
</value>
      <webElementGuid>15f29595-67f7-49dd-87eb-882d7aa9e270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reception_Visit_Type_Id&quot;)</value>
      <webElementGuid>eee76793-193f-47f1-a6ad-bd79ac55ca0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Reception_Visit_Type_Id']</value>
      <webElementGuid>b17674cd-f98e-496d-b606-fa2564268ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[4]/select</value>
      <webElementGuid>afe07967-195f-43bc-a2e9-c1792628e486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>a8563f8a-4200-4674-a639-497a0bd1acb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type'])[1]/following::select[1]</value>
      <webElementGuid>d3df3873-527b-4bc9-af7b-6c9ac44cf634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Date'])[1]/preceding::select[1]</value>
      <webElementGuid>0098a3b2-1fbf-4d29-901d-1032dc81d6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>0db39c12-8112-4c57-87f5-2944477ffff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3d33f5aa-6d4a-4c63-93b9-43df3ba68e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Reception_Visit_Type_Id' and @name = 'ReceptionRegister.Reception_Visit_Type_Id' and (text() = '- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
' or . = '- Please select -
Walk-in
IJS-Hub
Telephonic
Email
Fax
Online
')]</value>
      <webElementGuid>40bafaa8-ba24-447c-bad3-044b5071296c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
