<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Date_Of_Birth</name>
   <tag></tag>
   <elementGuidId>fcb0dc52-6e58-4dc3-a74f-38e4de509826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Date_of_Birth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Date_of_Birth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5788d1b7-63ea-4d2d-a858-c7ea2812ea9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>fee1903b-8c1c-4a0b-845b-336b963d7afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1db0ab3e-2e37-4e01-a968-9658df0034e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date of Birth must be a date.</value>
      <webElementGuid>449fa792-8bd0-4070-86e1-ca19ed4e1cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_of_Birth</value>
      <webElementGuid>0f3a1909-772e-4213-bba1-9b37fdf8ef8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Date_Of_Birth</value>
      <webElementGuid>db923aa6-241c-4637-a058-ba3b48251b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Click here to select Birth Date!</value>
      <webElementGuid>514e2256-b3fd-494e-8ff5-09a5ed74603e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>94f94ebc-d82a-496d-921f-393cd22f2ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec14f2aa-7141-41bd-9795-fa3391fed844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcad4e73-17bc-4b90-94ba-e66288ecd32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_of_Birth&quot;)</value>
      <webElementGuid>e946fefb-e80c-46ec-8f87-fe9a1dbc635f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Date_of_Birth']</value>
      <webElementGuid>689a6879-fb67-4c76-83fe-40f7757eb571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>bd28c9dc-6393-4fef-8696-cdf38943a9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>a165194a-5ae6-4448-883a-ebb63a208353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Date_of_Birth' and @name = 'Person.Date_Of_Birth' and @placeholder = 'Click here to select Birth Date!' and @type = 'text']</value>
      <webElementGuid>dfbaa805-4663-465b-94eb-8c7b51c8293e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
