<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contact Us_et_search_icon</name>
   <tag></tag>
   <elementGuidId>e01b7e9f-c043-47f3-b0ed-75469f70f48f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#et_search_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='et_search_icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9c7d3a2-40cb-4b49-9718-32c6caaf1959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>et_search_icon</value>
      <webElementGuid>7fe7cec4-4fae-4acb-ba02-840b6f77e730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et_search_icon&quot;)</value>
      <webElementGuid>271e212c-8217-479c-8ba0-6a626e679b93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='et_search_icon']</value>
      <webElementGuid>12d13b19-3105-4437-91eb-9c21a9c6c652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et_top_search']/span</value>
      <webElementGuid>bdb2ebab-9dd8-4293-b61b-57342aaceddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div[2]/div/span</value>
      <webElementGuid>b89a32bf-1d41-4c5b-b4d6-f26626f91b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'et_search_icon']</value>
      <webElementGuid>c977667c-e408-4d6a-b687-868b3c162d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
