<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6895b6aa-60c5-4052-a6b5-db630dc1b30d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Department of Home Affairs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top']/div/header/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>710c2801-e766-488b-9bac-164c3e756c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.dha.gov.za/images/banners/e-homeaffairs-Banner.jpg</value>
      <webElementGuid>4a8f79dc-2337-4d04-a7d3-a0ced012dcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Department of Home Affairs</value>
      <webElementGuid>5cd5af9b-b436-4b98-80a8-c0aa3d215bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;header-inner clearfix&quot;]/a[@class=&quot;brand pull-left&quot;]/img[1]</value>
      <webElementGuid>0d22ba51-9a32-4bec-84e8-60d46176b8cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/div/header/div/a/img</value>
      <webElementGuid>9a4d779c-8ac1-4462-ade7-78096189fa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Department of Home Affairs']</value>
      <webElementGuid>e5fe8f6d-12c1-4988-bc77-a30b62355dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>084844b0-c752-4779-bb0e-bf1d9ea07da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://www.dha.gov.za/images/banners/e-homeaffairs-Banner.jpg' and @alt = 'Department of Home Affairs']</value>
      <webElementGuid>ffe40b86-677b-4849-9bfb-f2b14c9bedc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
