<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Last_Name</name>
   <tag></tag>
   <elementGuidId>8c627a2f-96bb-4394-8e64-7645b56ab262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LastNameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LastNameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2880914e-c969-4ef1-9f65-d12cd526e036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd9e27f4-d806-410b-b63d-1f8062101e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LastNameText</value>
      <webElementGuid>5b416839-67db-492b-baee-8eba7d297234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Last_Name</value>
      <webElementGuid>11bfae13-fc17-4c92-8ed9-d7d55fd959d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4ec01892-5c94-4125-b9c0-3bc0b40a967f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>649a8bc8-82b6-4ba5-82d9-ec486275da84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a25dc32d-48c1-4063-b1fc-61ab2a787b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LastNameText&quot;)</value>
      <webElementGuid>df335bc2-eb9f-44f0-bfdb-f8202bab5357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LastNameText']</value>
      <webElementGuid>cbcda64d-5b29-4962-85bd-608e2c7530ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[2]/div[4]/input</value>
      <webElementGuid>62b8f25e-0b1a-4d2c-99fa-2c9802336f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]/input</value>
      <webElementGuid>ea072790-a8bd-4d42-8bb2-f19ed6d13e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LastNameText' and @name = 'Person.Last_Name' and @type = 'text']</value>
      <webElementGuid>77416cad-1f75-4fd3-9b76-9edd5f0acb88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
