<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReceptionRegister.Visit_Date</name>
   <tag></tag>
   <elementGuidId>7c327c3f-0999-4e85-9545-85c5c827ec0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Visit_Date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Visit_Date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79aa9dca-cead-4f5e-b300-5ff399f6f204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>2ab45a06-bd6c-4664-9e24-87c79525be28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>663a117d-112c-4b6c-87f8-86e4111690b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Visit Date must be a date.</value>
      <webElementGuid>dee4d1c9-9c8d-43f3-810a-ff6ba866ebcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Visit_Date</value>
      <webElementGuid>f09bf237-5b82-47bc-839a-f6b15c7e1be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Visit_Date</value>
      <webElementGuid>cfce38ef-c964-4da6-8a47-a901bab831f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>8fe004c5-5f0e-4dd4-a126-4b1d1f890117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d23aaf46-ded7-4aa8-b528-cc48d8c91ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b3d3085-9253-48dc-b054-b792751862e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Visit_Date&quot;)</value>
      <webElementGuid>f7a48ab1-bf5f-4921-b0b4-41e2d602a27e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Visit_Date']</value>
      <webElementGuid>c9ca4ac5-d464-4fcb-99f7-0418dfb08b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>e20b258e-e888-45f0-8b29-6c8bf31f2b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>08eff69c-c4f5-4d6b-9e4c-c599dd393f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Visit_Date' and @name = 'ReceptionRegister.Visit_Date' and @type = 'text']</value>
      <webElementGuid>46e84274-ce34-494f-bbfc-f2203ac5cc94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
