<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.First_Name</name>
   <tag></tag>
   <elementGuidId>c8c80dca-80ba-45fc-b3b6-bd6725581be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FirstNameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FirstNameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f008c6a2-6078-44e2-9fcb-cdbedcc3473d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2185180-9b84-4f56-9520-f46103a3c7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FirstNameText</value>
      <webElementGuid>6c330be2-aa3d-4ad8-93bf-9240364bf546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.First_Name</value>
      <webElementGuid>099c0f45-2f93-4d74-a4af-c84b87531f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a9ce7cf8-7f25-4946-bf1b-49411db46a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>860166a7-f7c6-4962-9b03-111286321193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1605e48c-22a6-4b96-810e-66831f035143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FirstNameText&quot;)</value>
      <webElementGuid>21345881-5aec-4fb2-8596-9920c02d1f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FirstNameText']</value>
      <webElementGuid>5725d5b8-8d1f-4c65-a4a4-84c478b4bca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>78e8e6b2-b2ec-4de5-a815-6571c92d894f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>fdb21c50-8593-45d4-8ac7-fbaa0e704525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FirstNameText' and @name = 'Person.First_Name' and @type = 'text']</value>
      <webElementGuid>65dc36ee-235d-4f1e-a86f-b14c5c808d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
