<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maven</name>
   <tag></tag>
   <elementGuidId>c805c46c-9c71-4458-8e1f-122efb3c0ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active > a[title=&quot;Maven&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[2]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>163d30d1-7841-4565-8289-431860ae5fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/maven/maven-introduction/</value>
      <webElementGuid>daa8e197-3332-4c82-a87d-f2869914bbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Maven</value>
      <webElementGuid>d55e7383-5711-4bbd-96c5-b9b46a50360e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maven</value>
      <webElementGuid>8cbd9aec-8ef6-4b7a-9efc-47197975d780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;overlay-open&quot;]/nav[@class=&quot;mega-menu&quot;]/div[@class=&quot;container-fluid mega-menu--container&quot;]/div[@class=&quot;row mega-menu--wrapper&quot;]/div[@class=&quot;col-4&quot;]/div[@class=&quot;second-generation&quot;]/ul[@class=&quot;active&quot;]/li[@class=&quot;active&quot;]/a[1]</value>
      <webElementGuid>8e06747b-08e6-45d2-bcf7-3f0e93f1b90a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Maven')])[3]</value>
      <webElementGuid>595bc09c-4f1c-4d69-bd02-f03cb004bc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::a[1]</value>
      <webElementGuid>7a60abff-f3fa-42f9-bc05-17222d63464b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[2]/following::a[1]</value>
      <webElementGuid>f8e99817-fa0b-45f6-8320-38f38c2aaa76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Git'])[4]/preceding::a[1]</value>
      <webElementGuid>fe344c09-a98b-4fc1-ac27-6d4cb4ee2c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docker'])[2]/preceding::a[2]</value>
      <webElementGuid>347954a2-d629-4387-baf9-aea6d36dc1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/maven/maven-introduction/')])[3]</value>
      <webElementGuid>39e4ec91-e28e-4a7d-8e6c-79e213140c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>ced08513-656d-4b61-8326-0c23cfc63f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/maven/maven-introduction/' and @title = 'Maven' and (text() = 'Maven' or . = 'Maven')]</value>
      <webElementGuid>5a01c8b8-d6ef-48aa-a88f-32ca2862331f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
