<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intake</name>
   <tag></tag>
   <elementGuidId>d64adf2a-67c8-4779-afa6-e99d0224f633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Intake']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Intake > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cf8cf9f-b411-4fb5-acf4-5bd2474fc45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index</value>
      <webElementGuid>846f4bf3-620e-432b-9b63-14edc91b42ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intake</value>
      <webElementGuid>1f41b0d5-6f18-4381-8b0f-fcd866f30940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Intake&quot;)/a[1]</value>
      <webElementGuid>f8412422-d7a4-4df2-928c-2b53229dc2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Intake']/a</value>
      <webElementGuid>fe766b03-2e46-44e8-8577-bc5b1dbaf57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intake')]</value>
      <webElementGuid>00ef1e50-7c0f-4d25-abea-d55c5dc9271e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDICMS'])[1]/following::a[2]</value>
      <webElementGuid>be6feaed-07db-4978-af10-e305bd42c74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPAR'])[1]/preceding::a[1]</value>
      <webElementGuid>bba34f21-3a3d-4b12-9e8f-d06b782f0320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADS'])[1]/preceding::a[2]</value>
      <webElementGuid>9af1f2f0-e1ae-459d-9714-aeb98636b8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intake']/parent::*</value>
      <webElementGuid>8818ff99-9f8f-4b5b-9da2-f2b1e82322e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index')]</value>
      <webElementGuid>5b0d922a-2647-4170-8fa5-adec1df2b569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>6bae4560-595e-4ef9-bcbc-10c991bcf1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index' and (text() = 'Intake' or . = 'Intake')]</value>
      <webElementGuid>0735077c-8d14-46e6-9f02-14c0c4d3ac2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
