<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_Search_Date_Of_Birth</name>
   <tag></tag>
   <elementGuidId>8c84db04-de95-43f2-be86-c747913da660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Date_Of_Birth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Date_Of_Birth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>240fc541-582d-47c8-94c2-ad34c1467d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>4df74a58-4476-4b9e-a5f4-2a5fcc0a01cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Date_Of_Birth</value>
      <webElementGuid>2ba39f35-834a-44e0-b28d-054b6290f601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Date_Of_Birth</value>
      <webElementGuid>f128d55a-04df-456b-afa1-e402b64b6515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27e230ce-4fb7-43cb-b003-71dea10423ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Date_Of_Birth&quot;)</value>
      <webElementGuid>64eb8a49-0b39-44ac-b59e-f88b336afda3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Date_Of_Birth']</value>
      <webElementGuid>cead0c3f-1410-4228-b8d1-4091f86064f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[10]/div/input</value>
      <webElementGuid>1e5cc234-874e-46c5-8f39-dc66b673ddbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>5d807aee-8d3c-4fae-8b17-7130e7e578a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Date_Of_Birth' and @name = 'Search_Date_Of_Birth' and @type = 'text']</value>
      <webElementGuid>86e498ce-5717-4f9b-b494-8345ab77d515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
