<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client Ref No_Search_Client_Ref_No</name>
   <tag></tag>
   <elementGuidId>6f100179-7d95-4bdb-9785-1aa0ef2d8a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Client_Ref_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Client_Ref_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37f4cc43-9a77-4b64-9797-b9d0e3f83b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Client_Ref_No</value>
      <webElementGuid>fb17d5a0-6b63-4bfe-9576-254b233dd95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f3c1d46b-5fbc-4a96-8f2c-b321ce4e31e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Client_Ref_No</value>
      <webElementGuid>4aeac16c-1f1e-4b90-9365-6f1240bbbc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcc81f11-7386-4e13-9154-6644208efda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Client_Ref_No&quot;)</value>
      <webElementGuid>ae3da88b-8d45-4c3c-b262-01af22e57424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Client_Ref_No']</value>
      <webElementGuid>ae1f755b-6560-4b88-a5dd-94d2df1029b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[2]/input</value>
      <webElementGuid>8414f94f-a61a-4ccc-967a-f604b6cf7af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>4c44ab16-f538-4306-984c-c5b0212a0238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Client_Ref_No' and @name = 'Search_Client_Ref_No' and @type = 'text']</value>
      <webElementGuid>7396bfd5-73e3-4571-8b71-21397772f2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
