<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_Search_Last_Name</name>
   <tag></tag>
   <elementGuidId>4781f189-1ae6-4add-9812-56841ec1997d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Last_Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Last_Name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3587bab2-bd0a-4eaa-8a86-d0e08ae70215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fcacbfd7-2687-4e2f-be03-40ce4cfa5646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Last_Name</value>
      <webElementGuid>fb577cc0-657a-4615-bff6-0f38e6619908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Last_Name</value>
      <webElementGuid>de36d606-796f-4657-a390-fef27af08088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>842079a1-d40e-4395-ab26-7f66d924a797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Last_Name&quot;)</value>
      <webElementGuid>4da1daa4-1d09-4589-a140-0ee278ad5d5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Last_Name']</value>
      <webElementGuid>32f10201-f860-4e62-9e78-4aa2481c0086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[8]/input</value>
      <webElementGuid>6dc13f27-f4ca-4e5d-bf07-28f069e4fcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>72c1d16c-956c-4c15-a405-1d9f1f75fb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Last_Name' and @name = 'Search_Last_Name' and @type = 'text']</value>
      <webElementGuid>cc3259e6-35dd-4e1f-9f12-3415eac05d19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
