<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cypress with Cucumber BDD - Beginner to E_d66139</name>
   <tag></tag>
   <elementGuidId>6e3aac2e-246b-4f94-98e8-177eea4b38da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='udemy-promo-thumbnail']/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d138c61-4fc2-48a3-89ec-fa85ff6a9fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.udemy.com/course/cypress-with-cucumber-bdd-beginner-to-expert-in-9-hours/?couponCode=B91A7537D78D20E25FC0</value>
      <webElementGuid>70efe09c-501c-4f49-a312-eca5d1e8ed46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cypress with Cucumber BDD - Beginner to Expert in 9 Hours!</value>
      <webElementGuid>84257a9b-aa99-48e2-85c4-bcce4db126ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udemy-promo-thumbnail&quot;)/p[1]/a[1]</value>
      <webElementGuid>fbe98dfd-2f5d-41fe-9e7c-3e887711cc72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udemy-promo-thumbnail']/p/a</value>
      <webElementGuid>ed422f06-3644-4722-9021-2cff70d40070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cypress with Cucumber BDD - Beginner to Expert in 9 Hours!')]</value>
      <webElementGuid>7373f674-438e-4396-863e-71f4ea98fbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid until 18/10/2023.'])[1]/following::a[1]</value>
      <webElementGuid>71b54afe-662b-429f-b096-84fd7d043023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Complete Cypress v12 Course: From Zero to Expert! [2023]'])[1]/preceding::a[1]</value>
      <webElementGuid>c63dbda6-00a6-45d6-9c66-36caf0084e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Complete WebdriverIO Course: From Zero to Expert! [2023]'])[1]/preceding::a[2]</value>
      <webElementGuid>f68d6321-9c28-481c-a8fc-2dcece038de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cypress with Cucumber BDD - Beginner to Expert in 9 Hours!']/parent::*</value>
      <webElementGuid>c803dc6e-8a1c-48e9-96c0-2793937c91ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.udemy.com/course/cypress-with-cucumber-bdd-beginner-to-expert-in-9-hours/?couponCode=B91A7537D78D20E25FC0')]</value>
      <webElementGuid>2ddb9dc6-60f5-44e5-a8fe-99ba3a750ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>a4fb363b-e227-4a98-a6a3-806f4d5324b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.udemy.com/course/cypress-with-cucumber-bdd-beginner-to-expert-in-9-hours/?couponCode=B91A7537D78D20E25FC0' and (text() = 'Cypress with Cucumber BDD - Beginner to Expert in 9 Hours!' or . = 'Cypress with Cucumber BDD - Beginner to Expert in 9 Hours!')]</value>
      <webElementGuid>8a149e56-2f16-4218-a358-d86958926c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
