<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_Search_Date_Of_Birth</name>
   <tag></tag>
   <elementGuidId>5a9ad210-9182-47e3-95dc-06271fe149e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Date_Of_Birth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Date_Of_Birth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>191be824-84d2-48a5-b33e-f6e98d42c9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>7f3369be-8c85-45c7-9f1c-08add073e8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Date_Of_Birth</value>
      <webElementGuid>9851700d-5fd1-4886-a345-762585869320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Date_Of_Birth</value>
      <webElementGuid>b33af1a1-2030-4f9c-8514-02f688072ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0275bdd6-a556-4811-8c89-d5faad4dc094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Date_Of_Birth&quot;)</value>
      <webElementGuid>79affa08-a540-41c6-abb4-1aad893de1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Date_Of_Birth']</value>
      <webElementGuid>d28a705e-0701-4ea5-b15d-f725dfbd6093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[10]/div/input</value>
      <webElementGuid>a579126d-c2f5-45bc-a02f-c1541effad84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>3fe990e1-230a-4dbf-ad6b-946db5fe48c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Date_Of_Birth' and @name = 'Search_Date_Of_Birth' and @type = 'text']</value>
      <webElementGuid>d689b46f-41bd-491a-bd08-b6abf7685bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
