<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client Ref No_Search_Client_Ref_No</name>
   <tag></tag>
   <elementGuidId>d333250d-f191-4983-bcd2-9d2600147c12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Client_Ref_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Client_Ref_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34eaaa26-b32d-43e9-bdb7-bdf04d7ce43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Client_Ref_No</value>
      <webElementGuid>8305e25a-4cc5-40e1-8495-5ac611e6dfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc291cea-be19-48bf-b9bb-b75567246bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Client_Ref_No</value>
      <webElementGuid>2fe44a39-c7bc-48d3-aa53-c116d42b56a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a80f25e6-01a4-43f7-9d28-40f73978c532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Client_Ref_No&quot;)</value>
      <webElementGuid>ba3ef6f8-4d81-46b0-82f5-55055da261e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Client_Ref_No']</value>
      <webElementGuid>c764618a-1635-4489-8491-1a6ba9b763fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[2]/input</value>
      <webElementGuid>9a49b35e-808e-4295-b2f9-34ca4553bb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>c144aba0-c166-40b2-90da-b97945ec3dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Client_Ref_No' and @name = 'Search_Client_Ref_No' and @type = 'text']</value>
      <webElementGuid>43c061cb-6d75-475c-a3bf-122626a00220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
