<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_takelot.co.za_namemaster-1,master-a-_ab991d</name>
   <tag></tag>
   <elementGuidId>5f28c090-de64-4278-8631-9d4fc43abce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#master-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='master-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>18eee95a-77cb-47fc-b7b6-4b51b726f4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>610e8d31-371b-4019-a969-295353d5283d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93986945-05b1-44b6-b51f-5cfebc84b393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c85fcf02-5393-41ce-af69-2cae75c2bd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd14bf14-cb3c-4203-b8ba-0d22aa37a19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e437b4cb-844d-4e97-96ea-c4025e24a131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>55a39650-fb97-4d9a-961b-90db075fc237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;master-1&quot;,&quot;master-a-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkxOC4wOTc6NGJhZTdkYjIzNDdlZjdhOTFhYmEyMzNkOTY4NzQ2ZDljNGJiZWNlOGIzMzBmNGViZjMwNmQ5Y2I1NDJlNDc1ODo2NTJjNDg1NjE3YWU0&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&amp;kw=Takealot&quot;,&quot;container&quot;:&quot;ads&quot;,&quot;styleId&quot;:1167268112,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;adLoadedCallback&quot;:null,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;ads&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:13},&quot;master-b-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkxOC4wOTc6NGJhZTdkYjIzNDdlZjdhOTFhYmEyMzNkOTY4NzQ2ZDljNGJiZWNlOGIzMzBmNGViZjMwNmQ5Y2I1NDJlNDc1ODo2NTJjNDg1NjE3YWU0&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&amp;kw=Takealot&quot;,&quot;container&quot;:&quot;ads&quot;,&quot;styleId&quot;:1167268112,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;adLoadedCallback&quot;:null,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;ads&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:13},&quot;master-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkxOC4wOTc6NGJhZTdkYjIzNDdlZjdhOTFhYmEyMzNkOTY4NzQ2ZDljNGJiZWNlOGIzMzBmNGViZjMwNmQ5Y2I1NDJlNDc1ODo2NTJjNDg1NjE3YWU0&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&amp;kw=Takealot&quot;,&quot;container&quot;:&quot;ads&quot;,&quot;styleId&quot;:1167268112,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011&quot;,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:3,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;query&quot;:&quot;Takealot&quot;,&quot;role&quot;:&quot;m&quot;,&quot;sct&quot;:&quot;ID=183b34b63c54e072:T=1697400909:RT=1697400909:S=ALNI_MY4KVlhSicl_TGjONkTpGXhVXjB0A&quot;,&quot;sc_status&quot;:6,&quot;hl&quot;:&quot;en&quot;,&quot;colorText&quot;:&quot;#333&quot;,&quot;colorTitleLink&quot;:&quot;#0277bd&quot;,&quot;colorAttribution&quot;:&quot;#aaa&quot;,&quot;fontFamily&quot;:&quot;Arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;titleBold&quot;:false,&quot;rolloverLinkBold&quot;:false,&quot;rolloverLinkColor&quot;:&quot;#01579b&quot;,&quot;rolloverLinkUnderline&quot;:true,&quot;noTitleUnderline&quot;:false,&quot;lineHeightTitle&quot;:30,&quot;resultsPageBaseUrl&quot;:&quot;http://www.takelot.co.za/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;Takealot,South Africa Online Shopping,Books,Kitchen Appliances for Sale,Tablets,Cheap Furniture Online Stores,Bedroom Furniture for Cheap,Cheap Office Furniture,Download Free Online Books,Furniture Sale&quot;,&quot;kw&quot;:&quot;&quot;,&quot;afdToken&quot;:&quot;ChMI7LqLku_4gQMVsFVBAB0LUAMmEmUBxDSP9ea5obD7bok4xhJ_dm71idtQO53BGr8GF647TBlQ8nmK2Hc1GgdcnQK31CpJRWDmYIveysgpj3cqNtTQc84CSaP0GHDnPz_YFmFtQzfluQvAoutuPeNGH9YzfmG_GRZcbA&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;ads&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;verticalSpacing&quot;:24,&quot;fontSizeTitle&quot;:&quot;22px&quot;,&quot;fontSizeAttribution&quot;:&quot;16px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;attributionBold&quot;:false,&quot;titleUppercase&quot;:false,&quot;webFontFamily&quot;:&quot;Poppins&quot;,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2556825297878728&quot;}}</value>
      <webElementGuid>c7b26889-f3d8-4173-abb7-ee9e40fd1da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-1</value>
      <webElementGuid>ce39f6b0-09cc-4e9a-8f10-92f63865e6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/afs/ads?adtest=off&amp;psid=1167268112&amp;pcsa=false&amp;channel=000001%2Cbucket011&amp;client=dp-teaminternet09_3ph&amp;r=m&amp;sct=ID%3D183b34b63c54e072%3AT%3D1697400909%3ART%3D1697400909%3AS%3DALNI_MY4KVlhSicl_TGjONkTpGXhVXjB0A&amp;sc_status=6&amp;hl=en&amp;rpbu=http%3A%2F%2Fwww.takelot.co.za%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%253D%253D&amp;terms=Takealot%2CSouth%20Africa%20Online%20Shopping%2CBooks%2CKitchen%20Appliances%20for%20Sale%2CTablets%2CCheap%20Furniture%20Online%20Stores%2CBedroom%20Furniture%20for%20Cheap%2CCheap%20Office%20Furniture%2CDownload%20Free%20Online%20Books%2CFurniture%20Sale&amp;max_radlink_len=40&amp;type=0&amp;uiopt=true&amp;swp=as-drid-2556825297878728&amp;q=Takealot&amp;afdt=ChMI7LqLku_4gQMVsFVBAB0LUAMmEmUBxDSP9ea5obD7bok4xhJ_dm71idtQO53BGr8GF647TBlQ8nmK2Hc1GgdcnQK31CpJRWDmYIveysgpj3cqNtTQc84CSaP0GHDnPz_YFmFtQzfluQvAoutuPeNGH9YzfmG_GRZcbA&amp;oe=UTF-8&amp;ie=UTF-8&amp;fexp=21404&amp;format=n3&amp;ad=n3&amp;nocache=1521697400918463&amp;num=0&amp;output=afd_ads&amp;domain_name=www.takelot.co.za&amp;v=3&amp;bsl=8&amp;pac=0&amp;u_his=3&amp;u_tz=120&amp;dt=1697400918463&amp;u_w=1366&amp;u_h=768&amp;biw=1017&amp;bih=606&amp;psw=1017&amp;psh=754&amp;frm=0&amp;cl=571959512&amp;uio=-&amp;cont=ads&amp;jsid=caf&amp;jsv=571959512&amp;rurl=http%3A%2F%2Fwww.takelot.co.za%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%253D%253D%26query%3DTakealot%26afdToken%3DChMI7LqLku_4gQMVsFVBAB0LUAMmEmUBxDSP9ea5obD7bok4xhJ_dm71idtQO53BGr8GF647TBlQ8nmK2Hc1GgdcnQK31CpJRWDmYIveysgpj3cqNtTQc84CSaP0GHDnPz_YFmFtQzfluQvAoutuPeNGH9YzfmG_GRZcbA%26pcsa%3Dfalse%26nb%3D0%26nm%3D27%26nx%3D91%26ny%3D71%26is%3D530x496%26clkt%3D82&amp;referer=https%3A%2F%2Fwww.google.com%2F</value>
      <webElementGuid>4d7bdca6-2251-425c-a915-96aad5d5ed59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-1&quot;)</value>
      <webElementGuid>03f2bbe3-d29c-4370-a56a-09843366149f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='master-1']</value>
      <webElementGuid>4a066978-8f50-4d7a-90aa-3789deb59563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ads']/iframe[2]</value>
      <webElementGuid>5a406561-69a3-41e0-b1f4-7742a8b482e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>2a683dc5-bf65-44bd-9808-3dabadb8fa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '{&quot;name&quot;:&quot;master-1&quot;,&quot;master-a-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkxOC4wOTc6NGJhZTdkYjIzNDdlZjdhOTFhYmEyMzNkOTY4NzQ2ZDljNGJiZWNlOGIzMzBmNGViZjMwNmQ5Y2I1NDJlNDc1ODo2NTJjNDg1NjE3YWU0&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&amp;kw=Takealot&quot;,&quot;container&quot;:&quot;ads&quot;,&quot;styleId&quot;:1167268112,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;adLoadedCallback&quot;:null,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;ads&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:13},&quot;master-b-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkxOC4wOTc6NGJhZTdkYjIzNDdlZjdhOTFhYmEyMzNkOTY4NzQ2ZDljNGJiZWNlOGIzMzBmNGViZjMwNmQ5Y2I1NDJlNDc1ODo2NTJjNDg1NjE3YWU0&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&amp;kw=Takealot&quot;,&quot;container&quot;:&quot;ads&quot;,&quot;styleId&quot;:1167268112,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;adLoadedCallback&quot;:null,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;ads&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:13},&quot;master-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkxOC4wOTc6NGJhZTdkYjIzNDdlZjdhOTFhYmEyMzNkOTY4NzQ2ZDljNGJiZWNlOGIzMzBmNGViZjMwNmQ5Y2I1NDJlNDc1ODo2NTJjNDg1NjE3YWU0&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&amp;kw=Takealot&quot;,&quot;container&quot;:&quot;ads&quot;,&quot;styleId&quot;:1167268112,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011&quot;,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:3,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;query&quot;:&quot;Takealot&quot;,&quot;role&quot;:&quot;m&quot;,&quot;sct&quot;:&quot;ID=183b34b63c54e072:T=1697400909:RT=1697400909:S=ALNI_MY4KVlhSicl_TGjONkTpGXhVXjB0A&quot;,&quot;sc_status&quot;:6,&quot;hl&quot;:&quot;en&quot;,&quot;colorText&quot;:&quot;#333&quot;,&quot;colorTitleLink&quot;:&quot;#0277bd&quot;,&quot;colorAttribution&quot;:&quot;#aaa&quot;,&quot;fontFamily&quot;:&quot;Arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;titleBold&quot;:false,&quot;rolloverLinkBold&quot;:false,&quot;rolloverLinkColor&quot;:&quot;#01579b&quot;,&quot;rolloverLinkUnderline&quot;:true,&quot;noTitleUnderline&quot;:false,&quot;lineHeightTitle&quot;:30,&quot;resultsPageBaseUrl&quot;:&quot;http://www.takelot.co.za/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;Takealot,South Africa Online Shopping,Books,Kitchen Appliances for Sale,Tablets,Cheap Furniture Online Stores,Bedroom Furniture for Cheap,Cheap Office Furniture,Download Free Online Books,Furniture Sale&quot;,&quot;kw&quot;:&quot;&quot;,&quot;afdToken&quot;:&quot;ChMI7LqLku_4gQMVsFVBAB0LUAMmEmUBxDSP9ea5obD7bok4xhJ_dm71idtQO53BGr8GF647TBlQ8nmK2Hc1GgdcnQK31CpJRWDmYIveysgpj3cqNtTQc84CSaP0GHDnPz_YFmFtQzfluQvAoutuPeNGH9YzfmG_GRZcbA&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;ads&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;verticalSpacing&quot;:24,&quot;fontSizeTitle&quot;:&quot;22px&quot;,&quot;fontSizeAttribution&quot;:&quot;16px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;attributionBold&quot;:false,&quot;titleUppercase&quot;:false,&quot;webFontFamily&quot;:&quot;Poppins&quot;,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2556825297878728&quot;}}' and @id = 'master-1' and @src = 'https://www.google.com/afs/ads?adtest=off&amp;psid=1167268112&amp;pcsa=false&amp;channel=000001%2Cbucket011&amp;client=dp-teaminternet09_3ph&amp;r=m&amp;sct=ID%3D183b34b63c54e072%3AT%3D1697400909%3ART%3D1697400909%3AS%3DALNI_MY4KVlhSicl_TGjONkTpGXhVXjB0A&amp;sc_status=6&amp;hl=en&amp;rpbu=http%3A%2F%2Fwww.takelot.co.za%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkxOC4xMDUxfDIzMzIzNWVjNDgwMDEwM2YxNDYyODU3ODcwZDMyMDk4MzY3NDg2N2J8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%253D%253D&amp;terms=Takealot%2CSouth%20Africa%20Online%20Shopping%2CBooks%2CKitchen%20Appliances%20for%20Sale%2CTablets%2CCheap%20Furniture%20Online%20Stores%2CBedroom%20Furniture%20for%20Cheap%2CCheap%20Office%20Furniture%2CDownload%20Free%20Online%20Books%2CFurniture%20Sale&amp;max_radlink_len=40&amp;type=0&amp;uiopt=true&amp;swp=as-drid-2556825297878728&amp;q=Takealot&amp;afdt=ChMI7LqLku_4gQMVsFVBAB0LUAMmEmUBxDSP9ea5obD7bok4xhJ_dm71idtQO53BGr8GF647TBlQ8nmK2Hc1GgdcnQK31CpJRWDmYIveysgpj3cqNtTQc84CSaP0GHDnPz_YFmFtQzfluQvAoutuPeNGH9YzfmG_GRZcbA&amp;oe=UTF-8&amp;ie=UTF-8&amp;fexp=21404&amp;format=n3&amp;ad=n3&amp;nocache=1521697400918463&amp;num=0&amp;output=afd_ads&amp;domain_name=www.takelot.co.za&amp;v=3&amp;bsl=8&amp;pac=0&amp;u_his=3&amp;u_tz=120&amp;dt=1697400918463&amp;u_w=1366&amp;u_h=768&amp;biw=1017&amp;bih=606&amp;psw=1017&amp;psh=754&amp;frm=0&amp;cl=571959512&amp;uio=-&amp;cont=ads&amp;jsid=caf&amp;jsv=571959512&amp;rurl=http%3A%2F%2Fwww.takelot.co.za%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%253D%253D%26query%3DTakealot%26afdToken%3DChMI7LqLku_4gQMVsFVBAB0LUAMmEmUBxDSP9ea5obD7bok4xhJ_dm71idtQO53BGr8GF647TBlQ8nmK2Hc1GgdcnQK31CpJRWDmYIveysgpj3cqNtTQc84CSaP0GHDnPz_YFmFtQzfluQvAoutuPeNGH9YzfmG_GRZcbA%26pcsa%3Dfalse%26nb%3D0%26nm%3D27%26nx%3D91%26ny%3D71%26is%3D530x496%26clkt%3D82&amp;referer=https%3A%2F%2Fwww.google.com%2F']</value>
      <webElementGuid>a54a1505-d8a5-4b58-8aa1-1455c85707a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
