<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_takelot.co.za_namemaster-1,slave-1-1_a3b7a7</name>
   <tag></tag>
   <elementGuidId>da653bbf-cc4b-4956-89c1-37e56c6787d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#master-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='master-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>be1f03e9-3a76-443b-9e55-167d1766921b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1f6fffe-39b7-4893-ad0f-ce5b505552ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f87f48a1-3f4f-473b-a86f-6bc4694edf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12e58d38-4bbb-4ca0-8e97-3481b8fc6b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e24f023a-0853-435d-a886-4124c5336f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>28ed4d59-dd00-4cf7-9156-9da529312420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>db2d8c78-72b1-48b4-8cff-bf44991b88b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;master-1&quot;,&quot;slave-1-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkwOC41MDY4OjE2ZTE3N2QzZTA5OTZhZjc1MDBjYzgyMGJkNWExZWY0Y2MxNjkwMTczMWFmYTk0OTdlMTQzYzFkYWFiMmVjYmQ6NjUyYzQ4NGM3YmJkMg%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY0fDUxMjM1NTI2YzZhZWEyZDU5MGY5MWRhMzViZTQ3ZGViYzI3ZmJlMTF8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&quot;,&quot;container&quot;:&quot;search&quot;,&quot;styleId&quot;:1167268112,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011&quot;,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;slaveNumber&quot;:1,&quot;hl&quot;:&quot;en&quot;,&quot;colorAttribution&quot;:&quot;#b7b7b7&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;resultsPageBaseUrl&quot;:&quot;http://www.takelot.co.za/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;Takealot,South Africa Online Shopping,Books,Kitchen Appliances for Sale,Tablets,Cheap Furniture Online Stores,Bedroom Furniture for Cheap,Cheap Office Furniture,Download Free Online Books,Furniture Sale&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;searchbox&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:&quot;16px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;hideSearchInputBorder&quot;:false,&quot;hideSearchButtonBorder&quot;:true,&quot;colorSearchButton&quot;:&quot;#0b3279&quot;,&quot;colorSearchButtonText&quot;:&quot;#fff&quot;,&quot;fontSizeSearchInput&quot;:12,&quot;fontSizeSearchButton&quot;:13,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2556825297878728&quot;},&quot;master-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkwOC41MDY4OjE2ZTE3N2QzZTA5OTZhZjc1MDBjYzgyMGJkNWExZWY0Y2MxNjkwMTczMWFmYTk0OTdlMTQzYzFkYWFiMmVjYmQ6NjUyYzQ4NGM3YmJkMg%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY0fDUxMjM1NTI2YzZhZWEyZDU5MGY5MWRhMzViZTQ3ZGViYzI3ZmJlMTF8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&quot;,&quot;container&quot;:&quot;tc&quot;,&quot;styleId&quot;:1167268112,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011&quot;,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:3,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;m&quot;,&quot;hl&quot;:&quot;en&quot;,&quot;colorTitleLink&quot;:&quot;#0277bd&quot;,&quot;colorAttribution&quot;:&quot;#aaa&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;rolloverLinkColor&quot;:&quot;#01579b&quot;,&quot;noTitleUnderline&quot;:false,&quot;lineHeightTitle&quot;:34,&quot;resultsPageBaseUrl&quot;:&quot;http://www.takelot.co.za/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;center&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;Takealot,South Africa Online Shopping,Books,Kitchen Appliances for Sale,Tablets,Cheap Furniture Online Stores,Bedroom Furniture for Cheap,Cheap Office Furniture,Download Free Online Books,Furniture Sale&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;relatedsearch&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;verticalSpacing&quot;:10,&quot;fontSizeTitle&quot;:&quot;24px&quot;,&quot;fontSizeAttribution&quot;:&quot;14px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2556825297878728&quot;}}</value>
      <webElementGuid>3834a764-e00d-4c9d-9e31-8f961dcf358d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-1</value>
      <webElementGuid>11da4673-d027-4a07-b958-e02134db6390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/afs/ads?adtest=off&amp;psid=1167268112&amp;pcsa=false&amp;channel=000001%2Cbucket011&amp;client=dp-teaminternet09_3ph&amp;r=m&amp;hl=en&amp;rpbu=http%3A%2F%2Fwww.takelot.co.za%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%253D%253D&amp;terms=Takealot%2CSouth%20Africa%20Online%20Shopping%2CBooks%2CKitchen%20Appliances%20for%20Sale%2CTablets%2CCheap%20Furniture%20Online%20Stores%2CBedroom%20Furniture%20for%20Cheap%2CCheap%20Office%20Furniture%2CDownload%20Free%20Online%20Books%2CFurniture%20Sale&amp;max_radlink_len=40&amp;type=3&amp;uiopt=true&amp;swp=as-drid-2556825297878728&amp;oe=UTF-8&amp;ie=UTF-8&amp;fexp=21404&amp;format=r3%7Cs&amp;nocache=251697400909130&amp;num=0&amp;output=afd_ads&amp;domain_name=www.takelot.co.za&amp;v=3&amp;bsl=8&amp;pac=0&amp;u_his=2&amp;u_tz=120&amp;dt=1697400909132&amp;u_w=1366&amp;u_h=768&amp;biw=1017&amp;bih=606&amp;psw=1017&amp;psh=754&amp;frm=0&amp;cl=571959512&amp;uio=--&amp;cont=tc&amp;jsid=caf&amp;jsv=571959512&amp;rurl=http%3A%2F%2Fwww.takelot.co.za%2F</value>
      <webElementGuid>4a57267f-3893-4b0b-8fca-9d731fc13ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-1&quot;)</value>
      <webElementGuid>d43e919b-a861-4c00-b70c-b8d0f66bbf33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='master-1']</value>
      <webElementGuid>663db278-798b-4f01-b1d0-6c6255e9626f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tc']/iframe</value>
      <webElementGuid>c82b8260-55f9-42a6-ad22-2927e4998ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>913c49a5-1a1b-46be-9427-e6bc168f7085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '{&quot;name&quot;:&quot;master-1&quot;,&quot;slave-1-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkwOC41MDY4OjE2ZTE3N2QzZTA5OTZhZjc1MDBjYzgyMGJkNWExZWY0Y2MxNjkwMTczMWFmYTk0OTdlMTQzYzFkYWFiMmVjYmQ6NjUyYzQ4NGM3YmJkMg%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY0fDUxMjM1NTI2YzZhZWEyZDU5MGY5MWRhMzViZTQ3ZGViYzI3ZmJlMTF8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&quot;,&quot;container&quot;:&quot;search&quot;,&quot;styleId&quot;:1167268112,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011&quot;,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;slaveNumber&quot;:1,&quot;hl&quot;:&quot;en&quot;,&quot;colorAttribution&quot;:&quot;#b7b7b7&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;resultsPageBaseUrl&quot;:&quot;http://www.takelot.co.za/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;Takealot,South Africa Online Shopping,Books,Kitchen Appliances for Sale,Tablets,Cheap Furniture Online Stores,Bedroom Furniture for Cheap,Cheap Office Furniture,Download Free Online Books,Furniture Sale&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;searchbox&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:&quot;16px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;hideSearchInputBorder&quot;:false,&quot;hideSearchButtonBorder&quot;:true,&quot;colorSearchButton&quot;:&quot;#0b3279&quot;,&quot;colorSearchButtonText&quot;:&quot;#fff&quot;,&quot;fontSizeSearchInput&quot;:12,&quot;fontSizeSearchButton&quot;:13,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2556825297878728&quot;},&quot;master-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://parking-crew.com/track.php?click=caf&amp;domain=takelot.co.za&amp;uid=MTY5NzQwMDkwOC41MDY4OjE2ZTE3N2QzZTA5OTZhZjc1MDBjYzgyMGJkNWExZWY0Y2MxNjkwMTczMWFmYTk0OTdlMTQzYzFkYWFiMmVjYmQ6NjUyYzQ4NGM3YmJkMg%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY0fDUxMjM1NTI2YzZhZWEyZDU5MGY5MWRhMzViZTQ3ZGViYzI3ZmJlMTF8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&amp;adtest=off&quot;,&quot;container&quot;:&quot;tc&quot;,&quot;styleId&quot;:1167268112,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011&quot;,&quot;domainName&quot;:&quot;www.takelot.co.za&quot;,&quot;fexp&quot;:&quot;21404&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:3,&quot;pubId&quot;:&quot;dp-teaminternet09_3ph&quot;,&quot;role&quot;:&quot;m&quot;,&quot;hl&quot;:&quot;en&quot;,&quot;colorTitleLink&quot;:&quot;#0277bd&quot;,&quot;colorAttribution&quot;:&quot;#aaa&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;rolloverLinkColor&quot;:&quot;#01579b&quot;,&quot;noTitleUnderline&quot;:false,&quot;lineHeightTitle&quot;:34,&quot;resultsPageBaseUrl&quot;:&quot;http://www.takelot.co.za/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%3D%3D&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;center&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;Takealot,South Africa Online Shopping,Books,Kitchen Appliances for Sale,Tablets,Cheap Furniture Online Stores,Bedroom Furniture for Cheap,Cheap Office Furniture,Download Free Online Books,Furniture Sale&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;relatedsearch&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;verticalSpacing&quot;:10,&quot;fontSizeTitle&quot;:&quot;24px&quot;,&quot;fontSizeAttribution&quot;:&quot;14px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2556825297878728&quot;}}' and @id = 'master-1' and @src = 'https://www.google.com/afs/ads?adtest=off&amp;psid=1167268112&amp;pcsa=false&amp;channel=000001%2Cbucket011&amp;client=dp-teaminternet09_3ph&amp;r=m&amp;hl=en&amp;rpbu=http%3A%2F%2Fwww.takelot.co.za%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTF8fHx8fHw2NTJjNDg0YzdiYmFmfHx8MTY5NzQwMDkwOC41MTY1fGE0ZTY5MjBhMmI2NTJhNzMzZmZlMzc1NmVjYjYyODY4NmRhYWRhODZ8fHx8fDF8fDB8MHx8fHwxfHx8fHwwfDB8UEhOamNtbHdkQ0J6Y21NOUlpOHZaREZzZUdoak5HcDJjM1I2Y25BdVkyeHZkV1JtY205dWRDNXVaWFF2YzJOeWFYQjBjeTlqYjNKdmJtRXViV2x1TG1weklpQjBlWEJsUFNKMFpYaDBMMnBoZG1GelkzSnBjSFFpUGp3dmMyTnlhWEIwUGc9PXxhNjllNWE3OGNmZTNjYWM3YmYwMzU0MDQ3YjFkZGVkNGE4MmUwN2RmfHx8fHx8fHwwfDB8fDB8fHwwfDB8VzEwPXx8MXxXMTA9fGMzZmU2ZjI3YjAyMmM4ZGJkZDhjMzdjOGY4MzBiNWZhNDRmNTZiYTd8MHxkcC10ZWFtaW50ZXJuZXQwOV8zcGh8MHwwfA%253D%253D&amp;terms=Takealot%2CSouth%20Africa%20Online%20Shopping%2CBooks%2CKitchen%20Appliances%20for%20Sale%2CTablets%2CCheap%20Furniture%20Online%20Stores%2CBedroom%20Furniture%20for%20Cheap%2CCheap%20Office%20Furniture%2CDownload%20Free%20Online%20Books%2CFurniture%20Sale&amp;max_radlink_len=40&amp;type=3&amp;uiopt=true&amp;swp=as-drid-2556825297878728&amp;oe=UTF-8&amp;ie=UTF-8&amp;fexp=21404&amp;format=r3%7Cs&amp;nocache=251697400909130&amp;num=0&amp;output=afd_ads&amp;domain_name=www.takelot.co.za&amp;v=3&amp;bsl=8&amp;pac=0&amp;u_his=2&amp;u_tz=120&amp;dt=1697400909132&amp;u_w=1366&amp;u_h=768&amp;biw=1017&amp;bih=606&amp;psw=1017&amp;psh=754&amp;frm=0&amp;cl=571959512&amp;uio=--&amp;cont=tc&amp;jsid=caf&amp;jsv=571959512&amp;rurl=http%3A%2F%2Fwww.takelot.co.za%2F']</value>
      <webElementGuid>97afa12d-dc8f-40e1-bdb0-dcfe3cb5c8f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
