<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accept</name>
   <tag></tag>
   <elementGuidId>4b553aaa-f01a-4a79-ba4b-d03d7007d7d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='inboxItemGrid']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd3b0f0e-38d5-4531-b0f1-4426040333d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>ead73027-a9ed-44fd-b2ec-7ee6e24471ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SDICMS_TEST/Intake/AcceptInboxItem/19806</value>
      <webElementGuid>847d2b12-c605-4554-ad08-5318ede9f172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>56413613-bb01-4c4e-9de5-2093d51778c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inboxItemGrid&quot;)/tbody[1]/tr[@class=&quot;webgrid-row-style&quot;]/td[@class=&quot;EditPersonWidth&quot;]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>19403b92-d3a9-4465-8577-8ceec72d84e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='inboxItemGrid']/tbody/tr/td[5]/a</value>
      <webElementGuid>5c0b5589-fe6a-4dd2-840c-007068326852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accept')]</value>
      <webElementGuid>223d7f19-0efe-42cc-9041-cfb88e70ae23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lekoma Lucky Mabala'])[1]/following::a[1]</value>
      <webElementGuid>e8b3dccc-8a81-41f1-8458-57f548300ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulu Lulo'])[1]/following::a[1]</value>
      <webElementGuid>ce322e35-0435-45e0-a056-743983376f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lolo Lolo'])[1]/preceding::a[1]</value>
      <webElementGuid>32aeb244-078f-4f99-8483-fb2b20862947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lekoma Lucky Mabala'])[2]/preceding::a[1]</value>
      <webElementGuid>34683a81-ffdf-4f6e-9eff-d660f4130f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>3d98db53-80cc-4262-af54-9670ae044bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SDICMS_TEST/Intake/AcceptInboxItem/19806')]</value>
      <webElementGuid>8514a460-1465-4f42-9926-8d2e66a8f2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>27ed957f-6ed3-4926-a26b-d0193428da14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SDICMS_TEST/Intake/AcceptInboxItem/19806' and (text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>507984f3-e0d4-4d5a-ad23-af410f9a52af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
