<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>19d3369c-9a9b-4c9c-a763-bc820e385fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resultLoading > div > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultLoading']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7015471-7897-4205-b02c-50cf787efccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif</value>
      <webElementGuid>89a49e38-d97b-4a6d-8ac9-28e81d30db8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultLoading&quot;)/div[1]/img[1]</value>
      <webElementGuid>f49ceafa-983d-4846-8cd2-83096f39c55b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultLoading']/div/img</value>
      <webElementGuid>24c99c1f-c34c-47e7-8b3b-897456c5a357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif')]</value>
      <webElementGuid>1bcf607a-140a-4b8e-9e15-450a9a642645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>d3425185-b6f4-469d-8cee-d76e8d6fc182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://testportal.dsd.gov.za/SDICMS_TEST/Images/ajax-loader.gif']</value>
      <webElementGuid>ee6e1e3c-1b93-41e4-9a45-ec97dff9b248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
