<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_Person.Identification_Number</name>
   <tag></tag>
   <elementGuidId>1b9371d0-2190-42b7-82b9-35f89dcdd85a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Identification_Number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identification_Number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39a7921e-c755-4da4-9710-74490805ab02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>96c88716-bf02-47fa-a6c8-9a54e1d93cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identification_Number</value>
      <webElementGuid>844bd07e-5d5a-4645-a221-a5ec6159dec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Identification_Number</value>
      <webElementGuid>7b875528-c162-4e5c-a822-899d9b44c713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4da02c25-5165-4ba9-9383-76d71241e31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identification_Number&quot;)</value>
      <webElementGuid>05787040-2798-49e3-8193-48c709a03081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identification_Number']</value>
      <webElementGuid>92e31913-e6fc-443f-b58d-c8d6c3297d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[4]/div[4]/input</value>
      <webElementGuid>e45fddfd-4d94-40f9-bbfd-eac35df70c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>a91129e0-f8ea-4ed6-857c-50fcd612eefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identification_Number' and @name = 'Person.Identification_Number' and @type = 'text']</value>
      <webElementGuid>6e259dba-13b4-40ac-afe0-603696f3ff81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
