<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Last_Name</name>
   <tag></tag>
   <elementGuidId>b603cf54-ffd3-444f-99d9-daefc776c102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LastNameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LastNameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29ef9009-5e66-466e-9a48-9209f791cb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ece533f8-6074-41b9-8043-de458e97ffb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LastNameText</value>
      <webElementGuid>e97fd3cc-a9c3-4786-ad81-5499454f071d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Last_Name</value>
      <webElementGuid>fddb046d-7979-4a2f-bb79-076a1d342a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>48cbaa3a-feb4-49ac-932e-0a27604aa37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>beb7c681-9a5f-4e30-89d8-cb74fce73208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b41c647-4cdc-4d0d-a091-c4a5d40c0a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LastNameText&quot;)</value>
      <webElementGuid>ae039b6d-3a54-42e4-b5f3-a4b6a3393437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LastNameText']</value>
      <webElementGuid>2842f3af-189c-42d2-9a9a-0015f9ec19db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[2]/div[4]/input</value>
      <webElementGuid>7ef7f304-933d-40b9-be5f-2ee58b252cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]/input</value>
      <webElementGuid>b8131467-07c3-4cdd-b92f-5af0b89906e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LastNameText' and @name = 'Person.Last_Name' and @type = 'text']</value>
      <webElementGuid>0ab679e1-16ed-45e6-b2f6-8b934fc29419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
