<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Date_Of_Birth</name>
   <tag></tag>
   <elementGuidId>2ce3f979-cf32-4cc9-8b25-e6e75cd731e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Date_of_Birth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Date_of_Birth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25361adb-92f0-4bb7-ab04-26100dd548ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>c3c33e83-7f4f-414e-a724-1dce3f42cf20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>659bfdf0-27c8-4fdb-b9f8-153683f9ce9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date of Birth must be a date.</value>
      <webElementGuid>cbf1f2ed-bf3d-4fe2-a385-ac48e2b35244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_of_Birth</value>
      <webElementGuid>26540352-8cad-4387-a213-0bf97c70be89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Date_Of_Birth</value>
      <webElementGuid>8bde6088-129f-4c42-b281-01a250360149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Click here to select Birth Date!</value>
      <webElementGuid>ea145bbc-37f8-4302-b810-15fc6394a94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>820342d4-9f02-47d5-b4bb-67660cc6e3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eca333f4-5272-451a-95bf-2233641217b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>876b642c-e4fa-4f19-a809-42b21d2238ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_of_Birth&quot;)</value>
      <webElementGuid>db7e907a-5999-4f3d-ade2-beb8b83c7c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Date_of_Birth']</value>
      <webElementGuid>0df26c3c-2583-47a4-97e4-d23a3c853e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>239146eb-c944-4416-8ecb-c4777ddd84fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>48b0c18a-c280-4b52-b07d-fefe79081188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Date_of_Birth' and @name = 'Person.Date_Of_Birth' and @placeholder = 'Click here to select Birth Date!' and @type = 'text']</value>
      <webElementGuid>e93b2aa5-4445-4eb3-a788-f226f5a61845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
