<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_Person.Phone_Number</name>
   <tag></tag>
   <elementGuidId>50f1a549-3dce-46f2-aa81-c162a7f5f5d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Person_Phone_Number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Person_Phone_Number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e481965b-2da5-4eb5-9124-f89f5368f051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2e6acdf-d9f7-4c09-adf9-367bf2133124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Person_Phone_Number</value>
      <webElementGuid>407640b9-bdff-433f-873c-7963b6ce2ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Phone_Number</value>
      <webElementGuid>da079bc5-95b2-43b6-be54-dffdaf2cc24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36a87a4f-1e35-4bb0-a41d-dd90568b6275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Person_Phone_Number&quot;)</value>
      <webElementGuid>eda2f562-e19a-4b5b-9469-b062849efba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Person_Phone_Number']</value>
      <webElementGuid>63ad36fc-d1d5-4e96-8fb9-61363abeeddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div/div[2]/input</value>
      <webElementGuid>1032ea08-f9ee-4407-b122-5ea872546dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>7430b501-85c8-4df9-96bf-d7430de90196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Person_Phone_Number' and @name = 'Person.Phone_Number' and @type = 'text']</value>
      <webElementGuid>a11c9afb-ed4e-4328-b5b2-2289db9a25b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
