<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Attention Deficit Disorder</name>
   <tag></tag>
   <elementGuidId>48d71f57-26af-43b9-b916-1ad4c8d43299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownDisabilityTypes_chosen > div.chosen-drop > ul.chosen-results > li.result-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DropdownDisabilityTypes_chosen']/div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bfb89858-cf60-4495-a7fd-f19259444537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-selected</value>
      <webElementGuid>6e9edc4d-1fe4-4b97-af48-64d2d7f588d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6ced38c5-b279-4cb9-a0ee-544a4645b863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attention Deficit Disorder</value>
      <webElementGuid>1acc867f-8186-4b1c-a365-7ad717b8909b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownDisabilityTypes_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;result-selected&quot;]</value>
      <webElementGuid>6bc65666-ed08-4351-b32d-55f2ec3eeba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownDisabilityTypes_chosen']/div/ul/li[3]</value>
      <webElementGuid>508db9ae-1338-4ee6-9c59-86181a0f33a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asperger Syndrome'])[2]/following::li[1]</value>
      <webElementGuid>d9540213-52c1-4985-adfe-9e74e61d685b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Please Select -'])[2]/following::li[2]</value>
      <webElementGuid>30385713-a2fb-4cbb-ab25-0f4f5e5be23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autism'])[2]/preceding::li[2]</value>
      <webElementGuid>f7121fdc-7dd9-45ca-bda9-5bb59ecfa120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[4]/div/div/ul/li[3]</value>
      <webElementGuid>7e253ea2-5414-4d1b-a981-d99959cedd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Attention Deficit Disorder' or . = 'Attention Deficit Disorder')]</value>
      <webElementGuid>dc0e6197-973e-4b56-b20a-855314e41984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
