<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Multiple Disabilities</name>
   <tag></tag>
   <elementGuidId>7b988028-2050-4f7c-ae70-abb0472dac9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.result-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DropdownDisabilityCategory_chosen']/div/ul/li[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6414d74c-4745-451e-9918-c683c4201e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-selected</value>
      <webElementGuid>9a4064d6-f5c7-4708-902e-21b0e1422489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>dfaa9591-1dc0-424a-8be1-66161e5e8756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Multiple Disabilities</value>
      <webElementGuid>07f70c9c-2470-4c61-a46a-8a5b7c742ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownDisabilityCategory_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;result-selected&quot;]</value>
      <webElementGuid>9bbeb26f-0a78-4462-9f8c-f58af25b5608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownDisabilityCategory_chosen']/div/ul/li[8]</value>
      <webElementGuid>8c1f0a62-0c12-46b0-9462-d47f0b91fe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mental Disability'])[2]/following::li[1]</value>
      <webElementGuid>52ef2b3c-01fb-4756-8a06-06f811d50fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intellectual Disability'])[2]/following::li[2]</value>
      <webElementGuid>e0ebc232-843d-450d-a1fb-a487c8777a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not applicable'])[2]/preceding::li[1]</value>
      <webElementGuid>b08538eb-f671-4728-b990-2af2452f7594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Physical Disability'])[2]/preceding::li[2]</value>
      <webElementGuid>fd5d07d0-980b-4f0c-ac01-4793b03d33af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[8]</value>
      <webElementGuid>c87ac219-418d-40ee-9447-2e926d4e9ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Multiple Disabilities' or . = 'Multiple Disabilities')]</value>
      <webElementGuid>07533a81-4833-4d01-952e-d25956fc7b0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
