<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>26c0a70d-446e-4ec2-a655-59fcec4ca000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-img-header-mobile']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;toggle-menu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aad64d7a-6c9e-44be-b534-97c981b2dc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>toggle-menu</value>
      <webElementGuid>d0674bad-5747-4b80-a385-e8e7966f60fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1dykungmee0hk.cloudfront.net/themes/skillate/images/menubutton.svg</value>
      <webElementGuid>8d0a7fd2-da98-42a6-afe2-d7813a618c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-img-header-mobile&quot;)/img[1]</value>
      <webElementGuid>692caebc-5117-4220-ba6a-17245964bebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-img-header-mobile']/img</value>
      <webElementGuid>3188d448-69c0-4343-8f2c-e022f1773c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='toggle-menu']</value>
      <webElementGuid>dd2a4ec4-f973-4efb-96b6-55027a9b33b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>28963600-eeb4-4212-b13b-e1211a3778d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'toggle-menu' and @src = 'https://d1dykungmee0hk.cloudfront.net/themes/skillate/images/menubutton.svg']</value>
      <webElementGuid>c176fec7-1ede-4f92-9b92-4dbd955859d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
