<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Send us an email</name>
   <tag></tag>
   <elementGuidId>82abd9b7-c314-43ee-856e-7e26b4e2bb4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-btn-banner-middle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='id-btn-banner-middle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a1787cf-d7d7-4a49-9eb6-7a7d2c5347a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>86b6db5c-bb48-4f66-9566-47febd346157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-btn-banner-middle</value>
      <webElementGuid>8f1129b9-20a6-4175-9179-d1bfd8e7ce69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:training@katalon.com</value>
      <webElementGuid>6e1b0889-0c13-4a95-becc-bfdce280f2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>e6e03cd8-d8db-4155-8e37-e03ba6cb3a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send us an email</value>
      <webElementGuid>43d2e131-c0a8-413f-8eec-6ba6f74fab53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-btn-banner-middle&quot;)</value>
      <webElementGuid>dcae99de-cd64-4854-856e-7a047e2cf06b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='id-btn-banner-middle']</value>
      <webElementGuid>4cb135c9-9bf0-4905-8cf5-d2311c064b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-720']/div/div[2]/div[2]/div/div[3]/button/a</value>
      <webElementGuid>f4dbd00f-5c32-4986-8cd1-941e72a57894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Send us an email')]</value>
      <webElementGuid>48df73b4-527d-48b4-9319-ffa3a052ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become our instructor'])[1]/following::a[1]</value>
      <webElementGuid>5126ade7-f2e5-436e-afc9-63603118378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all learning paths'])[1]/following::a[1]</value>
      <webElementGuid>a3ba948a-a63d-482b-a067-42cf8ddf7dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profession'])[1]/preceding::a[1]</value>
      <webElementGuid>d2bbceff-7d85-49dc-92b1-470558ae791a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send us an email']/parent::*</value>
      <webElementGuid>3149158c-e6a4-4668-b893-f02dbbb4aead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:training@katalon.com')]</value>
      <webElementGuid>43e11f55-8c89-43a1-9ab3-b71265280f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>03ad45d1-2b20-4af9-a978-8d22d9e94ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'id-btn-banner-middle' and @href = 'mailto:training@katalon.com' and (text() = 'Send us an email' or . = 'Send us an email')]</value>
      <webElementGuid>78e533c5-9165-4966-8b82-aac425b66538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
