<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Web testing</name>
   <tag></tag>
   <elementGuidId>d336369d-d8eb-46ed-b1c7-21f3c1ff3a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#learning-path-web-testing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='learning-path-web-testing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7772fc0b-2bd5-45a7-a427-7ba64a120ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skillate-tab-nav-link skillate-tab-childcat</value>
      <webElementGuid>fee9c257-90d4-4da5-b08d-51d87e1596ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>learning-path-web-testing</value>
      <webElementGuid>75b4fe76-1e07-48c1-8775-bcb8d1de3053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e4af5584-3534-40a3-b1ef-d32c4a7abc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-v-web-testing</value>
      <webElementGuid>75414186-9d73-4553-af6e-7f042d583425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Web testing</value>
      <webElementGuid>f88c6863-a1bd-4caa-8e15-4ed0d6550ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;learning-path-web-testing&quot;)</value>
      <webElementGuid>e57b1022-1688-4552-8f8c-0f744388084b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='learning-path-web-testing']</value>
      <webElementGuid>a6c0f189-8cb3-422c-8561-093081fbf1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='tab-learning-path']/div/div/div/ul/li[2]/a</value>
      <webElementGuid>f2ce0289-caa7-4c1d-ae00-3fe526a1842b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Web testing')]</value>
      <webElementGuid>ef6a92dd-d954-4bd8-9af0-73628b58157b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latest Leaning Paths'])[1]/following::a[2]</value>
      <webElementGuid>55f4809a-6945-4eaf-8130-2a6532612c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beginner'])[29]/preceding::a[1]</value>
      <webElementGuid>0dada90f-a710-47c3-baa2-5bf4bffddadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enroll Now'])[36]/preceding::a[1]</value>
      <webElementGuid>83d0bd71-5c92-489f-bd95-d218c12ba25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Web testing']/parent::*</value>
      <webElementGuid>097d6ca8-809a-4515-a918-8eedc1db40ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-v-web-testing')]</value>
      <webElementGuid>734bc873-b51b-48d3-a1d8-c2806583d795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>65eb8c38-63f4-40bd-89ca-ffe14b1558c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'learning-path-web-testing' and @href = '#tab-v-web-testing' and (text() = ' Web testing' or . = ' Web testing')]</value>
      <webElementGuid>3217745a-fb87-41ef-867b-6b818b0c882b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
