<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Is_Estimated_Age</name>
   <tag></tag>
   <elementGuidId>982f5b72-9b40-4195-b319-21f191098b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsEstimatedAge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsEstimatedAge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>610a90f3-ddd0-4515-bb9a-3732804e8ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>362d653c-3798-4f72-841a-21d75a1e0389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ff506ea-d3f4-4f98-8dd2-66147200f525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Estimated field is required.</value>
      <webElementGuid>f2b593fe-0afc-455b-8b33-101dd6f5f04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsEstimatedAge</value>
      <webElementGuid>f3ad4d80-7bdf-404b-97e7-b07f9abbba4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Is_Estimated_Age</value>
      <webElementGuid>cddc1c54-45c9-43de-bc68-e15401432c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1051eebe-d365-4796-9ce9-7e4f307af608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42fd9d3c-18ff-4f14-b151-a87fe17e9457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsEstimatedAge&quot;)</value>
      <webElementGuid>1214ab4b-b6bb-461f-86c4-d4f68135ed6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsEstimatedAge']</value>
      <webElementGuid>c738c0f6-c3e6-4fbf-b553-470c610563b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div[4]/div[5]/input</value>
      <webElementGuid>57648f87-7373-4679-a367-c45bbf6a0869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>706dcdce-d688-4a19-aad6-b8ecef338610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = 'IsEstimatedAge' and @name = 'Person.Is_Estimated_Age' and @type = 'checkbox']</value>
      <webElementGuid>162ddf7f-bd73-4e28-854d-492c00cdc561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
