<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Date_Of_Birth</name>
   <tag></tag>
   <elementGuidId>fda3d2d5-eb8a-4076-b01c-57ac24688fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Date_of_Birth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Date_of_Birth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56fc8c77-c0ad-4dfa-a32a-23340810776b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>a0093894-b451-4da3-9b65-22168b669f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21f2f689-adc9-4b78-8299-17cfb0aa30cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date of Birth must be a date.</value>
      <webElementGuid>1339a564-63b8-4cdd-9173-9e92e9eafcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_of_Birth</value>
      <webElementGuid>e10a15dd-cfb9-4d50-9902-3484504909cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Date_Of_Birth</value>
      <webElementGuid>d4c33c61-f7f6-462f-a06b-f8c20b5da91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Click here to select Birth Date!</value>
      <webElementGuid>a0827095-1246-4d4a-8475-a23984321e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e46615fa-f144-411c-b559-45de0c836c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4c5ea268-1ca9-472c-942c-f5f92a696a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b19a599-60f3-4997-8911-eecba1e12a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1994/11/01 00:00:00</value>
      <webElementGuid>c17df70b-224d-45b9-8327-a91a3a108924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9b57e41-06f8-4a18-8ae2-7b9745b6e5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_of_Birth&quot;)</value>
      <webElementGuid>e4edea11-1e7e-4e7c-82b5-b1b29fb07520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Date_of_Birth']</value>
      <webElementGuid>06a28a1b-652d-4f40-82b3-6f08e72fb749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>3bde61c9-bc8b-4eca-ad6f-b543a8110f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>a3c4ce71-8c66-4d57-924b-0515559a8bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Date_of_Birth' and @name = 'Person.Date_Of_Birth' and @placeholder = 'Click here to select Birth Date!' and @type = 'text']</value>
      <webElementGuid>74846933-2b28-4a36-85b6-5a6aee83a173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
