<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Last_Name</name>
   <tag></tag>
   <elementGuidId>bd5fb843-26f7-4338-af73-d1ab07bf2435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Person_Last_Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Person_Last_Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc108b93-f082-45bd-9730-f003f4b639b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d523a89d-a9cc-4aa0-9289-b495e4bd5e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Person_Last_Name</value>
      <webElementGuid>29898e1f-7e8a-4871-93e5-6ec789a4a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Last_Name</value>
      <webElementGuid>86dab38d-cd48-4871-92a8-a36894cef677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>79ec0027-faba-4788-80da-9effb83c22f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57f9d3fb-e780-4f8f-b6d5-bcda6b6aa212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kebautlwile</value>
      <webElementGuid>9f11f38c-328e-4431-af34-97d53dc78fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>abd33a50-dd7e-4986-aa64-38a344c6c8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Person_Last_Name&quot;)</value>
      <webElementGuid>b6bc0811-43f7-4fc6-a943-06c59b0534d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Person_Last_Name']</value>
      <webElementGuid>7a179772-7e61-4e94-b98e-33d37fb4fa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[4]/input</value>
      <webElementGuid>8ebfe05d-8824-4422-8bae-c3f66ed802cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]/input</value>
      <webElementGuid>4a0d1e2f-56de-4404-82cf-a929eeec3f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Person_Last_Name' and @name = 'Person.Last_Name' and @type = 'text']</value>
      <webElementGuid>c29643fa-a4c1-4a4c-a4d0-fe4cf76b30ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
