<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReceptionRegister.Reason_For_Visit</name>
   <tag></tag>
   <elementGuidId>ddb75825-aeb4-4416-89f2-c853bc7dc605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReceptionRegister_Reason_For_Visit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdbc129e-5b6b-49a7-a997-7d0adccb6cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>79f4e732-8388-4fde-a214-032d94fa6190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReceptionRegister_Reason_For_Visit</value>
      <webElementGuid>ceb3049c-2328-498a-8c66-502ac2d300f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reason_For_Visit</value>
      <webElementGuid>65ed88c7-2f03-46c6-902a-03f48d8a4068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6ea1f34-ae8c-47bc-8d61-dc5b4e6a09d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Thato</value>
      <webElementGuid>ffa5faea-50f9-4ae0-b55e-7e2acc24c33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReceptionRegister_Reason_For_Visit&quot;)</value>
      <webElementGuid>396ce41a-5600-4e6a-87c8-d53129cc00aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      <webElementGuid>039aaa73-2b61-4a4f-80dc-62e159d1284d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[2]/input</value>
      <webElementGuid>f78183d1-e999-40fe-98e5-beb3329c0043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e631f495-8e58-4e5b-951e-ed5cb2bf6f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReceptionRegister_Reason_For_Visit' and @name = 'ReceptionRegister.Reason_For_Visit' and @type = 'text']</value>
      <webElementGuid>755717eb-a7a1-4e88-ada3-0874669aa5d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
