<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Known As_Person.Known_As</name>
   <tag></tag>
   <elementGuidId>2507ca1a-0f31-43d7-a381-a219e66ca443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Person_Known_As</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Person_Known_As']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a9517ca-8446-490d-94d6-5c0331c9bfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>718a4f9c-0183-4803-b51f-00be42e31e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Person_Known_As</value>
      <webElementGuid>f9faaaa9-a6aa-431f-9ded-74f2d02993fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Known_As</value>
      <webElementGuid>867490bc-a57b-450b-ac10-849cffad7d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43a1438f-c10c-4dc0-ae27-deb75f69cb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Person_Known_As&quot;)</value>
      <webElementGuid>6355aadd-9815-458b-8cff-2d2e3b728384</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Person_Known_As']</value>
      <webElementGuid>f944b094-72a3-4222-ac95-dc087a0dee5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>100661ab-b8e8-4912-8868-5f0ef747ec03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>ddab9fd2-28a3-490c-b19b-5f3653cd3014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Person_Known_As' and @name = 'Person.Known_As' and @type = 'text']</value>
      <webElementGuid>884bba7a-21f5-4e1a-9a45-137f569f595b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
