<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Passport DocumentRSA ID Document</name>
   <tag></tag>
   <elementGuidId>9c532620-27d1-4506-a770-36da6e430dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownIdentificationType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownIdentificationType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4fb1c68b-72b1-4ba6-a5a6-96d2daf195a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7746ebfb-a44d-4c61-84a1-7a557a4a123d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1cb0432-5784-4461-83c4-5c4f41cf9f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Identification_Type_Id must be a number.</value>
      <webElementGuid>3657bcc6-c933-4e94-a3e7-f612e8c00a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownIdentificationType</value>
      <webElementGuid>ece89935-3a6d-4b28-8380-848f7626ff8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Identification_Type_Id</value>
      <webElementGuid>175883c5-1d69-400c-a8c4-4175f67f2c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passport Document
RSA ID Document
</value>
      <webElementGuid>6091f563-6422-4e5e-bf8d-66dcab2c60ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownIdentificationType&quot;)</value>
      <webElementGuid>83be77e6-bf4b-4c2f-a320-faf9e2d0aaeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownIdentificationType']</value>
      <webElementGuid>733fc567-3554-4317-bc89-c5ab14e6d4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div[3]/div[2]/select</value>
      <webElementGuid>f501445f-41da-45d1-9f91-0d1bfb77fa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification Type'])[1]/following::select[1]</value>
      <webElementGuid>5f3745d4-30af-436d-88b3-3ec24de4552d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Citizenship'])[1]/following::select[2]</value>
      <webElementGuid>6259f538-db16-4c84-ae34-76176d2b6129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Number'])[1]/preceding::select[1]</value>
      <webElementGuid>e198b907-973a-43c3-8271-a95c0c433319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/preceding::select[1]</value>
      <webElementGuid>ce4161d9-f94c-4f76-84e1-29a6ddf4ad2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>0602334c-f6c3-4204-ab77-6eb56ae6f338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownIdentificationType' and @name = 'Person.Identification_Type_Id' and (text() = 'Passport Document
RSA ID Document
' or . = 'Passport Document
RSA ID Document
')]</value>
      <webElementGuid>c5d43b91-85dc-4e18-a685-ba750d31bb6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
