<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -AnyAsianBlackColour_ee2822</name>
   <tag></tag>
   <elementGuidId>68a35e80-9e02-41d5-aeb3-f5b5e418df2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownPopulationGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownPopulationGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e05ead2-d694-4c10-bf29-9ba6d9ce1bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4b3fa2d-25c8-46d3-a083-7f9fd23dd1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a1430a1f-c52f-4b18-bf20-645465d112ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Population_Group_Id must be a number.</value>
      <webElementGuid>303a060d-2173-4836-a6ea-147522b2af13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownPopulationGroup</value>
      <webElementGuid>c4b08e20-e8fd-4216-8630-8bcfd7a8688e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Population_Group_Id</value>
      <webElementGuid>7c011c4c-d77a-42e0-a33c-39c98da49880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Any
Asian
Black
Coloured
Did not ask
Indian
Refused to answer
Unknown
White
</value>
      <webElementGuid>0ed72495-6799-4abc-803c-de43acdbce40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownPopulationGroup&quot;)</value>
      <webElementGuid>550cd69e-fbad-49c2-9292-c2fe725f00c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownPopulationGroup']</value>
      <webElementGuid>7d62b498-842b-4305-8184-14d4287575b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div[6]/div[4]/select</value>
      <webElementGuid>309f66a1-a6ff-4120-b1bb-e38c17472097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Population Group'])[1]/following::select[1]</value>
      <webElementGuid>d512da8a-ddd1-4cf8-95c7-f1e0311854c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/following::select[2]</value>
      <webElementGuid>b4f26f57-daf7-434b-9912-35e23939935a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Type'])[1]/preceding::select[1]</value>
      <webElementGuid>ca1c1564-b599-4266-ab38-11cc4b404f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sexual Orientation'])[1]/preceding::select[2]</value>
      <webElementGuid>726c9037-e538-48e1-a293-9ebb526d9be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]/select</value>
      <webElementGuid>9dbeebf1-7a1d-49f4-9012-4787631df9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownPopulationGroup' and @name = 'Person.Population_Group_Id' and (text() = '- Please select -
Any
Asian
Black
Coloured
Did not ask
Indian
Refused to answer
Unknown
White
' or . = '- Please select -
Any
Asian
Black
Coloured
Did not ask
Indian
Refused to answer
Unknown
White
')]</value>
      <webElementGuid>8ef396c7-ee17-4b58-a529-c663c14564b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
