<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -DivorcedLiving with_a7bd96</name>
   <tag></tag>
   <elementGuidId>e20baded-7c05-44f6-b3f7-ce3c9298f157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownMaritalStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownMaritalStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5cfeaa7a-5f6a-4b0e-956e-a35587eb772f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>728c9fcf-622d-49b5-9992-3f98437fbd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f09da803-8f4f-4a7f-95e7-cdc2d6bb8382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Marital_Status_Id must be a number.</value>
      <webElementGuid>d71a84ee-4eee-4403-bf71-f3750edc8620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownMaritalStatus</value>
      <webElementGuid>68aae953-4892-4b3a-b503-773080ca1241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Marital_Status_Id</value>
      <webElementGuid>970b7ec0-9933-4d10-b664-438a164f84f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Divorced
Living with Partner(Cohabitation)
Married
Not Applicable
Separated
Single
Traditional
Widowed
</value>
      <webElementGuid>8efbbb6b-c1f8-424e-b250-a4c6e6639024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownMaritalStatus&quot;)</value>
      <webElementGuid>3efc27cb-24df-41b2-a32a-ef75ec2f859a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownMaritalStatus']</value>
      <webElementGuid>3009acff-4f74-461d-abed-287f14c50ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div[6]/div[2]/select</value>
      <webElementGuid>102c5030-c756-4eec-9bbd-9c122a91c930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/following::select[1]</value>
      <webElementGuid>94e6cb93-7c7e-4a5c-b039-3f2e9a700964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::select[2]</value>
      <webElementGuid>eebc98bb-b059-48ba-859f-f4a6c0fa8158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Population Group'])[1]/preceding::select[1]</value>
      <webElementGuid>26b3d640-f789-42cd-af18-9d1809a47659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Type'])[1]/preceding::select[2]</value>
      <webElementGuid>4a18568b-0162-4c5c-adca-b13b92268dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/select</value>
      <webElementGuid>fbbd7ef1-e81f-4db6-867e-dd3c7358ff42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownMaritalStatus' and @name = 'Person.Marital_Status_Id' and (text() = '- Please select -
Divorced
Living with Partner(Cohabitation)
Married
Not Applicable
Separated
Single
Traditional
Widowed
' or . = '- Please select -
Divorced
Living with Partner(Cohabitation)
Married
Not Applicable
Separated
Single
Traditional
Widowed
')]</value>
      <webElementGuid>1a5f1f2a-feae-460f-b357-6eea404df0e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
