<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intake</name>
   <tag></tag>
   <elementGuidId>cbabe0c7-280a-4612-b5d3-d79306200372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Intake > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Intake']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>684088e3-0e95-4cbb-83db-d5e7f43f707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index</value>
      <webElementGuid>bca0e39a-dc51-4393-bfbe-79d0907347b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intake</value>
      <webElementGuid>eb11b0cd-be19-40f7-a30b-a12ffc723cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Intake&quot;)/a[1]</value>
      <webElementGuid>c2cd3e43-d8d8-400d-990e-66724eaa76dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Intake']/a</value>
      <webElementGuid>091488f2-8813-48bc-9b97-1512d5a6b992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intake')]</value>
      <webElementGuid>31b7eddb-0a37-4aa3-9b4b-f4daca69d076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDICMS'])[1]/following::a[2]</value>
      <webElementGuid>46d0f26f-e463-441c-8f58-dd9ddf51fcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPAR'])[1]/preceding::a[1]</value>
      <webElementGuid>9b1e1ccc-5bbb-413f-891c-42196ca84fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADS'])[1]/preceding::a[2]</value>
      <webElementGuid>34589ee1-8f0b-4933-90cd-83dc4717fbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intake']/parent::*</value>
      <webElementGuid>85816237-d2ab-4947-9d91-17e2a8b7840c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index')]</value>
      <webElementGuid>3d510fd8-aa73-40d4-afd5-606dda783624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>46aa2cb2-a573-4743-8630-e3bcc73e638c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index' and (text() = 'Intake' or . = 'Intake')]</value>
      <webElementGuid>20ac77ef-eeb9-49fa-9e4c-fde8892fd7f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
