<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Country1</name>
   <tag></tag>
   <elementGuidId>e123aa4b-9d5b-468f-a83d-561d4eeca164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EnquiredCounty_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EnquiredCounty_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf01af9b-e500-48f7-ae3b-b94f17b902c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1af47349-1edd-4687-ab59-88b0bef73568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a40b00f3-8f89-4581-ad7b-2d9ebf41af9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Selected_Country_Id must be a number.</value>
      <webElementGuid>a3e6f085-828e-4192-a72c-54067506b071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EnquiredCounty_1</value>
      <webElementGuid>12d2083f-5cb6-414e-8e2e-422a72123521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalAddress.Selected_Country_Id</value>
      <webElementGuid>756a5942-ef9f-426d-a650-2b980dda17f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
China
South Africa
Turkey
United States of America
Zimbabwe
</value>
      <webElementGuid>20f9bcb7-8355-484e-8779-a9eff2e13e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnquiredCounty_1&quot;)</value>
      <webElementGuid>61ed808c-44d0-4cc8-9bc4-acaead4e8264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EnquiredCounty_1']</value>
      <webElementGuid>909cf97e-5570-4b2e-b4dd-8d2d6bdab013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div[3]/div[2]/select</value>
      <webElementGuid>6b9e0d06-822b-47b8-a492-6977a930266e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[2]/following::select[1]</value>
      <webElementGuid>a819eb48-7f9f-4917-910f-1b184b02261e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 2'])[2]/following::select[1]</value>
      <webElementGuid>0b39a3aa-ae45-4cfd-9b33-21bfbece10ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[2]/preceding::select[1]</value>
      <webElementGuid>fbd978bf-8ed9-4ed6-98b1-9380a0300974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Municipality'])[2]/preceding::select[2]</value>
      <webElementGuid>d3824333-8d8a-41c6-9db4-edb512f72d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]/select</value>
      <webElementGuid>058305af-60a3-48f1-8589-cc68074c3ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EnquiredCounty_1' and @name = 'PostalAddress.Selected_Country_Id' and (text() = '- Please select -
China
South Africa
Turkey
United States of America
Zimbabwe
' or . = '- Please select -
China
South Africa
Turkey
United States of America
Zimbabwe
')]</value>
      <webElementGuid>22d015d7-74d0-41cc-992b-037df26fe4dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
