<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>District1</name>
   <tag></tag>
   <elementGuidId>5b5edfe4-5f00-46c1-9efa-eaacde5cd3d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EnquiredMagistratesId_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EnquiredMagistratesId_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a45f7cb-3a98-4258-989e-435ca5730525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c9a5f4aa-7fef-4daa-b15b-42ed604bd49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>236208a5-b90b-452d-b244-738de7b35b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Selected_Municipality_Id must be a number.</value>
      <webElementGuid>a4aedde4-4967-4fd6-8e2f-f8ebab38b402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EnquiredMagistratesId_1</value>
      <webElementGuid>fe7cdcda-f1a2-42e8-b8ff-181bc3778700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalAddress.Selected_Municipality_Id</value>
      <webElementGuid>63258119-c96e-4de1-9faf-572abe18e314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -Alfred NzoAmatholeBuffalo CityCacaduChris HaniDr Beyers NaudeEnoch MgijimaJoe GqabiNelson Mandela BayOR TamboRaymond MhlabaSarah BaartmanTabankuluWalter Sisulu</value>
      <webElementGuid>b1db3a30-c000-4e92-acc7-3824ca994ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnquiredMagistratesId_1&quot;)</value>
      <webElementGuid>b5396e3e-daa0-4d03-91f0-43b94f50ac71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EnquiredMagistratesId_1']</value>
      <webElementGuid>42fa3962-8009-4724-8d17-0e12ca49c1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div[5]/div[2]/select</value>
      <webElementGuid>95ee4292-0c9c-48e0-aecb-09b12684284f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Municipality'])[2]/following::select[1]</value>
      <webElementGuid>867d4a69-24db-41a7-85b8-1e42fbd2c623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[2]/following::select[2]</value>
      <webElementGuid>f58c37d5-6c99-4d3a-9a30-75b56c5c24a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[2]/preceding::select[1]</value>
      <webElementGuid>7824c9b6-bcd0-4dd8-8dd2-5707481a28a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Town'])[2]/preceding::select[2]</value>
      <webElementGuid>ea4a37b1-e534-4d34-8378-058185e38e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[5]/div[2]/select</value>
      <webElementGuid>85e87082-d9b5-4c33-baf4-dd141f589859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EnquiredMagistratesId_1' and @name = 'PostalAddress.Selected_Municipality_Id' and (text() = '- Please Select -Alfred NzoAmatholeBuffalo CityCacaduChris HaniDr Beyers NaudeEnoch MgijimaJoe GqabiNelson Mandela BayOR TamboRaymond MhlabaSarah BaartmanTabankuluWalter Sisulu' or . = '- Please Select -Alfred NzoAmatholeBuffalo CityCacaduChris HaniDr Beyers NaudeEnoch MgijimaJoe GqabiNelson Mandela BayOR TamboRaymond MhlabaSarah BaartmanTabankuluWalter Sisulu')]</value>
      <webElementGuid>68736abb-7c11-433c-a492-1bffac5e0758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
