<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>District</name>
   <tag></tag>
   <elementGuidId>f826b22e-6df1-4af6-9252-f72ead182590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EnquiredMagistratesId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EnquiredMagistratesId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d6dbecc-a23a-4419-af82-5edc16ec35f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>41fe5319-974c-4580-b3c1-e96275beddd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4742a22-62bd-4a3a-8bf6-9957fe98b161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Selected_Municipality_Id must be a number.</value>
      <webElementGuid>a1a98d29-0cb0-4ce8-aceb-e54a661842c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EnquiredMagistratesId</value>
      <webElementGuid>04cb8d49-92ec-49ed-9fff-c2b30cea180e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhysicalAddress.Selected_Municipality_Id</value>
      <webElementGuid>f68d3e5a-419a-408e-a928-73bd376183bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab6ae459-6274-4fad-8264-36de5dfa86bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -Alfred NzoAmatholeBuffalo CityCacaduChris HaniDr Beyers NaudeEnoch MgijimaJoe GqabiNelson Mandela BayOR TamboRaymond MhlabaSarah BaartmanTabankuluWalter Sisulu</value>
      <webElementGuid>07d516f9-443b-4d00-8d32-cdc9ec409bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnquiredMagistratesId&quot;)</value>
      <webElementGuid>8d0f5817-a00f-4c7c-893e-40364e4530f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EnquiredMagistratesId']</value>
      <webElementGuid>3e57777e-1994-4faf-9a77-496b90e0c8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[4]/div[5]/div[2]/select</value>
      <webElementGuid>eb0fde8b-28f0-4da0-b837-7a588a1fb60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Municipality'])[1]/following::select[1]</value>
      <webElementGuid>3b657c76-9018-43f4-b380-35b336300bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::select[2]</value>
      <webElementGuid>5867f3f0-8788-4eb4-89ae-06f70ab07540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[1]/preceding::select[1]</value>
      <webElementGuid>8451f99d-8c95-4168-814f-b0149ae06a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Town'])[1]/preceding::select[2]</value>
      <webElementGuid>100d056e-88a6-4d69-b7ac-70e56adcf9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>c49705c9-b222-4a69-afdf-62bc6bcaeb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EnquiredMagistratesId' and @name = 'PhysicalAddress.Selected_Municipality_Id' and (text() = '- Please Select -Alfred NzoAmatholeBuffalo CityCacaduChris HaniDr Beyers NaudeEnoch MgijimaJoe GqabiNelson Mandela BayOR TamboRaymond MhlabaSarah BaartmanTabankuluWalter Sisulu' or . = '- Please Select -Alfred NzoAmatholeBuffalo CityCacaduChris HaniDr Beyers NaudeEnoch MgijimaJoe GqabiNelson Mandela BayOR TamboRaymond MhlabaSarah BaartmanTabankuluWalter Sisulu')]</value>
      <webElementGuid>c3f753c6-cf4a-4ae9-b576-3598f168f6a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
