<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Second Fingerprint_ButtonSave</name>
   <tag></tag>
   <elementGuidId>6714b51f-8355-44a3-867f-c0bac71d8b21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ButtonSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ButtonSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb6aa33c-383b-4578-a83a-8667aad4a31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ce52d380-efc6-41a0-8916-2a31b408c202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ButtonSave</value>
      <webElementGuid>d252b5c6-08c4-4e08-a346-def6d0f56159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>c1375f2f-0665-4425-806a-e7b3394fce8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>1e63bce8-b4f0-4f21-bef4-c453596a5a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ButtonSave&quot;)</value>
      <webElementGuid>1df62e08-0c44-43ed-a532-1062248f5d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ButtonSave']</value>
      <webElementGuid>f0873f9b-c821-43f5-bbf2-282b287904ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='personDetailsForm']/div[2]/div[4]/input</value>
      <webElementGuid>82f782eb-30cb-4ff2-9544-ccf9371464cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>104b83c7-b6b0-4784-941c-ef15c9bb2d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'ButtonSave']</value>
      <webElementGuid>2eaa4900-0bb4-4337-a653-ca20c29d8ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
