<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Line 2_PostalAddress.Address_Line_2</name>
   <tag></tag>
   <elementGuidId>3d4fc2e2-126f-41f6-94f9-0f99cc02965e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PostalAddress_Address_Line_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PostalAddress_Address_Line_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e86d5e9-73db-42d4-b7ef-29736e86323f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e010387b-e1c5-4f9b-bb74-7fb8d83da123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PostalAddress_Address_Line_2</value>
      <webElementGuid>6bf07629-89f8-43fb-970a-8cd765749cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalAddress.Address_Line_2</value>
      <webElementGuid>d8e6bed7-c219-42be-9b08-765d67c559b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6174ca4-9019-4a36-8082-93d51674f644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PostalAddress_Address_Line_2&quot;)</value>
      <webElementGuid>2c7f0673-804c-401a-af56-0498ae271fd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PostalAddress_Address_Line_2']</value>
      <webElementGuid>715c0b79-f933-405a-a770-f2eecd0aff51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div[2]/div[2]/input</value>
      <webElementGuid>18d47328-dc34-4169-84d8-9c170897d092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/input</value>
      <webElementGuid>d804e781-a346-4356-a686-47978c9006c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PostalAddress_Address_Line_2' and @name = 'PostalAddress.Address_Line_2' and @type = 'text']</value>
      <webElementGuid>bcb03d76-5b21-431c-beac-43aad825ebb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
