<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Line 2_PhysicalAddress.Address_Line_2</name>
   <tag></tag>
   <elementGuidId>0550b34a-92b9-4f49-b53f-f05c1836a177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PhysicalAddress_Address_Line_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PhysicalAddress_Address_Line_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aab24153-5132-4ca6-81f9-5ab5efd31126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>366efdfb-e8b7-463c-bc4e-55103d04569c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhysicalAddress_Address_Line_2</value>
      <webElementGuid>2b6b379b-b980-49e7-92f4-87ee9503a515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhysicalAddress.Address_Line_2</value>
      <webElementGuid>974e630b-eb08-4d20-98d9-320ab54902dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>759fcf75-f29b-43c4-8930-32737fd8b722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhysicalAddress_Address_Line_2&quot;)</value>
      <webElementGuid>35f9b45a-4f67-41ca-a8ef-39ca08e48f73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PhysicalAddress_Address_Line_2']</value>
      <webElementGuid>552b3014-af22-4c7a-884a-d857c6711438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>55b6a84c-6b53-40f4-9818-fbdb388887af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/input</value>
      <webElementGuid>e835ec6e-89e4-4827-9e6e-d9fc962f4523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhysicalAddress_Address_Line_2' and @name = 'PhysicalAddress.Address_Line_2' and @type = 'text']</value>
      <webElementGuid>44a4bc51-7561-4a03-a518-1e14e93fd1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
