<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Line 1_PostalAddress.Address_Line_1</name>
   <tag></tag>
   <elementGuidId>12c29c5b-962b-44ef-9126-78b76ff0b58f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PostalAddress_Address_Line_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PostalAddress_Address_Line_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c26b48fa-92bf-48cb-a297-82f562c7bc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac847175-22f1-46e7-b2b6-201532b6d087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PostalAddress_Address_Line_1</value>
      <webElementGuid>3bb7d5b6-4c2f-4adb-8453-d2f5ad50fe42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalAddress.Address_Line_1</value>
      <webElementGuid>92ccf213-da15-4fef-8d50-74c1de9da0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>403b0527-1441-4418-a6c8-54d1e90da007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PostalAddress_Address_Line_1&quot;)</value>
      <webElementGuid>7e79e500-bf5b-4cb3-add1-fff3c080a3b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PostalAddress_Address_Line_1']</value>
      <webElementGuid>6d2fd7aa-d577-4c21-b2e4-0809a050fa9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div/div[2]/input</value>
      <webElementGuid>b8af16ac-204f-4696-b020-cdf32df85f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>90eeb3b1-7eec-48af-8cc1-6443bcd0ea06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PostalAddress_Address_Line_1' and @name = 'PostalAddress.Address_Line_1' and @type = 'text']</value>
      <webElementGuid>1406814c-a872-43c7-8ffa-2ed3d6375ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
