<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Municipality1</name>
   <tag></tag>
   <elementGuidId>0b37aaa9-fe8c-4d90-926e-2fe86e30a881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownPostalAddressLocalMunicipality</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownPostalAddressLocalMunicipality']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>394984a0-ba18-42de-b618-1e844dd7654c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fffb775e-b93b-4676-80d4-f1db7adbf144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9dd9f9c8-9bae-4b83-8a37-d21734a9c9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Selected_Local_Municipality_Id must be a number.</value>
      <webElementGuid>cc04b58d-ae56-4e95-9602-aa3f0cd4f8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownPostalAddressLocalMunicipality</value>
      <webElementGuid>db9ce352-8fec-4862-85a1-c8e96fbfcdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalAddress.Selected_Local_Municipality_Id</value>
      <webElementGuid>9986bdaa-e14e-4206-b790-cd48071bcaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -MatatieleMbizanaNtabankuluUmzimvubu</value>
      <webElementGuid>d8bb0dbc-3929-4a3b-9387-f33a204fc201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownPostalAddressLocalMunicipality&quot;)</value>
      <webElementGuid>ba082f39-a056-41b8-8726-2dc9a0ac3dfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownPostalAddressLocalMunicipality']</value>
      <webElementGuid>399e4bb1-5dc0-4595-a559-4a4bfdfa343c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div[6]/div[2]/select</value>
      <webElementGuid>b6ba77a8-de77-4483-9bb6-88e6391e9f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[2]/following::select[1]</value>
      <webElementGuid>b0729b01-8b63-4814-8b4a-97c2c90adfa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Municipality'])[2]/following::select[2]</value>
      <webElementGuid>bfa447ff-71b5-4457-ad71-f3b9f3af762d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Town'])[2]/preceding::select[1]</value>
      <webElementGuid>062c8877-1c0b-42b6-bb6e-0e02e2f8ea77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[2]/preceding::select[2]</value>
      <webElementGuid>9fbe2073-106f-4ff6-8a6b-a52fc54a4396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[6]/div[2]/select</value>
      <webElementGuid>53d55341-81b2-429a-8188-624675c09939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownPostalAddressLocalMunicipality' and @name = 'PostalAddress.Selected_Local_Municipality_Id' and (text() = '- Please Select -MatatieleMbizanaNtabankuluUmzimvubu' or . = '- Please Select -MatatieleMbizanaNtabankuluUmzimvubu')]</value>
      <webElementGuid>51dd9d7d-0a69-49e1-824a-426d23d91c06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
