<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Municipality</name>
   <tag></tag>
   <elementGuidId>182a2090-5f0c-4cb9-8f62-d947e47699ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownPhysicalAddressLocalMunicipality</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownPhysicalAddressLocalMunicipality']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0986c721-197e-46d3-b4c8-55da5bcfc26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2cf20987-2169-452c-b24b-297376a757de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fd92210c-73e5-4abc-8eff-ee81230c1d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Selected_Local_Municipality_Id must be a number.</value>
      <webElementGuid>4c35f625-16aa-4907-b78a-65545b650bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownPhysicalAddressLocalMunicipality</value>
      <webElementGuid>4e59722e-ceb4-4dc9-a862-ebf9a29de18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhysicalAddress.Selected_Local_Municipality_Id</value>
      <webElementGuid>e26651e0-cddc-44e1-8b08-93e50f200372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -MatatieleMbizanaNtabankuluUmzimvubu</value>
      <webElementGuid>934add91-046c-434e-a1fa-c92e60d0370f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownPhysicalAddressLocalMunicipality&quot;)</value>
      <webElementGuid>82fe54eb-f17a-4941-82e9-377d851f849e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownPhysicalAddressLocalMunicipality']</value>
      <webElementGuid>4608aa13-0031-4caf-90dd-f5593ed13980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[4]/div[6]/div[2]/select</value>
      <webElementGuid>08c07f72-2c79-4134-a1cc-eccf05768a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[1]/following::select[1]</value>
      <webElementGuid>b82ec9e7-20ad-47bb-af64-9f5cc060e3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Municipality'])[1]/following::select[2]</value>
      <webElementGuid>8a06c304-8319-4689-a481-c25a7807ef33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Town'])[1]/preceding::select[1]</value>
      <webElementGuid>d39494f0-d9d2-427a-8acd-bce242397b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::select[2]</value>
      <webElementGuid>2b993c1f-7036-4640-bdb6-a57cd66a5fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[6]/div[2]/select</value>
      <webElementGuid>dd479e79-417f-44d0-9904-ba0fc2e49460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownPhysicalAddressLocalMunicipality' and @name = 'PhysicalAddress.Selected_Local_Municipality_Id' and (text() = '- Please Select -MatatieleMbizanaNtabankuluUmzimvubu' or . = '- Please Select -MatatieleMbizanaNtabankuluUmzimvubu')]</value>
      <webElementGuid>a4a71ea5-8feb-4948-bd8c-e91c4286c8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
