<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Province</name>
   <tag></tag>
   <elementGuidId>8e025843-06f7-4cc7-8d8b-e07db9137a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EnquiredProvinceId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EnquiredProvinceId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c5aa2fe-23b0-4e3d-8f0e-b1fc1d7ffb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>91cb7bd0-7861-4f4f-9f5b-ff8acf09b6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b77e5866-51a9-4e86-8d06-33dfae071b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Selected_Province_Id must be a number.</value>
      <webElementGuid>cb563bcc-e23d-477f-91c1-54898069529a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EnquiredProvinceId</value>
      <webElementGuid>fe1218f0-57f8-428e-b0d6-7f1f5110ee59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhysicalAddress.Selected_Province_Id</value>
      <webElementGuid>78507776-e36a-43aa-8a4d-d7d7c68d2da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -Eastern CapeFree StateGautengKwaZulu NatalLimpopoMpumalangaNationalNorth WestNorthern CapeWestern Cape</value>
      <webElementGuid>7f9a574d-8d24-49b2-86f2-7f61e5459f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnquiredProvinceId&quot;)</value>
      <webElementGuid>d9b1151b-ae98-4bda-b015-d0eee80ef26f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EnquiredProvinceId']</value>
      <webElementGuid>cada8b1b-4961-4812-9c37-34f10803face</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[4]/div[4]/div[2]/select</value>
      <webElementGuid>563eafee-d5f8-4683-83eb-2fb1cfa7756e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::select[1]</value>
      <webElementGuid>777b8728-6b43-449a-8e62-5c21e5317365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>1752b3cb-0d6c-481f-a443-6d6572a5947c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Municipality'])[1]/preceding::select[1]</value>
      <webElementGuid>45d2fe1e-2216-4791-b6c8-a644faaf43b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[1]/preceding::select[2]</value>
      <webElementGuid>8170ca7c-6ae5-4132-b6fb-fba34b6d43f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div[2]/select</value>
      <webElementGuid>b9c3a94d-68cd-439e-b5d2-e0b06d594ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EnquiredProvinceId' and @name = 'PhysicalAddress.Selected_Province_Id' and (text() = '- Please Select -Eastern CapeFree StateGautengKwaZulu NatalLimpopoMpumalangaNationalNorth WestNorthern CapeWestern Cape' or . = '- Please Select -Eastern CapeFree StateGautengKwaZulu NatalLimpopoMpumalangaNationalNorth WestNorthern CapeWestern Cape')]</value>
      <webElementGuid>ebbff0fc-0ac0-43b6-8b14-41d46b4ba496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
