<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Province1</name>
   <tag></tag>
   <elementGuidId>0dd90c92-00c9-4e3b-8e94-1834d8345ede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EnquiredProvinceId_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EnquiredProvinceId_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>37e1da38-ff6c-4be6-9278-23967ff1c216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02d71caf-40b4-4c75-b392-af4b77c4d68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fd2f717f-899f-4419-9a85-898a9e0115af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Selected_Province_Id must be a number.</value>
      <webElementGuid>9a6a7d0a-684b-4319-ac78-5f0f7463678c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EnquiredProvinceId_1</value>
      <webElementGuid>e8f384cf-406e-4894-a6b9-4ad2b9e98e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalAddress.Selected_Province_Id</value>
      <webElementGuid>bf1341dd-54cf-4da4-b232-faaca8609473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -Eastern CapeFree StateGautengKwaZulu NatalLimpopoMpumalangaNationalNorth WestNorthern CapeWestern Cape</value>
      <webElementGuid>33d0310c-5e82-4353-9ae1-382ae85efefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnquiredProvinceId_1&quot;)</value>
      <webElementGuid>f7d8ee08-9ba2-414d-b519-ecc76bc0b7aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EnquiredProvinceId_1']</value>
      <webElementGuid>5da0d15c-22a6-4ee6-9150-2977051c24c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div[4]/div[2]/select</value>
      <webElementGuid>0645bf4d-9f46-4c3d-94a2-b2ea4047a8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[2]/following::select[1]</value>
      <webElementGuid>190cd852-dd36-4c67-ba74-afdbf7d66dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[2]/following::select[2]</value>
      <webElementGuid>c67eae3d-e413-4425-8042-b14ff7df9e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District Municipality'])[2]/preceding::select[1]</value>
      <webElementGuid>2c7f662a-44a1-4df3-a94e-4fc7f643a6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[2]/preceding::select[2]</value>
      <webElementGuid>be612922-f98f-4b8e-9d6d-213d30482c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div[2]/select</value>
      <webElementGuid>e9deb6c4-1615-4e52-84ec-302c11a70e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EnquiredProvinceId_1' and @name = 'PostalAddress.Selected_Province_Id' and (text() = '- Please Select -Eastern CapeFree StateGautengKwaZulu NatalLimpopoMpumalangaNationalNorth WestNorthern CapeWestern Cape' or . = '- Please Select -Eastern CapeFree StateGautengKwaZulu NatalLimpopoMpumalangaNationalNorth WestNorthern CapeWestern Cape')]</value>
      <webElementGuid>f564e7aa-adf9-4052-b8ab-fae5007608a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
