<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Town1</name>
   <tag></tag>
   <elementGuidId>ba88edad-6335-4612-ae28-34e3a404af89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EnquiredTownId_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EnquiredTownId_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>81a47e4f-3d66-4bce-9977-9a2d17c56ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6c5f534-962b-4135-8029-80b0568a759f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>febd7460-0f80-4a31-b768-3112946c9344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Town_Id must be a number.</value>
      <webElementGuid>51857aae-8a23-412d-9eac-301ebba96880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EnquiredTownId_1</value>
      <webElementGuid>ec86dc46-72f5-4cab-8866-c9c24e1909d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalAddress.Town_Id</value>
      <webElementGuid>ef43d214-e829-4723-b343-b960f1516611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -BertievaleCedarvilleDiahosvilleHarry Gwala ParkItsokoleleKhoapaLikhohlongMalutiMapfonteinMatatieleMjomlaMzingiziNkausNyanisoQueen`S MercySnakefieldTaylerville</value>
      <webElementGuid>f3c106ec-122e-487f-9647-c7b6dc936a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnquiredTownId_1&quot;)</value>
      <webElementGuid>317239fa-3a49-4ace-9621-39fa0d56ebbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EnquiredTownId_1']</value>
      <webElementGuid>798d1f6a-10ca-4aec-bb39-6cb4d5a9af89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div[7]/div[2]/select</value>
      <webElementGuid>5fb2ea84-9abd-46c6-8556-416463f05686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Town'])[2]/following::select[1]</value>
      <webElementGuid>9b69808d-6790-4180-9b33-0eb97de13890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[2]/following::select[2]</value>
      <webElementGuid>ef1ca28e-8b55-4130-a5d6-7359ed16c7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[2]/preceding::select[1]</value>
      <webElementGuid>8dc3aaf8-2866-4d7f-9305-da68a19ca13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piva System is Offline - Please make sure the PIVA Service is running'])[1]/preceding::select[2]</value>
      <webElementGuid>391676dd-bd21-4578-be51-ae37a4cdd1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[7]/div[2]/select</value>
      <webElementGuid>48edec2c-f4ce-4ea1-8ba9-2f77e3546536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EnquiredTownId_1' and @name = 'PostalAddress.Town_Id' and (text() = '- Please Select -BertievaleCedarvilleDiahosvilleHarry Gwala ParkItsokoleleKhoapaLikhohlongMalutiMapfonteinMatatieleMjomlaMzingiziNkausNyanisoQueen`S MercySnakefieldTaylerville' or . = '- Please Select -BertievaleCedarvilleDiahosvilleHarry Gwala ParkItsokoleleKhoapaLikhohlongMalutiMapfonteinMatatieleMjomlaMzingiziNkausNyanisoQueen`S MercySnakefieldTaylerville')]</value>
      <webElementGuid>6725cc07-c09c-429b-bbfd-f8c6c6afe279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
