<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Town</name>
   <tag></tag>
   <elementGuidId>6440d850-7712-4db3-8e8e-9066159407ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EnquiredTownId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EnquiredTownId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c05c1b77-f52c-40e0-aa8b-0c77db26548c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c85d1697-e3ef-4ec8-a028-762e1a20c7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fadd72ca-6e99-4e42-8d5f-fd7469be3580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Town_Id must be a number.</value>
      <webElementGuid>9bb0e424-ab9b-4227-bd88-1e947406a6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EnquiredTownId</value>
      <webElementGuid>9b55ea80-b2df-4be8-9e7c-3cc64b66d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhysicalAddress.Town_Id</value>
      <webElementGuid>9ab1ea6b-40af-4594-9a6e-888a518f8e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please Select -BertievaleCedarvilleDiahosvilleHarry Gwala ParkItsokoleleKhoapaLikhohlongMalutiMapfonteinMatatieleMjomlaMzingiziNkausNyanisoQueen`S MercySnakefieldTaylerville</value>
      <webElementGuid>266e8f9f-a4a9-4d50-816c-3f40f420e688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnquiredTownId&quot;)</value>
      <webElementGuid>9deca376-457f-4201-8912-4151c73fb207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EnquiredTownId']</value>
      <webElementGuid>ac5c7661-8e9d-4a6a-962e-8dc17834485e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[4]/div[7]/div[2]/select</value>
      <webElementGuid>21c9dc25-14f4-4597-8649-57687ffe17fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Town'])[1]/following::select[1]</value>
      <webElementGuid>faf6456f-7dde-4c58-9711-e8d1a65bec13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Municipality'])[1]/following::select[2]</value>
      <webElementGuid>9df37487-b5ef-45fd-b111-d574d5127098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::select[1]</value>
      <webElementGuid>b762a246-b91c-48bd-b84d-982fe06d10db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 1'])[2]/preceding::select[2]</value>
      <webElementGuid>d433bbcb-3229-4340-9df9-b56dd4f08286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[7]/div[2]/select</value>
      <webElementGuid>944a12a7-de24-443f-84ef-fae1b059f5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EnquiredTownId' and @name = 'PhysicalAddress.Town_Id' and (text() = '- Please Select -BertievaleCedarvilleDiahosvilleHarry Gwala ParkItsokoleleKhoapaLikhohlongMalutiMapfonteinMatatieleMjomlaMzingiziNkausNyanisoQueen`S MercySnakefieldTaylerville' or . = '- Please Select -BertievaleCedarvilleDiahosvilleHarry Gwala ParkItsokoleleKhoapaLikhohlongMalutiMapfonteinMatatieleMjomlaMzingiziNkausNyanisoQueen`S MercySnakefieldTaylerville')]</value>
      <webElementGuid>a59d7e89-1df1-49f3-ad61-44aabc30be01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
