<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intake</name>
   <tag></tag>
   <elementGuidId>3db1e949-7dba-4615-ab5d-a5b4c7db9b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Intake']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Intake > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cdb2558d-cad9-4eb9-8af7-a5d6761b3d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index</value>
      <webElementGuid>01453696-efe2-4b03-a69c-c0f9e9c19942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intake</value>
      <webElementGuid>088cc9fa-bae7-4e1d-9a03-2474a99c493a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Intake&quot;)/a[1]</value>
      <webElementGuid>f0a0adc5-ae47-45ab-bc0a-e63bc4a79fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Intake']/a</value>
      <webElementGuid>e2ef630e-b554-4e3b-9fa4-079e834b2279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intake')]</value>
      <webElementGuid>ce40da5d-82e1-4d9f-b1f5-cc2451fa8d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDICMS'])[1]/following::a[2]</value>
      <webElementGuid>01f2f662-a07c-40c6-b9ee-992209fda92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPAR'])[1]/preceding::a[1]</value>
      <webElementGuid>82aeb20d-812e-40ff-abd0-3e31c7986f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADS'])[1]/preceding::a[2]</value>
      <webElementGuid>24a46a48-cfa2-4c4f-9cc0-5f5a17c023d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intake']/parent::*</value>
      <webElementGuid>6e7e6dd6-de49-4080-ab17-7fffe2b988bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index')]</value>
      <webElementGuid>0dacd740-7251-42bb-a8bf-62c12a7afbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>c228299a-0a40-40c1-96b6-3f4ff0333ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index' and (text() = 'Intake' or . = 'Intake')]</value>
      <webElementGuid>b8ac822f-7e51-4d37-80b3-23fb7d498a0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
