<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client Ref No_Search_Client_Ref_No</name>
   <tag></tag>
   <elementGuidId>09a924ea-34d0-4f17-a72b-553b7f64d7c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Client_Ref_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Client_Ref_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bbf009c-7ae7-47e1-ad2a-301b7bbe69a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Client_Ref_No</value>
      <webElementGuid>7cb5bc36-971c-4a81-a9a0-3deb017de4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5966ce49-b1cf-4076-be4c-5a03afa812b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Client_Ref_No</value>
      <webElementGuid>6a9b5854-08de-4646-9246-404f4b5f50cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39a9e100-6ec9-477a-b4b5-f487e5d3df65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Client_Ref_No&quot;)</value>
      <webElementGuid>7418029f-5256-4f6b-89dd-9b1323e56480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Client_Ref_No']</value>
      <webElementGuid>9be16f71-d86a-4ddb-bfaa-794484cae76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[2]/input</value>
      <webElementGuid>c02e33a9-c5fa-49d5-9d25-b0324ffd9f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>15bfbae2-5c30-4a57-b967-424bfed5b9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Client_Ref_No' and @name = 'Search_Client_Ref_No' and @type = 'text']</value>
      <webElementGuid>5cd12fa7-ca40-4045-83f2-a3272991a3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
