<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identification Number_Search_Client_ID_No</name>
   <tag></tag>
   <elementGuidId>3e16b735-538a-4f19-9330-9b126eaa19dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Client_Id_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Client_Id_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edb7c919-9704-4069-a91b-7ce5f44ef769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3716fb9-af85-4756-94d1-851928810989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Client_Id_No</value>
      <webElementGuid>e5381a19-c36c-4108-ad13-88708b346739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Client_ID_No</value>
      <webElementGuid>d285f20a-603e-4db1-8af4-4f9c8d7eddc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edc3ee85-9346-460b-8fb2-0dc5b4bedbe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Client_Id_No&quot;)</value>
      <webElementGuid>16d7e407-3747-47a9-92f7-f61b7c5e5079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Client_Id_No']</value>
      <webElementGuid>e22fb08e-e59e-42a0-9a30-cd38e9446b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[4]/input</value>
      <webElementGuid>a949a5a0-d251-44e8-aa62-0e864a4e0dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b2b885ce-05bb-4d84-a129-c8d24fd9a8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Client_Id_No' and @name = 'Search_Client_ID_No' and @type = 'text']</value>
      <webElementGuid>56465a25-0ce3-4f8f-af34-61159be3da62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
