<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create anaccount</name>
   <tag></tag>
   <elementGuidId>4b5592d4-52aa-4822-a306-bd433d1306c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='createacc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#createacc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>183aef23-c448-4c75-af2c-6f015684d70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/create?.lang=en-US&amp;src=homepage&amp;activity=ybar-signin&amp;pspid=2023538075&amp;.done=https%3A%2F%2Fwww.yahoo.com%2F&amp;specId=yidregsimplified&amp;done=https%3A%2F%2Fwww.yahoo.com%2F</value>
      <webElementGuid>59d9c0f3-68b0-4a4e-a1fb-e3c4437e7297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createacc</value>
      <webElementGuid>7630e133-f589-4630-a0ad-2083d37f29ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ec37431-60d4-40d5-a1b4-ac35b0a230bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pure-button puree-button-secondary challenge-button</value>
      <webElementGuid>34059444-fcd8-403e-a286-bbcd3446d99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid-tracking</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0385a35a-1f0b-4455-953a-80060dfd117d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>elm:link;elmt:secondary;slk:signup;mKey:signup</value>
      <webElementGuid>2c9105ce-e1f6-4085-9770-9d25ab933ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create an account</value>
      <webElementGuid>4d290b40-b307-4177-ac8c-57b932804599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createacc&quot;)</value>
      <webElementGuid>107c26c0-d160-48a1-bb3f-02e1d5e797a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='createacc']</value>
      <webElementGuid>4c446afe-70e8-4912-ac98-9ddb12b5b221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-username-form']/div[4]/p/a</value>
      <webElementGuid>75ce19f3-e3f2-4c74-8d6a-185a5bbb0a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create an account')]</value>
      <webElementGuid>e0d3682c-40b4-4673-abde-0c86b2260783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot username?'])[1]/following::a[1]</value>
      <webElementGuid>a8533a4b-4b5d-4835-9326-47e8664ca748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stay signed in'])[1]/following::a[2]</value>
      <webElementGuid>2293eaa2-a387-4a8d-8c4c-f91a3b11b448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or, continue with'])[1]/preceding::a[1]</value>
      <webElementGuid>dbc98c8c-1f6b-4d05-891d-98b19147c856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='google'])[1]/preceding::a[1]</value>
      <webElementGuid>0552a6d3-538a-4ed9-93dd-1e1764e7b5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create an account']/parent::*</value>
      <webElementGuid>de1b69c6-da2d-4008-893d-3b1c16d162c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/create?.lang=en-US&amp;src=homepage&amp;activity=ybar-signin&amp;pspid=2023538075&amp;.done=https%3A%2F%2Fwww.yahoo.com%2F&amp;specId=yidregsimplified&amp;done=https%3A%2F%2Fwww.yahoo.com%2F')]</value>
      <webElementGuid>ea8baedf-38c6-4acd-b7bb-87ad5854b7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>64de6576-9111-407b-92e0-48aab55a6276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/create?.lang=en-US&amp;src=homepage&amp;activity=ybar-signin&amp;pspid=2023538075&amp;.done=https%3A%2F%2Fwww.yahoo.com%2F&amp;specId=yidregsimplified&amp;done=https%3A%2F%2Fwww.yahoo.com%2F' and @id = 'createacc' and (text() = 'Create an account' or . = 'Create an account')]</value>
      <webElementGuid>d02716b2-13ce-45ef-ae04-061a93c84b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
