<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Signin</name>
   <tag></tag>
   <elementGuidId>9ddf1a2d-8476-470f-aca0-c69be423d8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-landing']/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong.challenge-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>f0af3bfa-cf83-4c69-bbbd-76ab1c58820e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>challenge-heading</value>
      <webElementGuid>c29c1aa4-5688-4e2d-8d03-44aba4b6739c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>cfbb704c-07dd-40bc-aaed-2411ba3da743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-landing&quot;)/strong[@class=&quot;challenge-heading&quot;]</value>
      <webElementGuid>62d5094e-f927-4cb3-b9ea-c13bd469ea3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-landing']/strong</value>
      <webElementGuid>732e30d8-24c1-43d5-95e4-f5c8a3f4182d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::strong[1]</value>
      <webElementGuid>22340e0c-0be1-4837-97b8-2d85893ca088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='using your Yahoo account'])[1]/preceding::strong[1]</value>
      <webElementGuid>98e06a42-11cd-4679-9c51-d97e2cd9a8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Country Code'])[1]/preceding::strong[1]</value>
      <webElementGuid>4586aaba-3c62-4e2a-95d7-ce0036f0062e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in']/parent::*</value>
      <webElementGuid>b29207b4-07f0-40b3-a469-06d558572e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>cd2a95a9-67f9-4e48-9204-6a192054579a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>c6d9b47e-1e64-4e7f-bb1b-c16cdba53fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
