<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chosen-search-input default</name>
   <tag></tag>
   <elementGuidId>bc92a106-507f-4a7c-bddd-41700bfc7b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chosen-search-input.default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Select Some Options'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67cbfe6f-8105-4637-8232-63df1b3ddeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-search-input default</value>
      <webElementGuid>131dd090-8ca6-4fe8-8d08-63f0abe45770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>881f42c6-6e01-458b-bf99-fdad2d924ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03aaa535-84a4-4f5b-b372-ee175ba0a38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Select Some Options</value>
      <webElementGuid>0dda0862-d37f-4ed5-994f-eccec11cb961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownDisabilityTypes_chosen&quot;)/ul[@class=&quot;chosen-choices&quot;]/li[@class=&quot;search-field&quot;]/input[@class=&quot;chosen-search-input default&quot;]</value>
      <webElementGuid>27d04e3d-b1b2-4bb4-b564-e18478c824ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Select Some Options'])[2]</value>
      <webElementGuid>ce899b98-27c8-40ef-8df3-8fdd3a96190b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownDisabilityTypes_chosen']/ul/li/input</value>
      <webElementGuid>28c82457-840b-4f35-bf4f-8600551a88c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[4]/div/ul/li/input</value>
      <webElementGuid>3d2b7280-b9d3-46c9-a2c9-1c74370be134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>9a074d89-52a9-4737-a1aa-df42637ba9a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
