<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Hearing Disability - Due to Parkinsons Disease</name>
   <tag></tag>
   <elementGuidId>13637992-4046-47e4-9e71-c6735f6e2f29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = concat(&quot;Hearing Disability - Due to Parkinson&quot; , &quot;'&quot; , &quot;s Disease&quot;) or . = concat(&quot;Hearing Disability - Due to Parkinson&quot; , &quot;'&quot; , &quot;s Disease&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4c74daa7-924b-4118-bc1d-f7ed85bd5878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>2ff63e37-b66f-42b8-88c1-a1aa605f0cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6c9b7559-3135-4232-bd02-e2ce7ee1584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hearing Disability - Due to Parkinson's Disease</value>
      <webElementGuid>14929494-b5e1-4bb5-8c9a-74259dd748e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>cc637ed9-237b-4463-b2f0-2731a4b96928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = concat(&quot;Hearing Disability - Due to Parkinson&quot; , &quot;'&quot; , &quot;s Disease&quot;) or . = concat(&quot;Hearing Disability - Due to Parkinson&quot; , &quot;'&quot; , &quot;s Disease&quot;))]</value>
      <webElementGuid>346a8e6c-ba7a-4c02-b995-a497d9597155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
