<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intake</name>
   <tag></tag>
   <elementGuidId>2a090a77-9d42-4d6c-95f9-865c4dad2f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Intake > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Intake']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58fdc7b5-ce93-4b66-8f5e-54ed04488653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index</value>
      <webElementGuid>727e9e0f-3958-4c43-a91f-02494211fbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intake</value>
      <webElementGuid>888667d3-ea2f-4ed5-b7a0-c27f43c79d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Intake&quot;)/a[1]</value>
      <webElementGuid>e6c653fc-97c2-4444-ae8b-a58286b95c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Intake']/a</value>
      <webElementGuid>4ae042cc-5974-4235-afff-f6d66be3bd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intake')]</value>
      <webElementGuid>06ea85c3-b531-43be-8e2f-267d73832605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDICMS'])[1]/following::a[2]</value>
      <webElementGuid>4a02c1d9-6ecb-4031-8b43-dc24cab40cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPAR'])[1]/preceding::a[1]</value>
      <webElementGuid>5c2e6532-368b-4f67-82b0-64797baac375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADS'])[1]/preceding::a[2]</value>
      <webElementGuid>057dbd46-0bfc-44e8-881b-5e09d4e033bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intake']/parent::*</value>
      <webElementGuid>051541a1-2377-4713-b83f-aaf9a034251e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index')]</value>
      <webElementGuid>5941ac45-b39b-45d9-b4f4-093981336da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>050685cf-a34b-4f61-b559-de12aceacd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index' and (text() = 'Intake' or . = 'Intake')]</value>
      <webElementGuid>72d7b311-79c4-4931-a22f-28f9bb8b6f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
