<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intake</name>
   <tag></tag>
   <elementGuidId>ac231c2c-5e03-4d9b-afbc-7bab81d64d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Intake > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Intake']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f16d2fe-dea7-430f-816d-27519db79b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index</value>
      <webElementGuid>61bb30ec-a412-4fe9-8173-8ff24b8c67af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intake</value>
      <webElementGuid>b081877c-12e3-4a2c-ab8c-ab91f42c1665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Intake&quot;)/a[1]</value>
      <webElementGuid>030eec29-f7ee-4604-a938-e92af696b955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Intake']/a</value>
      <webElementGuid>f1ce9fc0-aeae-4d0b-b40c-3ab7df56a6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intake')]</value>
      <webElementGuid>7d46fc59-76e7-4804-bbcf-170b75b73201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDICMS'])[1]/following::a[2]</value>
      <webElementGuid>5c1443fd-480c-460d-bed4-d9667fdab1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPAR'])[1]/preceding::a[1]</value>
      <webElementGuid>72042711-cf81-4fcd-8deb-8cf4f001e333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADS'])[1]/preceding::a[2]</value>
      <webElementGuid>0c7bf018-1600-4d9e-bbe6-4d67923726c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intake']/parent::*</value>
      <webElementGuid>83c5dbb7-343b-464b-8d39-e7594c7232ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index')]</value>
      <webElementGuid>5083a4ed-85ef-43c6-88c5-a9e64db180ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>45a53e10-92f1-4d6d-b398-0a7bd457b39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testportal.dsd.gov.za/SDICMS_Test/Intake/Index' and (text() = 'Intake' or . = 'Intake')]</value>
      <webElementGuid>10cdfd9c-f6d4-4c18-9ae9-210fe539535f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
