<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identification Number_Search_Client_ID_No</name>
   <tag></tag>
   <elementGuidId>3f83709f-06f3-474a-86a2-a66563722763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search_Client_Id_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search_Client_Id_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b6ce3f5-89dc-46ef-9509-d812687635ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>819f98b8-10ae-421f-a4f5-f334fe4bbcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search_Client_Id_No</value>
      <webElementGuid>6a7b6bb5-0043-4fed-9f4e-fef86aff3d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search_Client_ID_No</value>
      <webElementGuid>64164e8c-3370-4238-972d-ff963592b34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59c659b8-4ed4-4af3-b859-b6744bddec3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search_Client_Id_No&quot;)</value>
      <webElementGuid>c281ca01-6548-4cc2-8048-1c131a9d7481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search_Client_Id_No']</value>
      <webElementGuid>0ee9d1ba-c597-4800-b3eb-a04a668c6274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intakePanel']/div[2]/div/div[4]/input</value>
      <webElementGuid>e8aee6ed-6635-4478-bff4-390c528081d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>99cc15b5-c799-4ad5-9826-668249c7a4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Search_Client_Id_No' and @name = 'Search_Client_ID_No' and @type = 'text']</value>
      <webElementGuid>f1451cd9-2609-466c-9a6e-2dd81286684c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
