<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Person.Age</name>
   <tag></tag>
   <elementGuidId>260d65f6-bc13-4fd3-a576-15ef571ba977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextboxAge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextboxAge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2dbb917-c21d-4a4c-8a52-f3a4b5231d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>84136d41-e971-4d13-bc9c-6ee3e6ef83d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9316279b-69ad-495b-857e-452b23f68f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Age must be a number.</value>
      <webElementGuid>37c1a3cd-5113-49aa-9ad6-6d876705bfe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextboxAge</value>
      <webElementGuid>83f58eda-8ab0-4bc1-aac2-a3eeaa5bfbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Age</value>
      <webElementGuid>32d9550e-b278-4dc6-842d-0fb80222444b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>753bdc28-a410-4ca4-9175-001fe33c0600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextboxAge&quot;)</value>
      <webElementGuid>5b5d9f90-8673-4475-8214-6c01a8488d16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextboxAge']</value>
      <webElementGuid>2dc2ec16-3e18-4189-8b83-b84b57961b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[5]/div[4]/input</value>
      <webElementGuid>5773697b-afa1-4fd6-aab4-14a6ad748a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/input</value>
      <webElementGuid>9081fa8a-d3ba-4886-bb77-e4f87db557a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextboxAge' and @name = 'Person.Age' and @type = 'text']</value>
      <webElementGuid>9685de58-f7f6-4ba5-b2e2-63d8c8e75cf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
