<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Referral to SWS</name>
   <tag></tag>
   <elementGuidId>6bc4d683-24da-4026-9b39-ddfd647294ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='wizardlist']/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7712027a-b5d0-47d3-a0a3-e9d7cd8d40a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab9</value>
      <webElementGuid>b276ccd9-55a9-45a2-987f-8619f86cee8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b210f9b0-61c3-4945-af8e-8724768a21a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Referral to SWS</value>
      <webElementGuid>578ca062-d541-48cc-b98e-45df22aa7682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizardlist&quot;)/li[9]/a[1]</value>
      <webElementGuid>bd8b8f86-f1de-4055-86dd-a6fbea23d3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='wizardlist']/li[9]/a</value>
      <webElementGuid>788e560e-001f-41e3-8dca-b912cd78b86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Referral to SWS')]</value>
      <webElementGuid>b87fdec4-f988-4ba5-9885-9bb6babf4518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referrals'])[1]/following::a[1]</value>
      <webElementGuid>f140eabe-cf56-4e66-b119-f8be4d2d69f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessment'])[1]/following::a[2]</value>
      <webElementGuid>13859a9a-91ae-44ee-b289-17f3ec22cb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Names'])[1]/preceding::a[1]</value>
      <webElementGuid>af7b2544-460a-4841-b881-158bddb7fc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>4bab0c90-45a6-4e38-b88f-b8ae59989b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Referral to SWS']/parent::*</value>
      <webElementGuid>4a57fc2a-502c-4b05-92e6-176f0bf85787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab9')]</value>
      <webElementGuid>2411af16-f146-4209-91aa-1953e5cd6667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>4b2e383b-1d92-4d99-a007-d757b590936d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab9' and (text() = 'Referral to SWS' or . = 'Referral to SWS')]</value>
      <webElementGuid>55efd72e-4064-4e11-9759-ddf79de71268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
