<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__IntakeAssessment.Date_Due</name>
   <tag></tag>
   <elementGuidId>8ef39703-e61a-4248-a885-60b229374e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Date_Due']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Date_Due</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>886487f2-5e3f-4b64-8a75-954be845aa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>2c6554a4-ab0d-4add-8045-d5b38bff3eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8bb985af-5e00-450e-8e81-8d56bc7e2e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date Due must be a date.</value>
      <webElementGuid>925689da-c6de-4235-b590-b47e3228ccec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_Due</value>
      <webElementGuid>dbe7369e-a61e-44df-b9d5-e561bcbcc405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IntakeAssessment.Date_Due</value>
      <webElementGuid>6e6c549c-8dc6-4663-a2bc-a8c12ca89d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Click here to select Due Date!</value>
      <webElementGuid>74df75a0-e674-4926-9fe3-2c3db9e9a519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e20ada97-db44-4c45-93af-ec883a90c684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fd3a8ed9-4ff7-4dd2-bfd2-98af7fa8699e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Due&quot;)</value>
      <webElementGuid>a9484931-0a21-4389-a74a-b932a5ec7ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Date_Due']</value>
      <webElementGuid>ce880811-c68d-4dff-aac2-74eda66224a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CaseAllocationCaseMng']/div[4]/div[2]/div/input</value>
      <webElementGuid>3c2fc169-31b3-4bc0-98e7-bbdc09a2eb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div[2]/div/input</value>
      <webElementGuid>a83e0094-967c-4524-be9c-2c3dfca80495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Date_Due' and @name = 'IntakeAssessment.Date_Due' and @placeholder = 'Click here to select Due Date!' and @type = 'text']</value>
      <webElementGuid>8e89c26a-c829-442f-a114-ae6cdf5d4169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
