<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__IntakeAssessment.Date_Allocated</name>
   <tag></tag>
   <elementGuidId>65112e63-a4f4-4f4a-93fb-5dba678559ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Date_Allocated']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Date_Allocated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffa09140-a32d-4dc1-a8fc-2a81b3b5030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jqueryui-marker-datepicker hasDatepicker</value>
      <webElementGuid>a8a4216f-0361-4c17-9412-32f42662a4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0d608a5-c38a-4ec4-86b1-7a76bfaf72b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date Allocated must be a date.</value>
      <webElementGuid>b8fdcd42-637a-436a-98ae-ad79e119c23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_Allocated</value>
      <webElementGuid>a79845fb-61f0-4a6c-8e84-6c5b30000a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IntakeAssessment.Date_Allocated</value>
      <webElementGuid>c455d3dc-ecfe-47f5-86b9-856451563273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Click here to select Allocation Date!</value>
      <webElementGuid>a3e58b8f-28f8-441c-93b4-134916a23a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f58b86b3-aef3-49ed-8a97-d4ff16661812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>543fd4d2-5789-4442-a8b0-84ab87c693bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Allocated&quot;)</value>
      <webElementGuid>c9574cdc-5488-4e60-80a6-c42dc61e49c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Date_Allocated']</value>
      <webElementGuid>0f469b95-306f-4bd7-8c43-7bd817461c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CaseAllocationCaseMng']/div[3]/div[2]/div/input</value>
      <webElementGuid>41b3350c-8757-4b32-86e1-266375bdef2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>308540d4-a5e5-48d4-bbdd-418c01aea3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Date_Allocated' and @name = 'IntakeAssessment.Date_Allocated' and @placeholder = 'Click here to select Allocation Date!' and @type = 'text']</value>
      <webElementGuid>8db1026e-300e-4752-9e16-bc1f721c3fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
