<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Supervisor Comments_IntakeAssessme_8b24ac</name>
   <tag></tag>
   <elementGuidId>f0509753-27c2-4d1e-be54-c6e189104fd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='SupervisorCommentsText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SupervisorCommentsText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a8b0d553-1b08-477a-89c9-5cab89adc7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>36d47143-e8e8-447e-bd4e-dbb40871d3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8d4b32aa-0abe-443d-ad2d-b0440b14f8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SupervisorCommentsText</value>
      <webElementGuid>e77bc4f2-d368-42d2-8100-ed8165fb6f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IntakeAssessment.Supervisor_Comments</value>
      <webElementGuid>5a7ea894-e6a5-4e31-b22a-51ec1c804814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a8b3a0eb-e2aa-4d9e-84a2-fea3a64212b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SupervisorCommentsText&quot;)</value>
      <webElementGuid>b197d6f4-8bd1-4c10-8d50-5c3ad71591cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='SupervisorCommentsText']</value>
      <webElementGuid>d21d1442-1e00-4c93-ae20-3ab9895b0f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CaseAllocationCaseMng']/div[5]/div[2]/textarea</value>
      <webElementGuid>a06d3b36-276b-485b-879e-291cb5438f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/textarea</value>
      <webElementGuid>bac37681-ddc9-43fa-b298-5d1f06c4118f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'SupervisorCommentsText' and @name = 'IntakeAssessment.Supervisor_Comments']</value>
      <webElementGuid>d89b202d-ad9e-4495-8fb4-461b117ba257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
