<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loading data. please wait_bg</name>
   <tag></tag>
   <elementGuidId>c7b4278d-eb2f-4277-a35e-094dc24b6bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultLoading']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a989a528-c13a-4cb8-ba4b-d2a8d9f2742a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg</value>
      <webElementGuid>94858c64-a81a-4b2b-833a-b0419973fd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultLoading&quot;)/div[@class=&quot;bg&quot;]</value>
      <webElementGuid>49c12ec2-30be-4cec-ba56-f2d032cd1d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultLoading']/div[2]</value>
      <webElementGuid>c15fe65b-70b3-4417-8934-20d899e40902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]</value>
      <webElementGuid>77731737-3fb6-41e6-8590-a7cbca19ae04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
