<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReceptionRegister.Reason_For_Visit</name>
   <tag></tag>
   <elementGuidId>d01583d3-475e-4e77-817d-bca49b8adc44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReceptionRegister_Reason_For_Visit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46ca7fed-9e94-4783-97cd-09a158707d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3fb29d02-ded6-41c1-adf7-6b0e265c9176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReceptionRegister_Reason_For_Visit</value>
      <webElementGuid>fc7d9cb0-6497-47bb-ab79-8a8ca80c1914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReceptionRegister.Reason_For_Visit</value>
      <webElementGuid>01c0fb7e-91bc-4cc2-a462-e84cbb9a05ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7132fe77-d3f8-4e94-b330-512e9bdf0974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13eee680-f2a2-49e0-9f34-89d669ba9d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2b6a192-bfef-41b7-a4ce-3b04c9741d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReceptionRegister_Reason_For_Visit&quot;)</value>
      <webElementGuid>99e52549-96b1-42b3-9bfc-a9cb5ef204d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReceptionRegister_Reason_For_Visit']</value>
      <webElementGuid>61bb5ad0-d030-439d-9e17-7b20640feac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personDetails']/div[2]/div/div[2]/input</value>
      <webElementGuid>92b6d8b2-3a83-4387-8b9c-4c9f53c337ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cffc4ed7-2e13-44ef-ab7d-5072e6b63581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReceptionRegister_Reason_For_Visit' and @name = 'ReceptionRegister.Reason_For_Visit' and @type = 'text']</value>
      <webElementGuid>9bac55af-5914-4077-9b27-ba8b265c8d61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
