<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_Person.Identification_Number</name>
   <tag></tag>
   <elementGuidId>624698c7-9739-4ab3-be12-600d63cd0860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identification_Number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Identification_Number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fefdd69d-8679-49d3-bdbb-843bf1d1e5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>05be9c40-a6e4-4491-ad9b-78b14e69a9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identification_Number</value>
      <webElementGuid>c211e51a-43ca-431b-88f5-62e93d0ba126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Identification_Number</value>
      <webElementGuid>43eda056-4a1a-47fb-92ff-b468de2261dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2841a67d-01ad-4eed-ba72-bf6fde322e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identification_Number&quot;)</value>
      <webElementGuid>f7246921-ced8-45cc-98b9-d3d741a5dfee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identification_Number']</value>
      <webElementGuid>bbf18efa-b63f-40e2-b1c2-36bacf0cfe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[4]/div[4]/input</value>
      <webElementGuid>10b7a6f5-d9c0-404b-8fd4-f38de7b1a5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>3f309d04-372e-47ac-91a5-0bae0c6c2d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identification_Number' and @name = 'Person.Identification_Number' and @type = 'text']</value>
      <webElementGuid>01ae937a-fdaf-477f-8c47-762c348a1282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
