<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select -BisexualGayHetero S_d0c270</name>
   <tag></tag>
   <elementGuidId>98ddcc6a-09fc-4a32-93af-0a9493591917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownSexualOrientation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DropdownSexualOrientation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>75e9e642-6cd9-4f27-a54e-7fd3428d1704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>66e2e25a-52fc-4a08-9ee4-5b0a153d1101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1acca16-3ac5-496b-aae2-523901363b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Sexual_Orientation_Id must be a number.</value>
      <webElementGuid>0653f9dd-2057-4439-b0d4-dce60578d2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownSexualOrientation</value>
      <webElementGuid>a6c36378-2e16-4aa6-92c1-a1be7a717a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Person.Sexual_Orientation_Id</value>
      <webElementGuid>00494cf3-3d44-49d6-a61c-3fa1d618adf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select -
Bisexual
Gay
Hetero Sexual
Intersex
LBGTIQA+
Lesbian
Queer
Transgender
</value>
      <webElementGuid>94975ba7-e4f3-48d3-9faa-7bd49ceec3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownSexualOrientation&quot;)</value>
      <webElementGuid>aaf49a21-54ea-4668-90e4-780f53cee212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownSexualOrientation']</value>
      <webElementGuid>086dd3da-3530-4cd3-9e09-1be4dcdab35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div[7]/div[4]/select</value>
      <webElementGuid>44fd83c8-d295-421f-a5a8-e1e51501303b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sexual Orientation'])[1]/following::select[1]</value>
      <webElementGuid>e9ce7070-770d-4e52-8422-a000935a702a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Type'])[1]/following::select[2]</value>
      <webElementGuid>5f703225-6ccc-4332-8bfd-5c9f7740f4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Population Group'])[1]/preceding::select[1]</value>
      <webElementGuid>9c762692-1a99-44dd-8b01-0ae06cb681d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/preceding::select[2]</value>
      <webElementGuid>4d3d2e74-720c-4e10-8cc0-38211fa7452a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[4]/select</value>
      <webElementGuid>cb2af2df-db8d-471c-bb0c-fc2655d3ca00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownSexualOrientation' and @name = 'Person.Sexual_Orientation_Id' and (text() = '- Please select -
Bisexual
Gay
Hetero Sexual
Intersex
LBGTIQA+
Lesbian
Queer
Transgender
' or . = '- Please select -
Bisexual
Gay
Hetero Sexual
Intersex
LBGTIQA+
Lesbian
Queer
Transgender
')]</value>
      <webElementGuid>a50c1036-3892-402e-bfd4-5c9ea181a314</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
