<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_About_keyword</name>
   <tag></tag>
   <elementGuidId>47ea38ea-136d-4afe-85ad-874ff44e146a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='keyword'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navbar__search.col-auto.ml-lg-auto.ml-xl-0 > #search-form > input[name=&quot;keyword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f6b05db-4613-4c4b-9d4f-621d898ab6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81c0aea9-0fb6-40a4-b3de-7fa76d9e3424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__search--input</value>
      <webElementGuid>3f4a516e-513b-4a34-bd4e-785c6f6e12e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>86c1e285-96f8-4f20-b428-928e98dd36ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e2ffbeac-0e23-48b4-845e-c99e024aa14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>7ec5e79c-df75-4893-a446-a63076b886c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-auto flex-lg-grow-1 flex-xl-grow-0 d-none d-lg-flex order-4 navbar__links-and-search order-lg-2 ml-lg-auto&quot;]/div[@class=&quot;row align-items-center flex-grow-1&quot;]/div[@class=&quot;navbar__search col-auto  ml-lg-auto ml-xl-0&quot;]/form[@id=&quot;search-form&quot;]/input[@class=&quot;navbar__search--input&quot;]</value>
      <webElementGuid>3c1fd55a-6629-4d09-ae21-4d36559a1819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='keyword'])[2]</value>
      <webElementGuid>9eb1b06b-7c3d-49c7-a665-bfcd2254abda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='search-form']/input)[2]</value>
      <webElementGuid>6e989f20-a44b-4557-bf30-25df1f5fb175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/form/input</value>
      <webElementGuid>a9fb06ed-98cc-4678-9f24-e6a9dea5ad66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @name = 'keyword']</value>
      <webElementGuid>bdedbd09-e49a-44a5-9f61-856febd6ce10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
