<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_copious software director</name>
   <tag></tag>
   <elementGuidId>4f019193-cc02-49e3-a53a-587ed702957d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c7mM1c']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c7mM1c > div.wM6W7d > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e76f8e03-ca5a-4c91-9926-49738b7fcfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>copious software director</value>
      <webElementGuid>c1bef90a-d86c-4d03-962b-54659c520104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c7mM1c&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>21471ccf-623d-4507-9f44-0d8278e64d62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c7mM1c']/div/span</value>
      <webElementGuid>cadf4206-e9ca-4953-bccc-f7aebd7a370f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::span[1]</value>
      <webElementGuid>9cd8a7fb-0d87-4a28-a0b5-f9e633008b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more'])[2]/following::span[2]</value>
      <webElementGuid>f11d4739-4d62-4b78-99b3-10663a954b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/div/div/span</value>
      <webElementGuid>0b1fb2ea-fb4e-4726-8482-7a5f0084ad80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'copious software director' or . = 'copious software director')]</value>
      <webElementGuid>460d82ea-8d53-40fb-b9fa-eb27c679ba5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
