<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_See all jobs</name>
   <tag></tag>
   <elementGuidId>581ac25d-174f-4117-ad2b-c59c327f6734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.job_preview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section/div/div/div[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2ea5ae6-a099-4766-a12d-89a70c141712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>job_preview</value>
      <webElementGuid>036fabd4-3823-4fc4-8109-2c2c99116a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See all jobs</value>
      <webElementGuid>5664a515-0f98-447c-a730-c1e618eb5a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]/div[@class=&quot;left_content&quot;]/div[@class=&quot;searchbar_section&quot;]/div[@class=&quot;search_result&quot;]/a[1]/div[@class=&quot;job_preview&quot;]</value>
      <webElementGuid>9dd3f0c1-845f-4e11-b934-a0857c17a06f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div/div/div[2]/a/div</value>
      <webElementGuid>9df91521-ce3c-4012-a819-85bcf9e52bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not match your search'])[1]/following::div[1]</value>
      <webElementGuid>58b7c63c-560c-4168-84de-429e83cf67e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='starts here'])[1]/following::div[6]</value>
      <webElementGuid>181d90d4-fbcf-4e8a-9fce-b05036630d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Katalon'])[1]/preceding::div[10]</value>
      <webElementGuid>e566842e-03be-4416-be3d-aa0c7fd5d1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment spotlight'])[1]/preceding::div[14]</value>
      <webElementGuid>527acd9d-cd9d-412e-afde-73353f87c3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='See all jobs']/parent::*</value>
      <webElementGuid>e3fcc699-7e45-467d-ab95-1d93f6bd934f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/div/div/div[2]/a/div</value>
      <webElementGuid>6a8d78c2-46df-40bb-beb0-9c8d04275efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'See all jobs' or . = 'See all jobs')]</value>
      <webElementGuid>65396489-e9e6-4bb8-bac8-b53e014e7f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
