<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>8b2c3744-cba2-4936-960a-eb85a4e411f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search_input > div.search_icon > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f84e193c-06c7-4a63-8372-d93b8d136945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/careers-website/homepage/search_icon.svg</value>
      <webElementGuid>a64733f4-7956-478c-bc52-0adc58ce5598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]/div[@class=&quot;left_content&quot;]/div[@class=&quot;searchbar_section&quot;]/div[@class=&quot;search_input&quot;]/div[@class=&quot;search_icon&quot;]/img[1]</value>
      <webElementGuid>3768ec0a-a14b-4c35-9ecc-e89dc7c0542e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div/div/div/div/img</value>
      <webElementGuid>dedd8cba-869f-4289-a907-46a8fd2e5e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://d1h3p5fzmizjvp.cloudfront.net/careers-website/homepage/search_icon.svg')])[3]</value>
      <webElementGuid>415fd161-acb2-4eb3-b021-8359a26db09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/div/div/div/div/img</value>
      <webElementGuid>f3317f98-0100-4cdf-a9b7-ae2256b95cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/careers-website/homepage/search_icon.svg']</value>
      <webElementGuid>ec2d5bf9-f219-4864-8259-95dd49c34027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
